/*
  Warnings:

  - You are about to drop the column `ENABLE_WHATSAPP_BOT` on the `Settings` table. All the data in the column will be lost.

*/
-- RedefineTables
PRAGMA defer_foreign_keys=ON;
PRAGMA foreign_keys=OFF;
CREATE TABLE "new_Settings" (
    "id" INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT DEFAULT 1,
    "ENABLE_WHATSAPP_BOT_FUND_REPORT" BOOLEAN NOT NULL DEFAULT true,
    "ENABLE_WHATSAPP_BOT_DUTY_REPORT" BOOLEAN NOT NULL DEFAULT true,
    "ENABLE_WHATSAPP_BOT_SUBJECT_SCHEDULE_REMINDER" BOOLEAN NOT NULL DEFAULT true,
    "ENABLE_WHATSAPP_BOT_BIRTHDAY_REMINDER" BOOLEAN NOT NULL DEFAULT true
);
INSERT INTO "new_Settings" ("ENABLE_WHATSAPP_BOT_BIRTHDAY_REMINDER", "ENABLE_WHATSAPP_BOT_DUTY_REPORT", "ENABLE_WHATSAPP_BOT_FUND_REPORT", "ENABLE_WHATSAPP_BOT_SUBJECT_SCHEDULE_REMINDER", "id") SELECT "ENABLE_WHATSAPP_BOT_BIRTHDAY_REMINDER", "ENABLE_WHATSAPP_BOT_DUTY_REPORT", "ENABLE_WHATSAPP_BOT_FUND_REPORT", "ENABLE_WHATSAPP_BOT_SUBJECT_SCHEDULE_REMINDER", "id" FROM "Settings";
DROP TABLE "Settings";
ALTER TABLE "new_Settings" RENAME TO "Settings";
PRAGMA foreign_keys=ON;
PRAGMA defer_foreign_keys=OFF;
