/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
 * This file exports the `Duty` model and its related types.
 *
 * 🟢 You can import this file directly.
 */
import type * as runtime from "@prisma/client/runtime/client"
import type * as $Enums from "../enums.js"
import type * as Prisma from "../internal/prismaNamespace.js"

/**
 * Model Duty
 * 
 */
export type DutyModel = runtime.Types.Result.DefaultSelection<Prisma.$DutyPayload>

export type AggregateDuty = {
  _count: DutyCountAggregateOutputType | null
  _min: DutyMinAggregateOutputType | null
  _max: DutyMaxAggregateOutputType | null
}

export type DutyMinAggregateOutputType = {
  id: string | null
  title: string | null
  createdAt: Date | null
}

export type DutyMaxAggregateOutputType = {
  id: string | null
  title: string | null
  createdAt: Date | null
}

export type DutyCountAggregateOutputType = {
  id: number
  title: number
  createdAt: number
  _all: number
}


export type DutyMinAggregateInputType = {
  id?: true
  title?: true
  createdAt?: true
}

export type DutyMaxAggregateInputType = {
  id?: true
  title?: true
  createdAt?: true
}

export type DutyCountAggregateInputType = {
  id?: true
  title?: true
  createdAt?: true
  _all?: true
}

export type DutyAggregateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which Duty to aggregate.
   */
  where?: Prisma.DutyWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of Duties to fetch.
   */
  orderBy?: Prisma.DutyOrderByWithRelationInput | Prisma.DutyOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the start position
   */
  cursor?: Prisma.DutyWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` Duties from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` Duties.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Count returned Duties
  **/
  _count?: true | DutyCountAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the minimum value
  **/
  _min?: DutyMinAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the maximum value
  **/
  _max?: DutyMaxAggregateInputType
}

export type GetDutyAggregateType<T extends DutyAggregateArgs> = {
      [P in keyof T & keyof AggregateDuty]: P extends '_count' | 'count'
    ? T[P] extends true
      ? number
      : Prisma.GetScalarType<T[P], AggregateDuty[P]>
    : Prisma.GetScalarType<T[P], AggregateDuty[P]>
}




export type DutyGroupByArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.DutyWhereInput
  orderBy?: Prisma.DutyOrderByWithAggregationInput | Prisma.DutyOrderByWithAggregationInput[]
  by: Prisma.DutyScalarFieldEnum[] | Prisma.DutyScalarFieldEnum
  having?: Prisma.DutyScalarWhereWithAggregatesInput
  take?: number
  skip?: number
  _count?: DutyCountAggregateInputType | true
  _min?: DutyMinAggregateInputType
  _max?: DutyMaxAggregateInputType
}

export type DutyGroupByOutputType = {
  id: string
  title: string
  createdAt: Date
  _count: DutyCountAggregateOutputType | null
  _min: DutyMinAggregateOutputType | null
  _max: DutyMaxAggregateOutputType | null
}

type GetDutyGroupByPayload<T extends DutyGroupByArgs> = Prisma.PrismaPromise<
  Array<
    Prisma.PickEnumerable<DutyGroupByOutputType, T['by']> &
      {
        [P in ((keyof T) & (keyof DutyGroupByOutputType))]: P extends '_count'
          ? T[P] extends boolean
            ? number
            : Prisma.GetScalarType<T[P], DutyGroupByOutputType[P]>
          : Prisma.GetScalarType<T[P], DutyGroupByOutputType[P]>
      }
    >
  >



export type DutyWhereInput = {
  AND?: Prisma.DutyWhereInput | Prisma.DutyWhereInput[]
  OR?: Prisma.DutyWhereInput[]
  NOT?: Prisma.DutyWhereInput | Prisma.DutyWhereInput[]
  id?: Prisma.StringFilter<"Duty"> | string
  title?: Prisma.StringFilter<"Duty"> | string
  createdAt?: Prisma.DateTimeFilter<"Duty"> | Date | string
}

export type DutyOrderByWithRelationInput = {
  id?: Prisma.SortOrder
  title?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
}

export type DutyWhereUniqueInput = Prisma.AtLeast<{
  id?: string
  AND?: Prisma.DutyWhereInput | Prisma.DutyWhereInput[]
  OR?: Prisma.DutyWhereInput[]
  NOT?: Prisma.DutyWhereInput | Prisma.DutyWhereInput[]
  title?: Prisma.StringFilter<"Duty"> | string
  createdAt?: Prisma.DateTimeFilter<"Duty"> | Date | string
}, "id">

export type DutyOrderByWithAggregationInput = {
  id?: Prisma.SortOrder
  title?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  _count?: Prisma.DutyCountOrderByAggregateInput
  _max?: Prisma.DutyMaxOrderByAggregateInput
  _min?: Prisma.DutyMinOrderByAggregateInput
}

export type DutyScalarWhereWithAggregatesInput = {
  AND?: Prisma.DutyScalarWhereWithAggregatesInput | Prisma.DutyScalarWhereWithAggregatesInput[]
  OR?: Prisma.DutyScalarWhereWithAggregatesInput[]
  NOT?: Prisma.DutyScalarWhereWithAggregatesInput | Prisma.DutyScalarWhereWithAggregatesInput[]
  id?: Prisma.StringWithAggregatesFilter<"Duty"> | string
  title?: Prisma.StringWithAggregatesFilter<"Duty"> | string
  createdAt?: Prisma.DateTimeWithAggregatesFilter<"Duty"> | Date | string
}

export type DutyCreateInput = {
  id?: string
  title: string
  createdAt?: Date | string
}

export type DutyUncheckedCreateInput = {
  id?: string
  title: string
  createdAt?: Date | string
}

export type DutyUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  title?: Prisma.StringFieldUpdateOperationsInput | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type DutyUncheckedUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  title?: Prisma.StringFieldUpdateOperationsInput | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type DutyCreateManyInput = {
  id?: string
  title: string
  createdAt?: Date | string
}

export type DutyUpdateManyMutationInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  title?: Prisma.StringFieldUpdateOperationsInput | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type DutyUncheckedUpdateManyInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  title?: Prisma.StringFieldUpdateOperationsInput | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type DutyCountOrderByAggregateInput = {
  id?: Prisma.SortOrder
  title?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
}

export type DutyMaxOrderByAggregateInput = {
  id?: Prisma.SortOrder
  title?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
}

export type DutyMinOrderByAggregateInput = {
  id?: Prisma.SortOrder
  title?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
}



export type DutySelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  title?: boolean
  createdAt?: boolean
}, ExtArgs["result"]["duty"]>

export type DutySelectCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  title?: boolean
  createdAt?: boolean
}, ExtArgs["result"]["duty"]>

export type DutySelectUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  title?: boolean
  createdAt?: boolean
}, ExtArgs["result"]["duty"]>

export type DutySelectScalar = {
  id?: boolean
  title?: boolean
  createdAt?: boolean
}

export type DutyOmit<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetOmit<"id" | "title" | "createdAt", ExtArgs["result"]["duty"]>

export type $DutyPayload<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  name: "Duty"
  objects: {}
  scalars: runtime.Types.Extensions.GetPayloadResult<{
    id: string
    title: string
    createdAt: Date
  }, ExtArgs["result"]["duty"]>
  composites: {}
}

export type DutyGetPayload<S extends boolean | null | undefined | DutyDefaultArgs> = runtime.Types.Result.GetResult<Prisma.$DutyPayload, S>

export type DutyCountArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> =
  Omit<DutyFindManyArgs, 'select' | 'include' | 'distinct' | 'omit'> & {
    select?: DutyCountAggregateInputType | true
  }

export interface DutyDelegate<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> {
  [K: symbol]: { types: Prisma.TypeMap<ExtArgs>['model']['Duty'], meta: { name: 'Duty' } }
  /**
   * Find zero or one Duty that matches the filter.
   * @param {DutyFindUniqueArgs} args - Arguments to find a Duty
   * @example
   * // Get one Duty
   * const duty = await prisma.duty.findUnique({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUnique<T extends DutyFindUniqueArgs>(args: Prisma.SelectSubset<T, DutyFindUniqueArgs<ExtArgs>>): Prisma.Prisma__DutyClient<runtime.Types.Result.GetResult<Prisma.$DutyPayload<ExtArgs>, T, "findUnique", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find one Duty that matches the filter or throw an error with `error.code='P2025'`
   * if no matches were found.
   * @param {DutyFindUniqueOrThrowArgs} args - Arguments to find a Duty
   * @example
   * // Get one Duty
   * const duty = await prisma.duty.findUniqueOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUniqueOrThrow<T extends DutyFindUniqueOrThrowArgs>(args: Prisma.SelectSubset<T, DutyFindUniqueOrThrowArgs<ExtArgs>>): Prisma.Prisma__DutyClient<runtime.Types.Result.GetResult<Prisma.$DutyPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first Duty that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {DutyFindFirstArgs} args - Arguments to find a Duty
   * @example
   * // Get one Duty
   * const duty = await prisma.duty.findFirst({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirst<T extends DutyFindFirstArgs>(args?: Prisma.SelectSubset<T, DutyFindFirstArgs<ExtArgs>>): Prisma.Prisma__DutyClient<runtime.Types.Result.GetResult<Prisma.$DutyPayload<ExtArgs>, T, "findFirst", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first Duty that matches the filter or
   * throw `PrismaKnownClientError` with `P2025` code if no matches were found.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {DutyFindFirstOrThrowArgs} args - Arguments to find a Duty
   * @example
   * // Get one Duty
   * const duty = await prisma.duty.findFirstOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirstOrThrow<T extends DutyFindFirstOrThrowArgs>(args?: Prisma.SelectSubset<T, DutyFindFirstOrThrowArgs<ExtArgs>>): Prisma.Prisma__DutyClient<runtime.Types.Result.GetResult<Prisma.$DutyPayload<ExtArgs>, T, "findFirstOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find zero or more Duties that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {DutyFindManyArgs} args - Arguments to filter and select certain fields only.
   * @example
   * // Get all Duties
   * const duties = await prisma.duty.findMany()
   * 
   * // Get first 10 Duties
   * const duties = await prisma.duty.findMany({ take: 10 })
   * 
   * // Only select the `id`
   * const dutyWithIdOnly = await prisma.duty.findMany({ select: { id: true } })
   * 
   */
  findMany<T extends DutyFindManyArgs>(args?: Prisma.SelectSubset<T, DutyFindManyArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$DutyPayload<ExtArgs>, T, "findMany", GlobalOmitOptions>>

  /**
   * Create a Duty.
   * @param {DutyCreateArgs} args - Arguments to create a Duty.
   * @example
   * // Create one Duty
   * const Duty = await prisma.duty.create({
   *   data: {
   *     // ... data to create a Duty
   *   }
   * })
   * 
   */
  create<T extends DutyCreateArgs>(args: Prisma.SelectSubset<T, DutyCreateArgs<ExtArgs>>): Prisma.Prisma__DutyClient<runtime.Types.Result.GetResult<Prisma.$DutyPayload<ExtArgs>, T, "create", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Create many Duties.
   * @param {DutyCreateManyArgs} args - Arguments to create many Duties.
   * @example
   * // Create many Duties
   * const duty = await prisma.duty.createMany({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   *     
   */
  createMany<T extends DutyCreateManyArgs>(args?: Prisma.SelectSubset<T, DutyCreateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Create many Duties and returns the data saved in the database.
   * @param {DutyCreateManyAndReturnArgs} args - Arguments to create many Duties.
   * @example
   * // Create many Duties
   * const duty = await prisma.duty.createManyAndReturn({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Create many Duties and only return the `id`
   * const dutyWithIdOnly = await prisma.duty.createManyAndReturn({
   *   select: { id: true },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  createManyAndReturn<T extends DutyCreateManyAndReturnArgs>(args?: Prisma.SelectSubset<T, DutyCreateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$DutyPayload<ExtArgs>, T, "createManyAndReturn", GlobalOmitOptions>>

  /**
   * Delete a Duty.
   * @param {DutyDeleteArgs} args - Arguments to delete one Duty.
   * @example
   * // Delete one Duty
   * const Duty = await prisma.duty.delete({
   *   where: {
   *     // ... filter to delete one Duty
   *   }
   * })
   * 
   */
  delete<T extends DutyDeleteArgs>(args: Prisma.SelectSubset<T, DutyDeleteArgs<ExtArgs>>): Prisma.Prisma__DutyClient<runtime.Types.Result.GetResult<Prisma.$DutyPayload<ExtArgs>, T, "delete", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Update one Duty.
   * @param {DutyUpdateArgs} args - Arguments to update one Duty.
   * @example
   * // Update one Duty
   * const duty = await prisma.duty.update({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  update<T extends DutyUpdateArgs>(args: Prisma.SelectSubset<T, DutyUpdateArgs<ExtArgs>>): Prisma.Prisma__DutyClient<runtime.Types.Result.GetResult<Prisma.$DutyPayload<ExtArgs>, T, "update", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Delete zero or more Duties.
   * @param {DutyDeleteManyArgs} args - Arguments to filter Duties to delete.
   * @example
   * // Delete a few Duties
   * const { count } = await prisma.duty.deleteMany({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   * 
   */
  deleteMany<T extends DutyDeleteManyArgs>(args?: Prisma.SelectSubset<T, DutyDeleteManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more Duties.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {DutyUpdateManyArgs} args - Arguments to update one or more rows.
   * @example
   * // Update many Duties
   * const duty = await prisma.duty.updateMany({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  updateMany<T extends DutyUpdateManyArgs>(args: Prisma.SelectSubset<T, DutyUpdateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more Duties and returns the data updated in the database.
   * @param {DutyUpdateManyAndReturnArgs} args - Arguments to update many Duties.
   * @example
   * // Update many Duties
   * const duty = await prisma.duty.updateManyAndReturn({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Update zero or more Duties and only return the `id`
   * const dutyWithIdOnly = await prisma.duty.updateManyAndReturn({
   *   select: { id: true },
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  updateManyAndReturn<T extends DutyUpdateManyAndReturnArgs>(args: Prisma.SelectSubset<T, DutyUpdateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$DutyPayload<ExtArgs>, T, "updateManyAndReturn", GlobalOmitOptions>>

  /**
   * Create or update one Duty.
   * @param {DutyUpsertArgs} args - Arguments to update or create a Duty.
   * @example
   * // Update or create a Duty
   * const duty = await prisma.duty.upsert({
   *   create: {
   *     // ... data to create a Duty
   *   },
   *   update: {
   *     // ... in case it already exists, update
   *   },
   *   where: {
   *     // ... the filter for the Duty we want to update
   *   }
   * })
   */
  upsert<T extends DutyUpsertArgs>(args: Prisma.SelectSubset<T, DutyUpsertArgs<ExtArgs>>): Prisma.Prisma__DutyClient<runtime.Types.Result.GetResult<Prisma.$DutyPayload<ExtArgs>, T, "upsert", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>


  /**
   * Count the number of Duties.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {DutyCountArgs} args - Arguments to filter Duties to count.
   * @example
   * // Count the number of Duties
   * const count = await prisma.duty.count({
   *   where: {
   *     // ... the filter for the Duties we want to count
   *   }
   * })
  **/
  count<T extends DutyCountArgs>(
    args?: Prisma.Subset<T, DutyCountArgs>,
  ): Prisma.PrismaPromise<
    T extends runtime.Types.Utils.Record<'select', any>
      ? T['select'] extends true
        ? number
        : Prisma.GetScalarType<T['select'], DutyCountAggregateOutputType>
      : number
  >

  /**
   * Allows you to perform aggregations operations on a Duty.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {DutyAggregateArgs} args - Select which aggregations you would like to apply and on what fields.
   * @example
   * // Ordered by age ascending
   * // Where email contains prisma.io
   * // Limited to the 10 users
   * const aggregations = await prisma.user.aggregate({
   *   _avg: {
   *     age: true,
   *   },
   *   where: {
   *     email: {
   *       contains: "prisma.io",
   *     },
   *   },
   *   orderBy: {
   *     age: "asc",
   *   },
   *   take: 10,
   * })
  **/
  aggregate<T extends DutyAggregateArgs>(args: Prisma.Subset<T, DutyAggregateArgs>): Prisma.PrismaPromise<GetDutyAggregateType<T>>

  /**
   * Group by Duty.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {DutyGroupByArgs} args - Group by arguments.
   * @example
   * // Group by city, order by createdAt, get count
   * const result = await prisma.user.groupBy({
   *   by: ['city', 'createdAt'],
   *   orderBy: {
   *     createdAt: true
   *   },
   *   _count: {
   *     _all: true
   *   },
   * })
   * 
  **/
  groupBy<
    T extends DutyGroupByArgs,
    HasSelectOrTake extends Prisma.Or<
      Prisma.Extends<'skip', Prisma.Keys<T>>,
      Prisma.Extends<'take', Prisma.Keys<T>>
    >,
    OrderByArg extends Prisma.True extends HasSelectOrTake
      ? { orderBy: DutyGroupByArgs['orderBy'] }
      : { orderBy?: DutyGroupByArgs['orderBy'] },
    OrderFields extends Prisma.ExcludeUnderscoreKeys<Prisma.Keys<Prisma.MaybeTupleToUnion<T['orderBy']>>>,
    ByFields extends Prisma.MaybeTupleToUnion<T['by']>,
    ByValid extends Prisma.Has<ByFields, OrderFields>,
    HavingFields extends Prisma.GetHavingFields<T['having']>,
    HavingValid extends Prisma.Has<ByFields, HavingFields>,
    ByEmpty extends T['by'] extends never[] ? Prisma.True : Prisma.False,
    InputErrors extends ByEmpty extends Prisma.True
    ? `Error: "by" must not be empty.`
    : HavingValid extends Prisma.False
    ? {
        [P in HavingFields]: P extends ByFields
          ? never
          : P extends string
          ? `Error: Field "${P}" used in "having" needs to be provided in "by".`
          : [
              Error,
              'Field ',
              P,
              ` in "having" needs to be provided in "by"`,
            ]
      }[HavingFields]
    : 'take' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "take", you also need to provide "orderBy"'
    : 'skip' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "skip", you also need to provide "orderBy"'
    : ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
          ? never
          : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
      }[OrderFields]
  >(args: Prisma.SubsetIntersection<T, DutyGroupByArgs, OrderByArg> & InputErrors): {} extends InputErrors ? GetDutyGroupByPayload<T> : Prisma.PrismaPromise<InputErrors>
/**
 * Fields of the Duty model
 */
readonly fields: DutyFieldRefs;
}

/**
 * The delegate class that acts as a "Promise-like" for Duty.
 * Why is this prefixed with `Prisma__`?
 * Because we want to prevent naming conflicts as mentioned in
 * https://github.com/prisma/prisma-client-js/issues/707
 */
export interface Prisma__DutyClient<T, Null = never, ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> extends Prisma.PrismaPromise<T> {
  readonly [Symbol.toStringTag]: "PrismaPromise"
  /**
   * Attaches callbacks for the resolution and/or rejection of the Promise.
   * @param onfulfilled The callback to execute when the Promise is resolved.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of which ever callback is executed.
   */
  then<TResult1 = T, TResult2 = never>(onfulfilled?: ((value: T) => TResult1 | PromiseLike<TResult1>) | undefined | null, onrejected?: ((reason: any) => TResult2 | PromiseLike<TResult2>) | undefined | null): runtime.Types.Utils.JsPromise<TResult1 | TResult2>
  /**
   * Attaches a callback for only the rejection of the Promise.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of the callback.
   */
  catch<TResult = never>(onrejected?: ((reason: any) => TResult | PromiseLike<TResult>) | undefined | null): runtime.Types.Utils.JsPromise<T | TResult>
  /**
   * Attaches a callback that is invoked when the Promise is settled (fulfilled or rejected). The
   * resolved value cannot be modified from the callback.
   * @param onfinally The callback to execute when the Promise is settled (fulfilled or rejected).
   * @returns A Promise for the completion of the callback.
   */
  finally(onfinally?: (() => void) | undefined | null): runtime.Types.Utils.JsPromise<T>
}




/**
 * Fields of the Duty model
 */
export interface DutyFieldRefs {
  readonly id: Prisma.FieldRef<"Duty", 'String'>
  readonly title: Prisma.FieldRef<"Duty", 'String'>
  readonly createdAt: Prisma.FieldRef<"Duty", 'DateTime'>
}
    

// Custom InputTypes
/**
 * Duty findUnique
 */
export type DutyFindUniqueArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Duty
   */
  select?: Prisma.DutySelect<ExtArgs> | null
  /**
   * Omit specific fields from the Duty
   */
  omit?: Prisma.DutyOmit<ExtArgs> | null
  /**
   * Filter, which Duty to fetch.
   */
  where: Prisma.DutyWhereUniqueInput
}

/**
 * Duty findUniqueOrThrow
 */
export type DutyFindUniqueOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Duty
   */
  select?: Prisma.DutySelect<ExtArgs> | null
  /**
   * Omit specific fields from the Duty
   */
  omit?: Prisma.DutyOmit<ExtArgs> | null
  /**
   * Filter, which Duty to fetch.
   */
  where: Prisma.DutyWhereUniqueInput
}

/**
 * Duty findFirst
 */
export type DutyFindFirstArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Duty
   */
  select?: Prisma.DutySelect<ExtArgs> | null
  /**
   * Omit specific fields from the Duty
   */
  omit?: Prisma.DutyOmit<ExtArgs> | null
  /**
   * Filter, which Duty to fetch.
   */
  where?: Prisma.DutyWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of Duties to fetch.
   */
  orderBy?: Prisma.DutyOrderByWithRelationInput | Prisma.DutyOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for Duties.
   */
  cursor?: Prisma.DutyWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` Duties from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` Duties.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of Duties.
   */
  distinct?: Prisma.DutyScalarFieldEnum | Prisma.DutyScalarFieldEnum[]
}

/**
 * Duty findFirstOrThrow
 */
export type DutyFindFirstOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Duty
   */
  select?: Prisma.DutySelect<ExtArgs> | null
  /**
   * Omit specific fields from the Duty
   */
  omit?: Prisma.DutyOmit<ExtArgs> | null
  /**
   * Filter, which Duty to fetch.
   */
  where?: Prisma.DutyWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of Duties to fetch.
   */
  orderBy?: Prisma.DutyOrderByWithRelationInput | Prisma.DutyOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for Duties.
   */
  cursor?: Prisma.DutyWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` Duties from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` Duties.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of Duties.
   */
  distinct?: Prisma.DutyScalarFieldEnum | Prisma.DutyScalarFieldEnum[]
}

/**
 * Duty findMany
 */
export type DutyFindManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Duty
   */
  select?: Prisma.DutySelect<ExtArgs> | null
  /**
   * Omit specific fields from the Duty
   */
  omit?: Prisma.DutyOmit<ExtArgs> | null
  /**
   * Filter, which Duties to fetch.
   */
  where?: Prisma.DutyWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of Duties to fetch.
   */
  orderBy?: Prisma.DutyOrderByWithRelationInput | Prisma.DutyOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for listing Duties.
   */
  cursor?: Prisma.DutyWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` Duties from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` Duties.
   */
  skip?: number
  distinct?: Prisma.DutyScalarFieldEnum | Prisma.DutyScalarFieldEnum[]
}

/**
 * Duty create
 */
export type DutyCreateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Duty
   */
  select?: Prisma.DutySelect<ExtArgs> | null
  /**
   * Omit specific fields from the Duty
   */
  omit?: Prisma.DutyOmit<ExtArgs> | null
  /**
   * The data needed to create a Duty.
   */
  data: Prisma.XOR<Prisma.DutyCreateInput, Prisma.DutyUncheckedCreateInput>
}

/**
 * Duty createMany
 */
export type DutyCreateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to create many Duties.
   */
  data: Prisma.DutyCreateManyInput | Prisma.DutyCreateManyInput[]
}

/**
 * Duty createManyAndReturn
 */
export type DutyCreateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Duty
   */
  select?: Prisma.DutySelectCreateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the Duty
   */
  omit?: Prisma.DutyOmit<ExtArgs> | null
  /**
   * The data used to create many Duties.
   */
  data: Prisma.DutyCreateManyInput | Prisma.DutyCreateManyInput[]
}

/**
 * Duty update
 */
export type DutyUpdateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Duty
   */
  select?: Prisma.DutySelect<ExtArgs> | null
  /**
   * Omit specific fields from the Duty
   */
  omit?: Prisma.DutyOmit<ExtArgs> | null
  /**
   * The data needed to update a Duty.
   */
  data: Prisma.XOR<Prisma.DutyUpdateInput, Prisma.DutyUncheckedUpdateInput>
  /**
   * Choose, which Duty to update.
   */
  where: Prisma.DutyWhereUniqueInput
}

/**
 * Duty updateMany
 */
export type DutyUpdateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to update Duties.
   */
  data: Prisma.XOR<Prisma.DutyUpdateManyMutationInput, Prisma.DutyUncheckedUpdateManyInput>
  /**
   * Filter which Duties to update
   */
  where?: Prisma.DutyWhereInput
  /**
   * Limit how many Duties to update.
   */
  limit?: number
}

/**
 * Duty updateManyAndReturn
 */
export type DutyUpdateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Duty
   */
  select?: Prisma.DutySelectUpdateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the Duty
   */
  omit?: Prisma.DutyOmit<ExtArgs> | null
  /**
   * The data used to update Duties.
   */
  data: Prisma.XOR<Prisma.DutyUpdateManyMutationInput, Prisma.DutyUncheckedUpdateManyInput>
  /**
   * Filter which Duties to update
   */
  where?: Prisma.DutyWhereInput
  /**
   * Limit how many Duties to update.
   */
  limit?: number
}

/**
 * Duty upsert
 */
export type DutyUpsertArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Duty
   */
  select?: Prisma.DutySelect<ExtArgs> | null
  /**
   * Omit specific fields from the Duty
   */
  omit?: Prisma.DutyOmit<ExtArgs> | null
  /**
   * The filter to search for the Duty to update in case it exists.
   */
  where: Prisma.DutyWhereUniqueInput
  /**
   * In case the Duty found by the `where` argument doesn't exist, create a new Duty with this data.
   */
  create: Prisma.XOR<Prisma.DutyCreateInput, Prisma.DutyUncheckedCreateInput>
  /**
   * In case the Duty was found with the provided `where` argument, update it with this data.
   */
  update: Prisma.XOR<Prisma.DutyUpdateInput, Prisma.DutyUncheckedUpdateInput>
}

/**
 * Duty delete
 */
export type DutyDeleteArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Duty
   */
  select?: Prisma.DutySelect<ExtArgs> | null
  /**
   * Omit specific fields from the Duty
   */
  omit?: Prisma.DutyOmit<ExtArgs> | null
  /**
   * Filter which Duty to delete.
   */
  where: Prisma.DutyWhereUniqueInput
}

/**
 * Duty deleteMany
 */
export type DutyDeleteManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which Duties to delete
   */
  where?: Prisma.DutyWhereInput
  /**
   * Limit how many Duties to delete.
   */
  limit?: number
}

/**
 * Duty without action
 */
export type DutyDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Duty
   */
  select?: Prisma.DutySelect<ExtArgs> | null
  /**
   * Omit specific fields from the Duty
   */
  omit?: Prisma.DutyOmit<ExtArgs> | null
}
