/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
 * This file exports the `DutySchedule` model and its related types.
 *
 * 🟢 You can import this file directly.
 */
import type * as runtime from "@prisma/client/runtime/client"
import type * as $Enums from "../enums.js"
import type * as Prisma from "../internal/prismaNamespace.js"

/**
 * Model DutySchedule
 * 
 */
export type DutyScheduleModel = runtime.Types.Result.DefaultSelection<Prisma.$DutySchedulePayload>

export type AggregateDutySchedule = {
  _count: DutyScheduleCountAggregateOutputType | null
  _min: DutyScheduleMinAggregateOutputType | null
  _max: DutyScheduleMaxAggregateOutputType | null
}

export type DutyScheduleMinAggregateOutputType = {
  id: string | null
}

export type DutyScheduleMaxAggregateOutputType = {
  id: string | null
}

export type DutyScheduleCountAggregateOutputType = {
  id: number
  _all: number
}


export type DutyScheduleMinAggregateInputType = {
  id?: true
}

export type DutyScheduleMaxAggregateInputType = {
  id?: true
}

export type DutyScheduleCountAggregateInputType = {
  id?: true
  _all?: true
}

export type DutyScheduleAggregateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which DutySchedule to aggregate.
   */
  where?: Prisma.DutyScheduleWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of DutySchedules to fetch.
   */
  orderBy?: Prisma.DutyScheduleOrderByWithRelationInput | Prisma.DutyScheduleOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the start position
   */
  cursor?: Prisma.DutyScheduleWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` DutySchedules from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` DutySchedules.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Count returned DutySchedules
  **/
  _count?: true | DutyScheduleCountAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the minimum value
  **/
  _min?: DutyScheduleMinAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the maximum value
  **/
  _max?: DutyScheduleMaxAggregateInputType
}

export type GetDutyScheduleAggregateType<T extends DutyScheduleAggregateArgs> = {
      [P in keyof T & keyof AggregateDutySchedule]: P extends '_count' | 'count'
    ? T[P] extends true
      ? number
      : Prisma.GetScalarType<T[P], AggregateDutySchedule[P]>
    : Prisma.GetScalarType<T[P], AggregateDutySchedule[P]>
}




export type DutyScheduleGroupByArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.DutyScheduleWhereInput
  orderBy?: Prisma.DutyScheduleOrderByWithAggregationInput | Prisma.DutyScheduleOrderByWithAggregationInput[]
  by: Prisma.DutyScheduleScalarFieldEnum[] | Prisma.DutyScheduleScalarFieldEnum
  having?: Prisma.DutyScheduleScalarWhereWithAggregatesInput
  take?: number
  skip?: number
  _count?: DutyScheduleCountAggregateInputType | true
  _min?: DutyScheduleMinAggregateInputType
  _max?: DutyScheduleMaxAggregateInputType
}

export type DutyScheduleGroupByOutputType = {
  id: string
  _count: DutyScheduleCountAggregateOutputType | null
  _min: DutyScheduleMinAggregateOutputType | null
  _max: DutyScheduleMaxAggregateOutputType | null
}

type GetDutyScheduleGroupByPayload<T extends DutyScheduleGroupByArgs> = Prisma.PrismaPromise<
  Array<
    Prisma.PickEnumerable<DutyScheduleGroupByOutputType, T['by']> &
      {
        [P in ((keyof T) & (keyof DutyScheduleGroupByOutputType))]: P extends '_count'
          ? T[P] extends boolean
            ? number
            : Prisma.GetScalarType<T[P], DutyScheduleGroupByOutputType[P]>
          : Prisma.GetScalarType<T[P], DutyScheduleGroupByOutputType[P]>
      }
    >
  >



export type DutyScheduleWhereInput = {
  AND?: Prisma.DutyScheduleWhereInput | Prisma.DutyScheduleWhereInput[]
  OR?: Prisma.DutyScheduleWhereInput[]
  NOT?: Prisma.DutyScheduleWhereInput | Prisma.DutyScheduleWhereInput[]
  id?: Prisma.StringFilter<"DutySchedule"> | string
}

export type DutyScheduleOrderByWithRelationInput = {
  id?: Prisma.SortOrder
}

export type DutyScheduleWhereUniqueInput = Prisma.AtLeast<{
  id?: string
  AND?: Prisma.DutyScheduleWhereInput | Prisma.DutyScheduleWhereInput[]
  OR?: Prisma.DutyScheduleWhereInput[]
  NOT?: Prisma.DutyScheduleWhereInput | Prisma.DutyScheduleWhereInput[]
}, "id">

export type DutyScheduleOrderByWithAggregationInput = {
  id?: Prisma.SortOrder
  _count?: Prisma.DutyScheduleCountOrderByAggregateInput
  _max?: Prisma.DutyScheduleMaxOrderByAggregateInput
  _min?: Prisma.DutyScheduleMinOrderByAggregateInput
}

export type DutyScheduleScalarWhereWithAggregatesInput = {
  AND?: Prisma.DutyScheduleScalarWhereWithAggregatesInput | Prisma.DutyScheduleScalarWhereWithAggregatesInput[]
  OR?: Prisma.DutyScheduleScalarWhereWithAggregatesInput[]
  NOT?: Prisma.DutyScheduleScalarWhereWithAggregatesInput | Prisma.DutyScheduleScalarWhereWithAggregatesInput[]
  id?: Prisma.StringWithAggregatesFilter<"DutySchedule"> | string
}

export type DutyScheduleCreateInput = {
  id?: string
}

export type DutyScheduleUncheckedCreateInput = {
  id?: string
}

export type DutyScheduleUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
}

export type DutyScheduleUncheckedUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
}

export type DutyScheduleCreateManyInput = {
  id?: string
}

export type DutyScheduleUpdateManyMutationInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
}

export type DutyScheduleUncheckedUpdateManyInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
}

export type DutyScheduleCountOrderByAggregateInput = {
  id?: Prisma.SortOrder
}

export type DutyScheduleMaxOrderByAggregateInput = {
  id?: Prisma.SortOrder
}

export type DutyScheduleMinOrderByAggregateInput = {
  id?: Prisma.SortOrder
}



export type DutyScheduleSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
}, ExtArgs["result"]["dutySchedule"]>

export type DutyScheduleSelectCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
}, ExtArgs["result"]["dutySchedule"]>

export type DutyScheduleSelectUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
}, ExtArgs["result"]["dutySchedule"]>

export type DutyScheduleSelectScalar = {
  id?: boolean
}

export type DutyScheduleOmit<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetOmit<"id", ExtArgs["result"]["dutySchedule"]>

export type $DutySchedulePayload<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  name: "DutySchedule"
  objects: {}
  scalars: runtime.Types.Extensions.GetPayloadResult<{
    id: string
  }, ExtArgs["result"]["dutySchedule"]>
  composites: {}
}

export type DutyScheduleGetPayload<S extends boolean | null | undefined | DutyScheduleDefaultArgs> = runtime.Types.Result.GetResult<Prisma.$DutySchedulePayload, S>

export type DutyScheduleCountArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> =
  Omit<DutyScheduleFindManyArgs, 'select' | 'include' | 'distinct' | 'omit'> & {
    select?: DutyScheduleCountAggregateInputType | true
  }

export interface DutyScheduleDelegate<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> {
  [K: symbol]: { types: Prisma.TypeMap<ExtArgs>['model']['DutySchedule'], meta: { name: 'DutySchedule' } }
  /**
   * Find zero or one DutySchedule that matches the filter.
   * @param {DutyScheduleFindUniqueArgs} args - Arguments to find a DutySchedule
   * @example
   * // Get one DutySchedule
   * const dutySchedule = await prisma.dutySchedule.findUnique({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUnique<T extends DutyScheduleFindUniqueArgs>(args: Prisma.SelectSubset<T, DutyScheduleFindUniqueArgs<ExtArgs>>): Prisma.Prisma__DutyScheduleClient<runtime.Types.Result.GetResult<Prisma.$DutySchedulePayload<ExtArgs>, T, "findUnique", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find one DutySchedule that matches the filter or throw an error with `error.code='P2025'`
   * if no matches were found.
   * @param {DutyScheduleFindUniqueOrThrowArgs} args - Arguments to find a DutySchedule
   * @example
   * // Get one DutySchedule
   * const dutySchedule = await prisma.dutySchedule.findUniqueOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUniqueOrThrow<T extends DutyScheduleFindUniqueOrThrowArgs>(args: Prisma.SelectSubset<T, DutyScheduleFindUniqueOrThrowArgs<ExtArgs>>): Prisma.Prisma__DutyScheduleClient<runtime.Types.Result.GetResult<Prisma.$DutySchedulePayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first DutySchedule that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {DutyScheduleFindFirstArgs} args - Arguments to find a DutySchedule
   * @example
   * // Get one DutySchedule
   * const dutySchedule = await prisma.dutySchedule.findFirst({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirst<T extends DutyScheduleFindFirstArgs>(args?: Prisma.SelectSubset<T, DutyScheduleFindFirstArgs<ExtArgs>>): Prisma.Prisma__DutyScheduleClient<runtime.Types.Result.GetResult<Prisma.$DutySchedulePayload<ExtArgs>, T, "findFirst", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first DutySchedule that matches the filter or
   * throw `PrismaKnownClientError` with `P2025` code if no matches were found.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {DutyScheduleFindFirstOrThrowArgs} args - Arguments to find a DutySchedule
   * @example
   * // Get one DutySchedule
   * const dutySchedule = await prisma.dutySchedule.findFirstOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirstOrThrow<T extends DutyScheduleFindFirstOrThrowArgs>(args?: Prisma.SelectSubset<T, DutyScheduleFindFirstOrThrowArgs<ExtArgs>>): Prisma.Prisma__DutyScheduleClient<runtime.Types.Result.GetResult<Prisma.$DutySchedulePayload<ExtArgs>, T, "findFirstOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find zero or more DutySchedules that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {DutyScheduleFindManyArgs} args - Arguments to filter and select certain fields only.
   * @example
   * // Get all DutySchedules
   * const dutySchedules = await prisma.dutySchedule.findMany()
   * 
   * // Get first 10 DutySchedules
   * const dutySchedules = await prisma.dutySchedule.findMany({ take: 10 })
   * 
   * // Only select the `id`
   * const dutyScheduleWithIdOnly = await prisma.dutySchedule.findMany({ select: { id: true } })
   * 
   */
  findMany<T extends DutyScheduleFindManyArgs>(args?: Prisma.SelectSubset<T, DutyScheduleFindManyArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$DutySchedulePayload<ExtArgs>, T, "findMany", GlobalOmitOptions>>

  /**
   * Create a DutySchedule.
   * @param {DutyScheduleCreateArgs} args - Arguments to create a DutySchedule.
   * @example
   * // Create one DutySchedule
   * const DutySchedule = await prisma.dutySchedule.create({
   *   data: {
   *     // ... data to create a DutySchedule
   *   }
   * })
   * 
   */
  create<T extends DutyScheduleCreateArgs>(args: Prisma.SelectSubset<T, DutyScheduleCreateArgs<ExtArgs>>): Prisma.Prisma__DutyScheduleClient<runtime.Types.Result.GetResult<Prisma.$DutySchedulePayload<ExtArgs>, T, "create", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Create many DutySchedules.
   * @param {DutyScheduleCreateManyArgs} args - Arguments to create many DutySchedules.
   * @example
   * // Create many DutySchedules
   * const dutySchedule = await prisma.dutySchedule.createMany({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   *     
   */
  createMany<T extends DutyScheduleCreateManyArgs>(args?: Prisma.SelectSubset<T, DutyScheduleCreateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Create many DutySchedules and returns the data saved in the database.
   * @param {DutyScheduleCreateManyAndReturnArgs} args - Arguments to create many DutySchedules.
   * @example
   * // Create many DutySchedules
   * const dutySchedule = await prisma.dutySchedule.createManyAndReturn({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Create many DutySchedules and only return the `id`
   * const dutyScheduleWithIdOnly = await prisma.dutySchedule.createManyAndReturn({
   *   select: { id: true },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  createManyAndReturn<T extends DutyScheduleCreateManyAndReturnArgs>(args?: Prisma.SelectSubset<T, DutyScheduleCreateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$DutySchedulePayload<ExtArgs>, T, "createManyAndReturn", GlobalOmitOptions>>

  /**
   * Delete a DutySchedule.
   * @param {DutyScheduleDeleteArgs} args - Arguments to delete one DutySchedule.
   * @example
   * // Delete one DutySchedule
   * const DutySchedule = await prisma.dutySchedule.delete({
   *   where: {
   *     // ... filter to delete one DutySchedule
   *   }
   * })
   * 
   */
  delete<T extends DutyScheduleDeleteArgs>(args: Prisma.SelectSubset<T, DutyScheduleDeleteArgs<ExtArgs>>): Prisma.Prisma__DutyScheduleClient<runtime.Types.Result.GetResult<Prisma.$DutySchedulePayload<ExtArgs>, T, "delete", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Update one DutySchedule.
   * @param {DutyScheduleUpdateArgs} args - Arguments to update one DutySchedule.
   * @example
   * // Update one DutySchedule
   * const dutySchedule = await prisma.dutySchedule.update({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  update<T extends DutyScheduleUpdateArgs>(args: Prisma.SelectSubset<T, DutyScheduleUpdateArgs<ExtArgs>>): Prisma.Prisma__DutyScheduleClient<runtime.Types.Result.GetResult<Prisma.$DutySchedulePayload<ExtArgs>, T, "update", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Delete zero or more DutySchedules.
   * @param {DutyScheduleDeleteManyArgs} args - Arguments to filter DutySchedules to delete.
   * @example
   * // Delete a few DutySchedules
   * const { count } = await prisma.dutySchedule.deleteMany({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   * 
   */
  deleteMany<T extends DutyScheduleDeleteManyArgs>(args?: Prisma.SelectSubset<T, DutyScheduleDeleteManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more DutySchedules.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {DutyScheduleUpdateManyArgs} args - Arguments to update one or more rows.
   * @example
   * // Update many DutySchedules
   * const dutySchedule = await prisma.dutySchedule.updateMany({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  updateMany<T extends DutyScheduleUpdateManyArgs>(args: Prisma.SelectSubset<T, DutyScheduleUpdateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more DutySchedules and returns the data updated in the database.
   * @param {DutyScheduleUpdateManyAndReturnArgs} args - Arguments to update many DutySchedules.
   * @example
   * // Update many DutySchedules
   * const dutySchedule = await prisma.dutySchedule.updateManyAndReturn({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Update zero or more DutySchedules and only return the `id`
   * const dutyScheduleWithIdOnly = await prisma.dutySchedule.updateManyAndReturn({
   *   select: { id: true },
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  updateManyAndReturn<T extends DutyScheduleUpdateManyAndReturnArgs>(args: Prisma.SelectSubset<T, DutyScheduleUpdateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$DutySchedulePayload<ExtArgs>, T, "updateManyAndReturn", GlobalOmitOptions>>

  /**
   * Create or update one DutySchedule.
   * @param {DutyScheduleUpsertArgs} args - Arguments to update or create a DutySchedule.
   * @example
   * // Update or create a DutySchedule
   * const dutySchedule = await prisma.dutySchedule.upsert({
   *   create: {
   *     // ... data to create a DutySchedule
   *   },
   *   update: {
   *     // ... in case it already exists, update
   *   },
   *   where: {
   *     // ... the filter for the DutySchedule we want to update
   *   }
   * })
   */
  upsert<T extends DutyScheduleUpsertArgs>(args: Prisma.SelectSubset<T, DutyScheduleUpsertArgs<ExtArgs>>): Prisma.Prisma__DutyScheduleClient<runtime.Types.Result.GetResult<Prisma.$DutySchedulePayload<ExtArgs>, T, "upsert", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>


  /**
   * Count the number of DutySchedules.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {DutyScheduleCountArgs} args - Arguments to filter DutySchedules to count.
   * @example
   * // Count the number of DutySchedules
   * const count = await prisma.dutySchedule.count({
   *   where: {
   *     // ... the filter for the DutySchedules we want to count
   *   }
   * })
  **/
  count<T extends DutyScheduleCountArgs>(
    args?: Prisma.Subset<T, DutyScheduleCountArgs>,
  ): Prisma.PrismaPromise<
    T extends runtime.Types.Utils.Record<'select', any>
      ? T['select'] extends true
        ? number
        : Prisma.GetScalarType<T['select'], DutyScheduleCountAggregateOutputType>
      : number
  >

  /**
   * Allows you to perform aggregations operations on a DutySchedule.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {DutyScheduleAggregateArgs} args - Select which aggregations you would like to apply and on what fields.
   * @example
   * // Ordered by age ascending
   * // Where email contains prisma.io
   * // Limited to the 10 users
   * const aggregations = await prisma.user.aggregate({
   *   _avg: {
   *     age: true,
   *   },
   *   where: {
   *     email: {
   *       contains: "prisma.io",
   *     },
   *   },
   *   orderBy: {
   *     age: "asc",
   *   },
   *   take: 10,
   * })
  **/
  aggregate<T extends DutyScheduleAggregateArgs>(args: Prisma.Subset<T, DutyScheduleAggregateArgs>): Prisma.PrismaPromise<GetDutyScheduleAggregateType<T>>

  /**
   * Group by DutySchedule.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {DutyScheduleGroupByArgs} args - Group by arguments.
   * @example
   * // Group by city, order by createdAt, get count
   * const result = await prisma.user.groupBy({
   *   by: ['city', 'createdAt'],
   *   orderBy: {
   *     createdAt: true
   *   },
   *   _count: {
   *     _all: true
   *   },
   * })
   * 
  **/
  groupBy<
    T extends DutyScheduleGroupByArgs,
    HasSelectOrTake extends Prisma.Or<
      Prisma.Extends<'skip', Prisma.Keys<T>>,
      Prisma.Extends<'take', Prisma.Keys<T>>
    >,
    OrderByArg extends Prisma.True extends HasSelectOrTake
      ? { orderBy: DutyScheduleGroupByArgs['orderBy'] }
      : { orderBy?: DutyScheduleGroupByArgs['orderBy'] },
    OrderFields extends Prisma.ExcludeUnderscoreKeys<Prisma.Keys<Prisma.MaybeTupleToUnion<T['orderBy']>>>,
    ByFields extends Prisma.MaybeTupleToUnion<T['by']>,
    ByValid extends Prisma.Has<ByFields, OrderFields>,
    HavingFields extends Prisma.GetHavingFields<T['having']>,
    HavingValid extends Prisma.Has<ByFields, HavingFields>,
    ByEmpty extends T['by'] extends never[] ? Prisma.True : Prisma.False,
    InputErrors extends ByEmpty extends Prisma.True
    ? `Error: "by" must not be empty.`
    : HavingValid extends Prisma.False
    ? {
        [P in HavingFields]: P extends ByFields
          ? never
          : P extends string
          ? `Error: Field "${P}" used in "having" needs to be provided in "by".`
          : [
              Error,
              'Field ',
              P,
              ` in "having" needs to be provided in "by"`,
            ]
      }[HavingFields]
    : 'take' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "take", you also need to provide "orderBy"'
    : 'skip' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "skip", you also need to provide "orderBy"'
    : ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
          ? never
          : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
      }[OrderFields]
  >(args: Prisma.SubsetIntersection<T, DutyScheduleGroupByArgs, OrderByArg> & InputErrors): {} extends InputErrors ? GetDutyScheduleGroupByPayload<T> : Prisma.PrismaPromise<InputErrors>
/**
 * Fields of the DutySchedule model
 */
readonly fields: DutyScheduleFieldRefs;
}

/**
 * The delegate class that acts as a "Promise-like" for DutySchedule.
 * Why is this prefixed with `Prisma__`?
 * Because we want to prevent naming conflicts as mentioned in
 * https://github.com/prisma/prisma-client-js/issues/707
 */
export interface Prisma__DutyScheduleClient<T, Null = never, ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> extends Prisma.PrismaPromise<T> {
  readonly [Symbol.toStringTag]: "PrismaPromise"
  /**
   * Attaches callbacks for the resolution and/or rejection of the Promise.
   * @param onfulfilled The callback to execute when the Promise is resolved.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of which ever callback is executed.
   */
  then<TResult1 = T, TResult2 = never>(onfulfilled?: ((value: T) => TResult1 | PromiseLike<TResult1>) | undefined | null, onrejected?: ((reason: any) => TResult2 | PromiseLike<TResult2>) | undefined | null): runtime.Types.Utils.JsPromise<TResult1 | TResult2>
  /**
   * Attaches a callback for only the rejection of the Promise.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of the callback.
   */
  catch<TResult = never>(onrejected?: ((reason: any) => TResult | PromiseLike<TResult>) | undefined | null): runtime.Types.Utils.JsPromise<T | TResult>
  /**
   * Attaches a callback that is invoked when the Promise is settled (fulfilled or rejected). The
   * resolved value cannot be modified from the callback.
   * @param onfinally The callback to execute when the Promise is settled (fulfilled or rejected).
   * @returns A Promise for the completion of the callback.
   */
  finally(onfinally?: (() => void) | undefined | null): runtime.Types.Utils.JsPromise<T>
}




/**
 * Fields of the DutySchedule model
 */
export interface DutyScheduleFieldRefs {
  readonly id: Prisma.FieldRef<"DutySchedule", 'String'>
}
    

// Custom InputTypes
/**
 * DutySchedule findUnique
 */
export type DutyScheduleFindUniqueArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the DutySchedule
   */
  select?: Prisma.DutyScheduleSelect<ExtArgs> | null
  /**
   * Omit specific fields from the DutySchedule
   */
  omit?: Prisma.DutyScheduleOmit<ExtArgs> | null
  /**
   * Filter, which DutySchedule to fetch.
   */
  where: Prisma.DutyScheduleWhereUniqueInput
}

/**
 * DutySchedule findUniqueOrThrow
 */
export type DutyScheduleFindUniqueOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the DutySchedule
   */
  select?: Prisma.DutyScheduleSelect<ExtArgs> | null
  /**
   * Omit specific fields from the DutySchedule
   */
  omit?: Prisma.DutyScheduleOmit<ExtArgs> | null
  /**
   * Filter, which DutySchedule to fetch.
   */
  where: Prisma.DutyScheduleWhereUniqueInput
}

/**
 * DutySchedule findFirst
 */
export type DutyScheduleFindFirstArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the DutySchedule
   */
  select?: Prisma.DutyScheduleSelect<ExtArgs> | null
  /**
   * Omit specific fields from the DutySchedule
   */
  omit?: Prisma.DutyScheduleOmit<ExtArgs> | null
  /**
   * Filter, which DutySchedule to fetch.
   */
  where?: Prisma.DutyScheduleWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of DutySchedules to fetch.
   */
  orderBy?: Prisma.DutyScheduleOrderByWithRelationInput | Prisma.DutyScheduleOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for DutySchedules.
   */
  cursor?: Prisma.DutyScheduleWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` DutySchedules from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` DutySchedules.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of DutySchedules.
   */
  distinct?: Prisma.DutyScheduleScalarFieldEnum | Prisma.DutyScheduleScalarFieldEnum[]
}

/**
 * DutySchedule findFirstOrThrow
 */
export type DutyScheduleFindFirstOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the DutySchedule
   */
  select?: Prisma.DutyScheduleSelect<ExtArgs> | null
  /**
   * Omit specific fields from the DutySchedule
   */
  omit?: Prisma.DutyScheduleOmit<ExtArgs> | null
  /**
   * Filter, which DutySchedule to fetch.
   */
  where?: Prisma.DutyScheduleWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of DutySchedules to fetch.
   */
  orderBy?: Prisma.DutyScheduleOrderByWithRelationInput | Prisma.DutyScheduleOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for DutySchedules.
   */
  cursor?: Prisma.DutyScheduleWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` DutySchedules from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` DutySchedules.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of DutySchedules.
   */
  distinct?: Prisma.DutyScheduleScalarFieldEnum | Prisma.DutyScheduleScalarFieldEnum[]
}

/**
 * DutySchedule findMany
 */
export type DutyScheduleFindManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the DutySchedule
   */
  select?: Prisma.DutyScheduleSelect<ExtArgs> | null
  /**
   * Omit specific fields from the DutySchedule
   */
  omit?: Prisma.DutyScheduleOmit<ExtArgs> | null
  /**
   * Filter, which DutySchedules to fetch.
   */
  where?: Prisma.DutyScheduleWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of DutySchedules to fetch.
   */
  orderBy?: Prisma.DutyScheduleOrderByWithRelationInput | Prisma.DutyScheduleOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for listing DutySchedules.
   */
  cursor?: Prisma.DutyScheduleWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` DutySchedules from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` DutySchedules.
   */
  skip?: number
  distinct?: Prisma.DutyScheduleScalarFieldEnum | Prisma.DutyScheduleScalarFieldEnum[]
}

/**
 * DutySchedule create
 */
export type DutyScheduleCreateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the DutySchedule
   */
  select?: Prisma.DutyScheduleSelect<ExtArgs> | null
  /**
   * Omit specific fields from the DutySchedule
   */
  omit?: Prisma.DutyScheduleOmit<ExtArgs> | null
  /**
   * The data needed to create a DutySchedule.
   */
  data?: Prisma.XOR<Prisma.DutyScheduleCreateInput, Prisma.DutyScheduleUncheckedCreateInput>
}

/**
 * DutySchedule createMany
 */
export type DutyScheduleCreateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to create many DutySchedules.
   */
  data: Prisma.DutyScheduleCreateManyInput | Prisma.DutyScheduleCreateManyInput[]
}

/**
 * DutySchedule createManyAndReturn
 */
export type DutyScheduleCreateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the DutySchedule
   */
  select?: Prisma.DutyScheduleSelectCreateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the DutySchedule
   */
  omit?: Prisma.DutyScheduleOmit<ExtArgs> | null
  /**
   * The data used to create many DutySchedules.
   */
  data: Prisma.DutyScheduleCreateManyInput | Prisma.DutyScheduleCreateManyInput[]
}

/**
 * DutySchedule update
 */
export type DutyScheduleUpdateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the DutySchedule
   */
  select?: Prisma.DutyScheduleSelect<ExtArgs> | null
  /**
   * Omit specific fields from the DutySchedule
   */
  omit?: Prisma.DutyScheduleOmit<ExtArgs> | null
  /**
   * The data needed to update a DutySchedule.
   */
  data: Prisma.XOR<Prisma.DutyScheduleUpdateInput, Prisma.DutyScheduleUncheckedUpdateInput>
  /**
   * Choose, which DutySchedule to update.
   */
  where: Prisma.DutyScheduleWhereUniqueInput
}

/**
 * DutySchedule updateMany
 */
export type DutyScheduleUpdateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to update DutySchedules.
   */
  data: Prisma.XOR<Prisma.DutyScheduleUpdateManyMutationInput, Prisma.DutyScheduleUncheckedUpdateManyInput>
  /**
   * Filter which DutySchedules to update
   */
  where?: Prisma.DutyScheduleWhereInput
  /**
   * Limit how many DutySchedules to update.
   */
  limit?: number
}

/**
 * DutySchedule updateManyAndReturn
 */
export type DutyScheduleUpdateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the DutySchedule
   */
  select?: Prisma.DutyScheduleSelectUpdateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the DutySchedule
   */
  omit?: Prisma.DutyScheduleOmit<ExtArgs> | null
  /**
   * The data used to update DutySchedules.
   */
  data: Prisma.XOR<Prisma.DutyScheduleUpdateManyMutationInput, Prisma.DutyScheduleUncheckedUpdateManyInput>
  /**
   * Filter which DutySchedules to update
   */
  where?: Prisma.DutyScheduleWhereInput
  /**
   * Limit how many DutySchedules to update.
   */
  limit?: number
}

/**
 * DutySchedule upsert
 */
export type DutyScheduleUpsertArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the DutySchedule
   */
  select?: Prisma.DutyScheduleSelect<ExtArgs> | null
  /**
   * Omit specific fields from the DutySchedule
   */
  omit?: Prisma.DutyScheduleOmit<ExtArgs> | null
  /**
   * The filter to search for the DutySchedule to update in case it exists.
   */
  where: Prisma.DutyScheduleWhereUniqueInput
  /**
   * In case the DutySchedule found by the `where` argument doesn't exist, create a new DutySchedule with this data.
   */
  create: Prisma.XOR<Prisma.DutyScheduleCreateInput, Prisma.DutyScheduleUncheckedCreateInput>
  /**
   * In case the DutySchedule was found with the provided `where` argument, update it with this data.
   */
  update: Prisma.XOR<Prisma.DutyScheduleUpdateInput, Prisma.DutyScheduleUncheckedUpdateInput>
}

/**
 * DutySchedule delete
 */
export type DutyScheduleDeleteArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the DutySchedule
   */
  select?: Prisma.DutyScheduleSelect<ExtArgs> | null
  /**
   * Omit specific fields from the DutySchedule
   */
  omit?: Prisma.DutyScheduleOmit<ExtArgs> | null
  /**
   * Filter which DutySchedule to delete.
   */
  where: Prisma.DutyScheduleWhereUniqueInput
}

/**
 * DutySchedule deleteMany
 */
export type DutyScheduleDeleteManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which DutySchedules to delete
   */
  where?: Prisma.DutyScheduleWhereInput
  /**
   * Limit how many DutySchedules to delete.
   */
  limit?: number
}

/**
 * DutySchedule without action
 */
export type DutyScheduleDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the DutySchedule
   */
  select?: Prisma.DutyScheduleSelect<ExtArgs> | null
  /**
   * Omit specific fields from the DutySchedule
   */
  omit?: Prisma.DutyScheduleOmit<ExtArgs> | null
}
