
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
 * This file exports the `FundContributionLog` model and its related types.
 *
 * 🟢 You can import this file directly.
 */
import type * as runtime from "@prisma/client/runtime/client"
import type * as $Enums from "../enums.js"
import type * as Prisma from "../internal/prismaNamespace.js"

/**
 * Model FundContributionLog
 * 
 */
export type FundContributionLogModel = runtime.Types.Result.DefaultSelection<Prisma.$FundContributionLogPayload>

export type AggregateFundContributionLog = {
  _count: FundContributionLogCountAggregateOutputType | null
  _avg: FundContributionLogAvgAggregateOutputType | null
  _sum: FundContributionLogSumAggregateOutputType | null
  _min: FundContributionLogMinAggregateOutputType | null
  _max: FundContributionLogMaxAggregateOutputType | null
}

export type FundContributionLogAvgAggregateOutputType = {
  fundId: number | null
  amount: number | null
}

export type FundContributionLogSumAggregateOutputType = {
  fundId: number | null
  amount: number | null
}

export type FundContributionLogMinAggregateOutputType = {
  id: string | null
  reporterId: string | null
  contributorId: string | null
  fundId: number | null
  currency: string | null
  amount: number | null
  note: string | null
  type: $Enums.FundTransactionType | null
  createdAt: Date | null
}

export type FundContributionLogMaxAggregateOutputType = {
  id: string | null
  reporterId: string | null
  contributorId: string | null
  fundId: number | null
  currency: string | null
  amount: number | null
  note: string | null
  type: $Enums.FundTransactionType | null
  createdAt: Date | null
}

export type FundContributionLogCountAggregateOutputType = {
  id: number
  reporterId: number
  contributorId: number
  fundId: number
  currency: number
  amount: number
  note: number
  type: number
  createdAt: number
  _all: number
}


export type FundContributionLogAvgAggregateInputType = {
  fundId?: true
  amount?: true
}

export type FundContributionLogSumAggregateInputType = {
  fundId?: true
  amount?: true
}

export type FundContributionLogMinAggregateInputType = {
  id?: true
  reporterId?: true
  contributorId?: true
  fundId?: true
  currency?: true
  amount?: true
  note?: true
  type?: true
  createdAt?: true
}

export type FundContributionLogMaxAggregateInputType = {
  id?: true
  reporterId?: true
  contributorId?: true
  fundId?: true
  currency?: true
  amount?: true
  note?: true
  type?: true
  createdAt?: true
}

export type FundContributionLogCountAggregateInputType = {
  id?: true
  reporterId?: true
  contributorId?: true
  fundId?: true
  currency?: true
  amount?: true
  note?: true
  type?: true
  createdAt?: true
  _all?: true
}

export type FundContributionLogAggregateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which FundContributionLog to aggregate.
   */
  where?: Prisma.FundContributionLogWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of FundContributionLogs to fetch.
   */
  orderBy?: Prisma.FundContributionLogOrderByWithRelationInput | Prisma.FundContributionLogOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the start position
   */
  cursor?: Prisma.FundContributionLogWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` FundContributionLogs from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` FundContributionLogs.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Count returned FundContributionLogs
  **/
  _count?: true | FundContributionLogCountAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to average
  **/
  _avg?: FundContributionLogAvgAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to sum
  **/
  _sum?: FundContributionLogSumAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the minimum value
  **/
  _min?: FundContributionLogMinAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the maximum value
  **/
  _max?: FundContributionLogMaxAggregateInputType
}

export type GetFundContributionLogAggregateType<T extends FundContributionLogAggregateArgs> = {
      [P in keyof T & keyof AggregateFundContributionLog]: P extends '_count' | 'count'
    ? T[P] extends true
      ? number
      : Prisma.GetScalarType<T[P], AggregateFundContributionLog[P]>
    : Prisma.GetScalarType<T[P], AggregateFundContributionLog[P]>
}




export type FundContributionLogGroupByArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.FundContributionLogWhereInput
  orderBy?: Prisma.FundContributionLogOrderByWithAggregationInput | Prisma.FundContributionLogOrderByWithAggregationInput[]
  by: Prisma.FundContributionLogScalarFieldEnum[] | Prisma.FundContributionLogScalarFieldEnum
  having?: Prisma.FundContributionLogScalarWhereWithAggregatesInput
  take?: number
  skip?: number
  _count?: FundContributionLogCountAggregateInputType | true
  _avg?: FundContributionLogAvgAggregateInputType
  _sum?: FundContributionLogSumAggregateInputType
  _min?: FundContributionLogMinAggregateInputType
  _max?: FundContributionLogMaxAggregateInputType
}

export type FundContributionLogGroupByOutputType = {
  id: string
  reporterId: string
  contributorId: string
  fundId: number
  currency: string
  amount: number
  note: string | null
  type: $Enums.FundTransactionType
  createdAt: Date
  _count: FundContributionLogCountAggregateOutputType | null
  _avg: FundContributionLogAvgAggregateOutputType | null
  _sum: FundContributionLogSumAggregateOutputType | null
  _min: FundContributionLogMinAggregateOutputType | null
  _max: FundContributionLogMaxAggregateOutputType | null
}

type GetFundContributionLogGroupByPayload<T extends FundContributionLogGroupByArgs> = Prisma.PrismaPromise<
  Array<
    Prisma.PickEnumerable<FundContributionLogGroupByOutputType, T['by']> &
      {
        [P in ((keyof T) & (keyof FundContributionLogGroupByOutputType))]: P extends '_count'
          ? T[P] extends boolean
            ? number
            : Prisma.GetScalarType<T[P], FundContributionLogGroupByOutputType[P]>
          : Prisma.GetScalarType<T[P], FundContributionLogGroupByOutputType[P]>
      }
    >
  >



export type FundContributionLogWhereInput = {
  AND?: Prisma.FundContributionLogWhereInput | Prisma.FundContributionLogWhereInput[]
  OR?: Prisma.FundContributionLogWhereInput[]
  NOT?: Prisma.FundContributionLogWhereInput | Prisma.FundContributionLogWhereInput[]
  id?: Prisma.StringFilter<"FundContributionLog"> | string
  reporterId?: Prisma.StringFilter<"FundContributionLog"> | string
  contributorId?: Prisma.StringFilter<"FundContributionLog"> | string
  fundId?: Prisma.IntFilter<"FundContributionLog"> | number
  currency?: Prisma.StringFilter<"FundContributionLog"> | string
  amount?: Prisma.FloatFilter<"FundContributionLog"> | number
  note?: Prisma.StringNullableFilter<"FundContributionLog"> | string | null
  type?: Prisma.EnumFundTransactionTypeFilter<"FundContributionLog"> | $Enums.FundTransactionType
  createdAt?: Prisma.DateTimeFilter<"FundContributionLog"> | Date | string
  fund?: Prisma.XOR<Prisma.FundScalarRelationFilter, Prisma.FundWhereInput>
  reporter?: Prisma.XOR<Prisma.UserScalarRelationFilter, Prisma.UserWhereInput>
  contributor?: Prisma.XOR<Prisma.UserScalarRelationFilter, Prisma.UserWhereInput>
}

export type FundContributionLogOrderByWithRelationInput = {
  id?: Prisma.SortOrder
  reporterId?: Prisma.SortOrder
  contributorId?: Prisma.SortOrder
  fundId?: Prisma.SortOrder
  currency?: Prisma.SortOrder
  amount?: Prisma.SortOrder
  note?: Prisma.SortOrderInput | Prisma.SortOrder
  type?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  fund?: Prisma.FundOrderByWithRelationInput
  reporter?: Prisma.UserOrderByWithRelationInput
  contributor?: Prisma.UserOrderByWithRelationInput
}

export type FundContributionLogWhereUniqueInput = Prisma.AtLeast<{
  id?: string
  AND?: Prisma.FundContributionLogWhereInput | Prisma.FundContributionLogWhereInput[]
  OR?: Prisma.FundContributionLogWhereInput[]
  NOT?: Prisma.FundContributionLogWhereInput | Prisma.FundContributionLogWhereInput[]
  reporterId?: Prisma.StringFilter<"FundContributionLog"> | string
  contributorId?: Prisma.StringFilter<"FundContributionLog"> | string
  fundId?: Prisma.IntFilter<"FundContributionLog"> | number
  currency?: Prisma.StringFilter<"FundContributionLog"> | string
  amount?: Prisma.FloatFilter<"FundContributionLog"> | number
  note?: Prisma.StringNullableFilter<"FundContributionLog"> | string | null
  type?: Prisma.EnumFundTransactionTypeFilter<"FundContributionLog"> | $Enums.FundTransactionType
  createdAt?: Prisma.DateTimeFilter<"FundContributionLog"> | Date | string
  fund?: Prisma.XOR<Prisma.FundScalarRelationFilter, Prisma.FundWhereInput>
  reporter?: Prisma.XOR<Prisma.UserScalarRelationFilter, Prisma.UserWhereInput>
  contributor?: Prisma.XOR<Prisma.UserScalarRelationFilter, Prisma.UserWhereInput>
}, "id">

export type FundContributionLogOrderByWithAggregationInput = {
  id?: Prisma.SortOrder
  reporterId?: Prisma.SortOrder
  contributorId?: Prisma.SortOrder
  fundId?: Prisma.SortOrder
  currency?: Prisma.SortOrder
  amount?: Prisma.SortOrder
  note?: Prisma.SortOrderInput | Prisma.SortOrder
  type?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  _count?: Prisma.FundContributionLogCountOrderByAggregateInput
  _avg?: Prisma.FundContributionLogAvgOrderByAggregateInput
  _max?: Prisma.FundContributionLogMaxOrderByAggregateInput
  _min?: Prisma.FundContributionLogMinOrderByAggregateInput
  _sum?: Prisma.FundContributionLogSumOrderByAggregateInput
}

export type FundContributionLogScalarWhereWithAggregatesInput = {
  AND?: Prisma.FundContributionLogScalarWhereWithAggregatesInput | Prisma.FundContributionLogScalarWhereWithAggregatesInput[]
  OR?: Prisma.FundContributionLogScalarWhereWithAggregatesInput[]
  NOT?: Prisma.FundContributionLogScalarWhereWithAggregatesInput | Prisma.FundContributionLogScalarWhereWithAggregatesInput[]
  id?: Prisma.StringWithAggregatesFilter<"FundContributionLog"> | string
  reporterId?: Prisma.StringWithAggregatesFilter<"FundContributionLog"> | string
  contributorId?: Prisma.StringWithAggregatesFilter<"FundContributionLog"> | string
  fundId?: Prisma.IntWithAggregatesFilter<"FundContributionLog"> | number
  currency?: Prisma.StringWithAggregatesFilter<"FundContributionLog"> | string
  amount?: Prisma.FloatWithAggregatesFilter<"FundContributionLog"> | number
  note?: Prisma.StringNullableWithAggregatesFilter<"FundContributionLog"> | string | null
  type?: Prisma.EnumFundTransactionTypeWithAggregatesFilter<"FundContributionLog"> | $Enums.FundTransactionType
  createdAt?: Prisma.DateTimeWithAggregatesFilter<"FundContributionLog"> | Date | string
}

export type FundContributionLogCreateInput = {
  id?: string
  currency?: string
  amount: number
  note?: string | null
  type?: $Enums.FundTransactionType
  createdAt?: Date | string
  fund?: Prisma.FundCreateNestedOneWithoutContributionLogsInput
  reporter: Prisma.UserCreateNestedOneWithoutReportedLogsInput
  contributor: Prisma.UserCreateNestedOneWithoutContributedLogsInput
}

export type FundContributionLogUncheckedCreateInput = {
  id?: string
  reporterId: string
  contributorId: string
  fundId?: number
  currency?: string
  amount: number
  note?: string | null
  type?: $Enums.FundTransactionType
  createdAt?: Date | string
}

export type FundContributionLogUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  currency?: Prisma.StringFieldUpdateOperationsInput | string
  amount?: Prisma.FloatFieldUpdateOperationsInput | number
  note?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  type?: Prisma.EnumFundTransactionTypeFieldUpdateOperationsInput | $Enums.FundTransactionType
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  fund?: Prisma.FundUpdateOneRequiredWithoutContributionLogsNestedInput
  reporter?: Prisma.UserUpdateOneRequiredWithoutReportedLogsNestedInput
  contributor?: Prisma.UserUpdateOneRequiredWithoutContributedLogsNestedInput
}

export type FundContributionLogUncheckedUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  reporterId?: Prisma.StringFieldUpdateOperationsInput | string
  contributorId?: Prisma.StringFieldUpdateOperationsInput | string
  fundId?: Prisma.IntFieldUpdateOperationsInput | number
  currency?: Prisma.StringFieldUpdateOperationsInput | string
  amount?: Prisma.FloatFieldUpdateOperationsInput | number
  note?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  type?: Prisma.EnumFundTransactionTypeFieldUpdateOperationsInput | $Enums.FundTransactionType
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type FundContributionLogCreateManyInput = {
  id?: string
  reporterId: string
  contributorId: string
  fundId?: number
  currency?: string
  amount: number
  note?: string | null
  type?: $Enums.FundTransactionType
  createdAt?: Date | string
}

export type FundContributionLogUpdateManyMutationInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  currency?: Prisma.StringFieldUpdateOperationsInput | string
  amount?: Prisma.FloatFieldUpdateOperationsInput | number
  note?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  type?: Prisma.EnumFundTransactionTypeFieldUpdateOperationsInput | $Enums.FundTransactionType
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type FundContributionLogUncheckedUpdateManyInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  reporterId?: Prisma.StringFieldUpdateOperationsInput | string
  contributorId?: Prisma.StringFieldUpdateOperationsInput | string
  fundId?: Prisma.IntFieldUpdateOperationsInput | number
  currency?: Prisma.StringFieldUpdateOperationsInput | string
  amount?: Prisma.FloatFieldUpdateOperationsInput | number
  note?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  type?: Prisma.EnumFundTransactionTypeFieldUpdateOperationsInput | $Enums.FundTransactionType
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type FundContributionLogListRelationFilter = {
  every?: Prisma.FundContributionLogWhereInput
  some?: Prisma.FundContributionLogWhereInput
  none?: Prisma.FundContributionLogWhereInput
}

export type FundContributionLogOrderByRelationAggregateInput = {
  _count?: Prisma.SortOrder
}

export type FundContributionLogCountOrderByAggregateInput = {
  id?: Prisma.SortOrder
  reporterId?: Prisma.SortOrder
  contributorId?: Prisma.SortOrder
  fundId?: Prisma.SortOrder
  currency?: Prisma.SortOrder
  amount?: Prisma.SortOrder
  note?: Prisma.SortOrder
  type?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
}

export type FundContributionLogAvgOrderByAggregateInput = {
  fundId?: Prisma.SortOrder
  amount?: Prisma.SortOrder
}

export type FundContributionLogMaxOrderByAggregateInput = {
  id?: Prisma.SortOrder
  reporterId?: Prisma.SortOrder
  contributorId?: Prisma.SortOrder
  fundId?: Prisma.SortOrder
  currency?: Prisma.SortOrder
  amount?: Prisma.SortOrder
  note?: Prisma.SortOrder
  type?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
}

export type FundContributionLogMinOrderByAggregateInput = {
  id?: Prisma.SortOrder
  reporterId?: Prisma.SortOrder
  contributorId?: Prisma.SortOrder
  fundId?: Prisma.SortOrder
  currency?: Prisma.SortOrder
  amount?: Prisma.SortOrder
  note?: Prisma.SortOrder
  type?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
}

export type FundContributionLogSumOrderByAggregateInput = {
  fundId?: Prisma.SortOrder
  amount?: Prisma.SortOrder
}

export type FundContributionLogCreateNestedManyWithoutReporterInput = {
  create?: Prisma.XOR<Prisma.FundContributionLogCreateWithoutReporterInput, Prisma.FundContributionLogUncheckedCreateWithoutReporterInput> | Prisma.FundContributionLogCreateWithoutReporterInput[] | Prisma.FundContributionLogUncheckedCreateWithoutReporterInput[]
  connectOrCreate?: Prisma.FundContributionLogCreateOrConnectWithoutReporterInput | Prisma.FundContributionLogCreateOrConnectWithoutReporterInput[]
  createMany?: Prisma.FundContributionLogCreateManyReporterInputEnvelope
  connect?: Prisma.FundContributionLogWhereUniqueInput | Prisma.FundContributionLogWhereUniqueInput[]
}

export type FundContributionLogCreateNestedManyWithoutContributorInput = {
  create?: Prisma.XOR<Prisma.FundContributionLogCreateWithoutContributorInput, Prisma.FundContributionLogUncheckedCreateWithoutContributorInput> | Prisma.FundContributionLogCreateWithoutContributorInput[] | Prisma.FundContributionLogUncheckedCreateWithoutContributorInput[]
  connectOrCreate?: Prisma.FundContributionLogCreateOrConnectWithoutContributorInput | Prisma.FundContributionLogCreateOrConnectWithoutContributorInput[]
  createMany?: Prisma.FundContributionLogCreateManyContributorInputEnvelope
  connect?: Prisma.FundContributionLogWhereUniqueInput | Prisma.FundContributionLogWhereUniqueInput[]
}

export type FundContributionLogUncheckedCreateNestedManyWithoutReporterInput = {
  create?: Prisma.XOR<Prisma.FundContributionLogCreateWithoutReporterInput, Prisma.FundContributionLogUncheckedCreateWithoutReporterInput> | Prisma.FundContributionLogCreateWithoutReporterInput[] | Prisma.FundContributionLogUncheckedCreateWithoutReporterInput[]
  connectOrCreate?: Prisma.FundContributionLogCreateOrConnectWithoutReporterInput | Prisma.FundContributionLogCreateOrConnectWithoutReporterInput[]
  createMany?: Prisma.FundContributionLogCreateManyReporterInputEnvelope
  connect?: Prisma.FundContributionLogWhereUniqueInput | Prisma.FundContributionLogWhereUniqueInput[]
}

export type FundContributionLogUncheckedCreateNestedManyWithoutContributorInput = {
  create?: Prisma.XOR<Prisma.FundContributionLogCreateWithoutContributorInput, Prisma.FundContributionLogUncheckedCreateWithoutContributorInput> | Prisma.FundContributionLogCreateWithoutContributorInput[] | Prisma.FundContributionLogUncheckedCreateWithoutContributorInput[]
  connectOrCreate?: Prisma.FundContributionLogCreateOrConnectWithoutContributorInput | Prisma.FundContributionLogCreateOrConnectWithoutContributorInput[]
  createMany?: Prisma.FundContributionLogCreateManyContributorInputEnvelope
  connect?: Prisma.FundContributionLogWhereUniqueInput | Prisma.FundContributionLogWhereUniqueInput[]
}

export type FundContributionLogUpdateManyWithoutReporterNestedInput = {
  create?: Prisma.XOR<Prisma.FundContributionLogCreateWithoutReporterInput, Prisma.FundContributionLogUncheckedCreateWithoutReporterInput> | Prisma.FundContributionLogCreateWithoutReporterInput[] | Prisma.FundContributionLogUncheckedCreateWithoutReporterInput[]
  connectOrCreate?: Prisma.FundContributionLogCreateOrConnectWithoutReporterInput | Prisma.FundContributionLogCreateOrConnectWithoutReporterInput[]
  upsert?: Prisma.FundContributionLogUpsertWithWhereUniqueWithoutReporterInput | Prisma.FundContributionLogUpsertWithWhereUniqueWithoutReporterInput[]
  createMany?: Prisma.FundContributionLogCreateManyReporterInputEnvelope
  set?: Prisma.FundContributionLogWhereUniqueInput | Prisma.FundContributionLogWhereUniqueInput[]
  disconnect?: Prisma.FundContributionLogWhereUniqueInput | Prisma.FundContributionLogWhereUniqueInput[]
  delete?: Prisma.FundContributionLogWhereUniqueInput | Prisma.FundContributionLogWhereUniqueInput[]
  connect?: Prisma.FundContributionLogWhereUniqueInput | Prisma.FundContributionLogWhereUniqueInput[]
  update?: Prisma.FundContributionLogUpdateWithWhereUniqueWithoutReporterInput | Prisma.FundContributionLogUpdateWithWhereUniqueWithoutReporterInput[]
  updateMany?: Prisma.FundContributionLogUpdateManyWithWhereWithoutReporterInput | Prisma.FundContributionLogUpdateManyWithWhereWithoutReporterInput[]
  deleteMany?: Prisma.FundContributionLogScalarWhereInput | Prisma.FundContributionLogScalarWhereInput[]
}

export type FundContributionLogUpdateManyWithoutContributorNestedInput = {
  create?: Prisma.XOR<Prisma.FundContributionLogCreateWithoutContributorInput, Prisma.FundContributionLogUncheckedCreateWithoutContributorInput> | Prisma.FundContributionLogCreateWithoutContributorInput[] | Prisma.FundContributionLogUncheckedCreateWithoutContributorInput[]
  connectOrCreate?: Prisma.FundContributionLogCreateOrConnectWithoutContributorInput | Prisma.FundContributionLogCreateOrConnectWithoutContributorInput[]
  upsert?: Prisma.FundContributionLogUpsertWithWhereUniqueWithoutContributorInput | Prisma.FundContributionLogUpsertWithWhereUniqueWithoutContributorInput[]
  createMany?: Prisma.FundContributionLogCreateManyContributorInputEnvelope
  set?: Prisma.FundContributionLogWhereUniqueInput | Prisma.FundContributionLogWhereUniqueInput[]
  disconnect?: Prisma.FundContributionLogWhereUniqueInput | Prisma.FundContributionLogWhereUniqueInput[]
  delete?: Prisma.FundContributionLogWhereUniqueInput | Prisma.FundContributionLogWhereUniqueInput[]
  connect?: Prisma.FundContributionLogWhereUniqueInput | Prisma.FundContributionLogWhereUniqueInput[]
  update?: Prisma.FundContributionLogUpdateWithWhereUniqueWithoutContributorInput | Prisma.FundContributionLogUpdateWithWhereUniqueWithoutContributorInput[]
  updateMany?: Prisma.FundContributionLogUpdateManyWithWhereWithoutContributorInput | Prisma.FundContributionLogUpdateManyWithWhereWithoutContributorInput[]
  deleteMany?: Prisma.FundContributionLogScalarWhereInput | Prisma.FundContributionLogScalarWhereInput[]
}

export type FundContributionLogUncheckedUpdateManyWithoutReporterNestedInput = {
  create?: Prisma.XOR<Prisma.FundContributionLogCreateWithoutReporterInput, Prisma.FundContributionLogUncheckedCreateWithoutReporterInput> | Prisma.FundContributionLogCreateWithoutReporterInput[] | Prisma.FundContributionLogUncheckedCreateWithoutReporterInput[]
  connectOrCreate?: Prisma.FundContributionLogCreateOrConnectWithoutReporterInput | Prisma.FundContributionLogCreateOrConnectWithoutReporterInput[]
  upsert?: Prisma.FundContributionLogUpsertWithWhereUniqueWithoutReporterInput | Prisma.FundContributionLogUpsertWithWhereUniqueWithoutReporterInput[]
  createMany?: Prisma.FundContributionLogCreateManyReporterInputEnvelope
  set?: Prisma.FundContributionLogWhereUniqueInput | Prisma.FundContributionLogWhereUniqueInput[]
  disconnect?: Prisma.FundContributionLogWhereUniqueInput | Prisma.FundContributionLogWhereUniqueInput[]
  delete?: Prisma.FundContributionLogWhereUniqueInput | Prisma.FundContributionLogWhereUniqueInput[]
  connect?: Prisma.FundContributionLogWhereUniqueInput | Prisma.FundContributionLogWhereUniqueInput[]
  update?: Prisma.FundContributionLogUpdateWithWhereUniqueWithoutReporterInput | Prisma.FundContributionLogUpdateWithWhereUniqueWithoutReporterInput[]
  updateMany?: Prisma.FundContributionLogUpdateManyWithWhereWithoutReporterInput | Prisma.FundContributionLogUpdateManyWithWhereWithoutReporterInput[]
  deleteMany?: Prisma.FundContributionLogScalarWhereInput | Prisma.FundContributionLogScalarWhereInput[]
}

export type FundContributionLogUncheckedUpdateManyWithoutContributorNestedInput = {
  create?: Prisma.XOR<Prisma.FundContributionLogCreateWithoutContributorInput, Prisma.FundContributionLogUncheckedCreateWithoutContributorInput> | Prisma.FundContributionLogCreateWithoutContributorInput[] | Prisma.FundContributionLogUncheckedCreateWithoutContributorInput[]
  connectOrCreate?: Prisma.FundContributionLogCreateOrConnectWithoutContributorInput | Prisma.FundContributionLogCreateOrConnectWithoutContributorInput[]
  upsert?: Prisma.FundContributionLogUpsertWithWhereUniqueWithoutContributorInput | Prisma.FundContributionLogUpsertWithWhereUniqueWithoutContributorInput[]
  createMany?: Prisma.FundContributionLogCreateManyContributorInputEnvelope
  set?: Prisma.FundContributionLogWhereUniqueInput | Prisma.FundContributionLogWhereUniqueInput[]
  disconnect?: Prisma.FundContributionLogWhereUniqueInput | Prisma.FundContributionLogWhereUniqueInput[]
  delete?: Prisma.FundContributionLogWhereUniqueInput | Prisma.FundContributionLogWhereUniqueInput[]
  connect?: Prisma.FundContributionLogWhereUniqueInput | Prisma.FundContributionLogWhereUniqueInput[]
  update?: Prisma.FundContributionLogUpdateWithWhereUniqueWithoutContributorInput | Prisma.FundContributionLogUpdateWithWhereUniqueWithoutContributorInput[]
  updateMany?: Prisma.FundContributionLogUpdateManyWithWhereWithoutContributorInput | Prisma.FundContributionLogUpdateManyWithWhereWithoutContributorInput[]
  deleteMany?: Prisma.FundContributionLogScalarWhereInput | Prisma.FundContributionLogScalarWhereInput[]
}

export type FundContributionLogCreateNestedManyWithoutFundInput = {
  create?: Prisma.XOR<Prisma.FundContributionLogCreateWithoutFundInput, Prisma.FundContributionLogUncheckedCreateWithoutFundInput> | Prisma.FundContributionLogCreateWithoutFundInput[] | Prisma.FundContributionLogUncheckedCreateWithoutFundInput[]
  connectOrCreate?: Prisma.FundContributionLogCreateOrConnectWithoutFundInput | Prisma.FundContributionLogCreateOrConnectWithoutFundInput[]
  createMany?: Prisma.FundContributionLogCreateManyFundInputEnvelope
  connect?: Prisma.FundContributionLogWhereUniqueInput | Prisma.FundContributionLogWhereUniqueInput[]
}

export type FundContributionLogUncheckedCreateNestedManyWithoutFundInput = {
  create?: Prisma.XOR<Prisma.FundContributionLogCreateWithoutFundInput, Prisma.FundContributionLogUncheckedCreateWithoutFundInput> | Prisma.FundContributionLogCreateWithoutFundInput[] | Prisma.FundContributionLogUncheckedCreateWithoutFundInput[]
  connectOrCreate?: Prisma.FundContributionLogCreateOrConnectWithoutFundInput | Prisma.FundContributionLogCreateOrConnectWithoutFundInput[]
  createMany?: Prisma.FundContributionLogCreateManyFundInputEnvelope
  connect?: Prisma.FundContributionLogWhereUniqueInput | Prisma.FundContributionLogWhereUniqueInput[]
}

export type FundContributionLogUpdateManyWithoutFundNestedInput = {
  create?: Prisma.XOR<Prisma.FundContributionLogCreateWithoutFundInput, Prisma.FundContributionLogUncheckedCreateWithoutFundInput> | Prisma.FundContributionLogCreateWithoutFundInput[] | Prisma.FundContributionLogUncheckedCreateWithoutFundInput[]
  connectOrCreate?: Prisma.FundContributionLogCreateOrConnectWithoutFundInput | Prisma.FundContributionLogCreateOrConnectWithoutFundInput[]
  upsert?: Prisma.FundContributionLogUpsertWithWhereUniqueWithoutFundInput | Prisma.FundContributionLogUpsertWithWhereUniqueWithoutFundInput[]
  createMany?: Prisma.FundContributionLogCreateManyFundInputEnvelope
  set?: Prisma.FundContributionLogWhereUniqueInput | Prisma.FundContributionLogWhereUniqueInput[]
  disconnect?: Prisma.FundContributionLogWhereUniqueInput | Prisma.FundContributionLogWhereUniqueInput[]
  delete?: Prisma.FundContributionLogWhereUniqueInput | Prisma.FundContributionLogWhereUniqueInput[]
  connect?: Prisma.FundContributionLogWhereUniqueInput | Prisma.FundContributionLogWhereUniqueInput[]
  update?: Prisma.FundContributionLogUpdateWithWhereUniqueWithoutFundInput | Prisma.FundContributionLogUpdateWithWhereUniqueWithoutFundInput[]
  updateMany?: Prisma.FundContributionLogUpdateManyWithWhereWithoutFundInput | Prisma.FundContributionLogUpdateManyWithWhereWithoutFundInput[]
  deleteMany?: Prisma.FundContributionLogScalarWhereInput | Prisma.FundContributionLogScalarWhereInput[]
}

export type FundContributionLogUncheckedUpdateManyWithoutFundNestedInput = {
  create?: Prisma.XOR<Prisma.FundContributionLogCreateWithoutFundInput, Prisma.FundContributionLogUncheckedCreateWithoutFundInput> | Prisma.FundContributionLogCreateWithoutFundInput[] | Prisma.FundContributionLogUncheckedCreateWithoutFundInput[]
  connectOrCreate?: Prisma.FundContributionLogCreateOrConnectWithoutFundInput | Prisma.FundContributionLogCreateOrConnectWithoutFundInput[]
  upsert?: Prisma.FundContributionLogUpsertWithWhereUniqueWithoutFundInput | Prisma.FundContributionLogUpsertWithWhereUniqueWithoutFundInput[]
  createMany?: Prisma.FundContributionLogCreateManyFundInputEnvelope
  set?: Prisma.FundContributionLogWhereUniqueInput | Prisma.FundContributionLogWhereUniqueInput[]
  disconnect?: Prisma.FundContributionLogWhereUniqueInput | Prisma.FundContributionLogWhereUniqueInput[]
  delete?: Prisma.FundContributionLogWhereUniqueInput | Prisma.FundContributionLogWhereUniqueInput[]
  connect?: Prisma.FundContributionLogWhereUniqueInput | Prisma.FundContributionLogWhereUniqueInput[]
  update?: Prisma.FundContributionLogUpdateWithWhereUniqueWithoutFundInput | Prisma.FundContributionLogUpdateWithWhereUniqueWithoutFundInput[]
  updateMany?: Prisma.FundContributionLogUpdateManyWithWhereWithoutFundInput | Prisma.FundContributionLogUpdateManyWithWhereWithoutFundInput[]
  deleteMany?: Prisma.FundContributionLogScalarWhereInput | Prisma.FundContributionLogScalarWhereInput[]
}

export type EnumFundTransactionTypeFieldUpdateOperationsInput = {
  set?: $Enums.FundTransactionType
}

export type FundContributionLogCreateWithoutReporterInput = {
  id?: string
  currency?: string
  amount: number
  note?: string | null
  type?: $Enums.FundTransactionType
  createdAt?: Date | string
  fund?: Prisma.FundCreateNestedOneWithoutContributionLogsInput
  contributor: Prisma.UserCreateNestedOneWithoutContributedLogsInput
}

export type FundContributionLogUncheckedCreateWithoutReporterInput = {
  id?: string
  contributorId: string
  fundId?: number
  currency?: string
  amount: number
  note?: string | null
  type?: $Enums.FundTransactionType
  createdAt?: Date | string
}

export type FundContributionLogCreateOrConnectWithoutReporterInput = {
  where: Prisma.FundContributionLogWhereUniqueInput
  create: Prisma.XOR<Prisma.FundContributionLogCreateWithoutReporterInput, Prisma.FundContributionLogUncheckedCreateWithoutReporterInput>
}

export type FundContributionLogCreateManyReporterInputEnvelope = {
  data: Prisma.FundContributionLogCreateManyReporterInput | Prisma.FundContributionLogCreateManyReporterInput[]
}

export type FundContributionLogCreateWithoutContributorInput = {
  id?: string
  currency?: string
  amount: number
  note?: string | null
  type?: $Enums.FundTransactionType
  createdAt?: Date | string
  fund?: Prisma.FundCreateNestedOneWithoutContributionLogsInput
  reporter: Prisma.UserCreateNestedOneWithoutReportedLogsInput
}

export type FundContributionLogUncheckedCreateWithoutContributorInput = {
  id?: string
  reporterId: string
  fundId?: number
  currency?: string
  amount: number
  note?: string | null
  type?: $Enums.FundTransactionType
  createdAt?: Date | string
}

export type FundContributionLogCreateOrConnectWithoutContributorInput = {
  where: Prisma.FundContributionLogWhereUniqueInput
  create: Prisma.XOR<Prisma.FundContributionLogCreateWithoutContributorInput, Prisma.FundContributionLogUncheckedCreateWithoutContributorInput>
}

export type FundContributionLogCreateManyContributorInputEnvelope = {
  data: Prisma.FundContributionLogCreateManyContributorInput | Prisma.FundContributionLogCreateManyContributorInput[]
}

export type FundContributionLogUpsertWithWhereUniqueWithoutReporterInput = {
  where: Prisma.FundContributionLogWhereUniqueInput
  update: Prisma.XOR<Prisma.FundContributionLogUpdateWithoutReporterInput, Prisma.FundContributionLogUncheckedUpdateWithoutReporterInput>
  create: Prisma.XOR<Prisma.FundContributionLogCreateWithoutReporterInput, Prisma.FundContributionLogUncheckedCreateWithoutReporterInput>
}

export type FundContributionLogUpdateWithWhereUniqueWithoutReporterInput = {
  where: Prisma.FundContributionLogWhereUniqueInput
  data: Prisma.XOR<Prisma.FundContributionLogUpdateWithoutReporterInput, Prisma.FundContributionLogUncheckedUpdateWithoutReporterInput>
}

export type FundContributionLogUpdateManyWithWhereWithoutReporterInput = {
  where: Prisma.FundContributionLogScalarWhereInput
  data: Prisma.XOR<Prisma.FundContributionLogUpdateManyMutationInput, Prisma.FundContributionLogUncheckedUpdateManyWithoutReporterInput>
}

export type FundContributionLogScalarWhereInput = {
  AND?: Prisma.FundContributionLogScalarWhereInput | Prisma.FundContributionLogScalarWhereInput[]
  OR?: Prisma.FundContributionLogScalarWhereInput[]
  NOT?: Prisma.FundContributionLogScalarWhereInput | Prisma.FundContributionLogScalarWhereInput[]
  id?: Prisma.StringFilter<"FundContributionLog"> | string
  reporterId?: Prisma.StringFilter<"FundContributionLog"> | string
  contributorId?: Prisma.StringFilter<"FundContributionLog"> | string
  fundId?: Prisma.IntFilter<"FundContributionLog"> | number
  currency?: Prisma.StringFilter<"FundContributionLog"> | string
  amount?: Prisma.FloatFilter<"FundContributionLog"> | number
  note?: Prisma.StringNullableFilter<"FundContributionLog"> | string | null
  type?: Prisma.EnumFundTransactionTypeFilter<"FundContributionLog"> | $Enums.FundTransactionType
  createdAt?: Prisma.DateTimeFilter<"FundContributionLog"> | Date | string
}

export type FundContributionLogUpsertWithWhereUniqueWithoutContributorInput = {
  where: Prisma.FundContributionLogWhereUniqueInput
  update: Prisma.XOR<Prisma.FundContributionLogUpdateWithoutContributorInput, Prisma.FundContributionLogUncheckedUpdateWithoutContributorInput>
  create: Prisma.XOR<Prisma.FundContributionLogCreateWithoutContributorInput, Prisma.FundContributionLogUncheckedCreateWithoutContributorInput>
}

export type FundContributionLogUpdateWithWhereUniqueWithoutContributorInput = {
  where: Prisma.FundContributionLogWhereUniqueInput
  data: Prisma.XOR<Prisma.FundContributionLogUpdateWithoutContributorInput, Prisma.FundContributionLogUncheckedUpdateWithoutContributorInput>
}

export type FundContributionLogUpdateManyWithWhereWithoutContributorInput = {
  where: Prisma.FundContributionLogScalarWhereInput
  data: Prisma.XOR<Prisma.FundContributionLogUpdateManyMutationInput, Prisma.FundContributionLogUncheckedUpdateManyWithoutContributorInput>
}

export type FundContributionLogCreateWithoutFundInput = {
  id?: string
  currency?: string
  amount: number
  note?: string | null
  type?: $Enums.FundTransactionType
  createdAt?: Date | string
  reporter: Prisma.UserCreateNestedOneWithoutReportedLogsInput
  contributor: Prisma.UserCreateNestedOneWithoutContributedLogsInput
}

export type FundContributionLogUncheckedCreateWithoutFundInput = {
  id?: string
  reporterId: string
  contributorId: string
  currency?: string
  amount: number
  note?: string | null
  type?: $Enums.FundTransactionType
  createdAt?: Date | string
}

export type FundContributionLogCreateOrConnectWithoutFundInput = {
  where: Prisma.FundContributionLogWhereUniqueInput
  create: Prisma.XOR<Prisma.FundContributionLogCreateWithoutFundInput, Prisma.FundContributionLogUncheckedCreateWithoutFundInput>
}

export type FundContributionLogCreateManyFundInputEnvelope = {
  data: Prisma.FundContributionLogCreateManyFundInput | Prisma.FundContributionLogCreateManyFundInput[]
}

export type FundContributionLogUpsertWithWhereUniqueWithoutFundInput = {
  where: Prisma.FundContributionLogWhereUniqueInput
  update: Prisma.XOR<Prisma.FundContributionLogUpdateWithoutFundInput, Prisma.FundContributionLogUncheckedUpdateWithoutFundInput>
  create: Prisma.XOR<Prisma.FundContributionLogCreateWithoutFundInput, Prisma.FundContributionLogUncheckedCreateWithoutFundInput>
}

export type FundContributionLogUpdateWithWhereUniqueWithoutFundInput = {
  where: Prisma.FundContributionLogWhereUniqueInput
  data: Prisma.XOR<Prisma.FundContributionLogUpdateWithoutFundInput, Prisma.FundContributionLogUncheckedUpdateWithoutFundInput>
}

export type FundContributionLogUpdateManyWithWhereWithoutFundInput = {
  where: Prisma.FundContributionLogScalarWhereInput
  data: Prisma.XOR<Prisma.FundContributionLogUpdateManyMutationInput, Prisma.FundContributionLogUncheckedUpdateManyWithoutFundInput>
}

export type FundContributionLogCreateManyReporterInput = {
  id?: string
  contributorId: string
  fundId?: number
  currency?: string
  amount: number
  note?: string | null
  type?: $Enums.FundTransactionType
  createdAt?: Date | string
}

export type FundContributionLogCreateManyContributorInput = {
  id?: string
  reporterId: string
  fundId?: number
  currency?: string
  amount: number
  note?: string | null
  type?: $Enums.FundTransactionType
  createdAt?: Date | string
}

export type FundContributionLogUpdateWithoutReporterInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  currency?: Prisma.StringFieldUpdateOperationsInput | string
  amount?: Prisma.FloatFieldUpdateOperationsInput | number
  note?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  type?: Prisma.EnumFundTransactionTypeFieldUpdateOperationsInput | $Enums.FundTransactionType
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  fund?: Prisma.FundUpdateOneRequiredWithoutContributionLogsNestedInput
  contributor?: Prisma.UserUpdateOneRequiredWithoutContributedLogsNestedInput
}

export type FundContributionLogUncheckedUpdateWithoutReporterInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  contributorId?: Prisma.StringFieldUpdateOperationsInput | string
  fundId?: Prisma.IntFieldUpdateOperationsInput | number
  currency?: Prisma.StringFieldUpdateOperationsInput | string
  amount?: Prisma.FloatFieldUpdateOperationsInput | number
  note?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  type?: Prisma.EnumFundTransactionTypeFieldUpdateOperationsInput | $Enums.FundTransactionType
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type FundContributionLogUncheckedUpdateManyWithoutReporterInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  contributorId?: Prisma.StringFieldUpdateOperationsInput | string
  fundId?: Prisma.IntFieldUpdateOperationsInput | number
  currency?: Prisma.StringFieldUpdateOperationsInput | string
  amount?: Prisma.FloatFieldUpdateOperationsInput | number
  note?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  type?: Prisma.EnumFundTransactionTypeFieldUpdateOperationsInput | $Enums.FundTransactionType
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type FundContributionLogUpdateWithoutContributorInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  currency?: Prisma.StringFieldUpdateOperationsInput | string
  amount?: Prisma.FloatFieldUpdateOperationsInput | number
  note?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  type?: Prisma.EnumFundTransactionTypeFieldUpdateOperationsInput | $Enums.FundTransactionType
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  fund?: Prisma.FundUpdateOneRequiredWithoutContributionLogsNestedInput
  reporter?: Prisma.UserUpdateOneRequiredWithoutReportedLogsNestedInput
}

export type FundContributionLogUncheckedUpdateWithoutContributorInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  reporterId?: Prisma.StringFieldUpdateOperationsInput | string
  fundId?: Prisma.IntFieldUpdateOperationsInput | number
  currency?: Prisma.StringFieldUpdateOperationsInput | string
  amount?: Prisma.FloatFieldUpdateOperationsInput | number
  note?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  type?: Prisma.EnumFundTransactionTypeFieldUpdateOperationsInput | $Enums.FundTransactionType
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type FundContributionLogUncheckedUpdateManyWithoutContributorInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  reporterId?: Prisma.StringFieldUpdateOperationsInput | string
  fundId?: Prisma.IntFieldUpdateOperationsInput | number
  currency?: Prisma.StringFieldUpdateOperationsInput | string
  amount?: Prisma.FloatFieldUpdateOperationsInput | number
  note?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  type?: Prisma.EnumFundTransactionTypeFieldUpdateOperationsInput | $Enums.FundTransactionType
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type FundContributionLogCreateManyFundInput = {
  id?: string
  reporterId: string
  contributorId: string
  currency?: string
  amount: number
  note?: string | null
  type?: $Enums.FundTransactionType
  createdAt?: Date | string
}

export type FundContributionLogUpdateWithoutFundInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  currency?: Prisma.StringFieldUpdateOperationsInput | string
  amount?: Prisma.FloatFieldUpdateOperationsInput | number
  note?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  type?: Prisma.EnumFundTransactionTypeFieldUpdateOperationsInput | $Enums.FundTransactionType
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  reporter?: Prisma.UserUpdateOneRequiredWithoutReportedLogsNestedInput
  contributor?: Prisma.UserUpdateOneRequiredWithoutContributedLogsNestedInput
}

export type FundContributionLogUncheckedUpdateWithoutFundInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  reporterId?: Prisma.StringFieldUpdateOperationsInput | string
  contributorId?: Prisma.StringFieldUpdateOperationsInput | string
  currency?: Prisma.StringFieldUpdateOperationsInput | string
  amount?: Prisma.FloatFieldUpdateOperationsInput | number
  note?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  type?: Prisma.EnumFundTransactionTypeFieldUpdateOperationsInput | $Enums.FundTransactionType
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type FundContributionLogUncheckedUpdateManyWithoutFundInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  reporterId?: Prisma.StringFieldUpdateOperationsInput | string
  contributorId?: Prisma.StringFieldUpdateOperationsInput | string
  currency?: Prisma.StringFieldUpdateOperationsInput | string
  amount?: Prisma.FloatFieldUpdateOperationsInput | number
  note?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  type?: Prisma.EnumFundTransactionTypeFieldUpdateOperationsInput | $Enums.FundTransactionType
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}



export type FundContributionLogSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  reporterId?: boolean
  contributorId?: boolean
  fundId?: boolean
  currency?: boolean
  amount?: boolean
  note?: boolean
  type?: boolean
  createdAt?: boolean
  fund?: boolean | Prisma.FundDefaultArgs<ExtArgs>
  reporter?: boolean | Prisma.UserDefaultArgs<ExtArgs>
  contributor?: boolean | Prisma.UserDefaultArgs<ExtArgs>
}, ExtArgs["result"]["fundContributionLog"]>

export type FundContributionLogSelectCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  reporterId?: boolean
  contributorId?: boolean
  fundId?: boolean
  currency?: boolean
  amount?: boolean
  note?: boolean
  type?: boolean
  createdAt?: boolean
  fund?: boolean | Prisma.FundDefaultArgs<ExtArgs>
  reporter?: boolean | Prisma.UserDefaultArgs<ExtArgs>
  contributor?: boolean | Prisma.UserDefaultArgs<ExtArgs>
}, ExtArgs["result"]["fundContributionLog"]>

export type FundContributionLogSelectUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  reporterId?: boolean
  contributorId?: boolean
  fundId?: boolean
  currency?: boolean
  amount?: boolean
  note?: boolean
  type?: boolean
  createdAt?: boolean
  fund?: boolean | Prisma.FundDefaultArgs<ExtArgs>
  reporter?: boolean | Prisma.UserDefaultArgs<ExtArgs>
  contributor?: boolean | Prisma.UserDefaultArgs<ExtArgs>
}, ExtArgs["result"]["fundContributionLog"]>

export type FundContributionLogSelectScalar = {
  id?: boolean
  reporterId?: boolean
  contributorId?: boolean
  fundId?: boolean
  currency?: boolean
  amount?: boolean
  note?: boolean
  type?: boolean
  createdAt?: boolean
}

export type FundContributionLogOmit<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetOmit<"id" | "reporterId" | "contributorId" | "fundId" | "currency" | "amount" | "note" | "type" | "createdAt", ExtArgs["result"]["fundContributionLog"]>
export type FundContributionLogInclude<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  fund?: boolean | Prisma.FundDefaultArgs<ExtArgs>
  reporter?: boolean | Prisma.UserDefaultArgs<ExtArgs>
  contributor?: boolean | Prisma.UserDefaultArgs<ExtArgs>
}
export type FundContributionLogIncludeCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  fund?: boolean | Prisma.FundDefaultArgs<ExtArgs>
  reporter?: boolean | Prisma.UserDefaultArgs<ExtArgs>
  contributor?: boolean | Prisma.UserDefaultArgs<ExtArgs>
}
export type FundContributionLogIncludeUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  fund?: boolean | Prisma.FundDefaultArgs<ExtArgs>
  reporter?: boolean | Prisma.UserDefaultArgs<ExtArgs>
  contributor?: boolean | Prisma.UserDefaultArgs<ExtArgs>
}

export type $FundContributionLogPayload<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  name: "FundContributionLog"
  objects: {
    fund: Prisma.$FundPayload<ExtArgs>
    reporter: Prisma.$UserPayload<ExtArgs>
    contributor: Prisma.$UserPayload<ExtArgs>
  }
  scalars: runtime.Types.Extensions.GetPayloadResult<{
    id: string
    reporterId: string
    contributorId: string
    fundId: number
    currency: string
    amount: number
    note: string | null
    type: $Enums.FundTransactionType
    createdAt: Date
  }, ExtArgs["result"]["fundContributionLog"]>
  composites: {}
}

export type FundContributionLogGetPayload<S extends boolean | null | undefined | FundContributionLogDefaultArgs> = runtime.Types.Result.GetResult<Prisma.$FundContributionLogPayload, S>

export type FundContributionLogCountArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> =
  Omit<FundContributionLogFindManyArgs, 'select' | 'include' | 'distinct' | 'omit'> & {
    select?: FundContributionLogCountAggregateInputType | true
  }

export interface FundContributionLogDelegate<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> {
  [K: symbol]: { types: Prisma.TypeMap<ExtArgs>['model']['FundContributionLog'], meta: { name: 'FundContributionLog' } }
  /**
   * Find zero or one FundContributionLog that matches the filter.
   * @param {FundContributionLogFindUniqueArgs} args - Arguments to find a FundContributionLog
   * @example
   * // Get one FundContributionLog
   * const fundContributionLog = await prisma.fundContributionLog.findUnique({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUnique<T extends FundContributionLogFindUniqueArgs>(args: Prisma.SelectSubset<T, FundContributionLogFindUniqueArgs<ExtArgs>>): Prisma.Prisma__FundContributionLogClient<runtime.Types.Result.GetResult<Prisma.$FundContributionLogPayload<ExtArgs>, T, "findUnique", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find one FundContributionLog that matches the filter or throw an error with `error.code='P2025'`
   * if no matches were found.
   * @param {FundContributionLogFindUniqueOrThrowArgs} args - Arguments to find a FundContributionLog
   * @example
   * // Get one FundContributionLog
   * const fundContributionLog = await prisma.fundContributionLog.findUniqueOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUniqueOrThrow<T extends FundContributionLogFindUniqueOrThrowArgs>(args: Prisma.SelectSubset<T, FundContributionLogFindUniqueOrThrowArgs<ExtArgs>>): Prisma.Prisma__FundContributionLogClient<runtime.Types.Result.GetResult<Prisma.$FundContributionLogPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first FundContributionLog that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {FundContributionLogFindFirstArgs} args - Arguments to find a FundContributionLog
   * @example
   * // Get one FundContributionLog
   * const fundContributionLog = await prisma.fundContributionLog.findFirst({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirst<T extends FundContributionLogFindFirstArgs>(args?: Prisma.SelectSubset<T, FundContributionLogFindFirstArgs<ExtArgs>>): Prisma.Prisma__FundContributionLogClient<runtime.Types.Result.GetResult<Prisma.$FundContributionLogPayload<ExtArgs>, T, "findFirst", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first FundContributionLog that matches the filter or
   * throw `PrismaKnownClientError` with `P2025` code if no matches were found.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {FundContributionLogFindFirstOrThrowArgs} args - Arguments to find a FundContributionLog
   * @example
   * // Get one FundContributionLog
   * const fundContributionLog = await prisma.fundContributionLog.findFirstOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirstOrThrow<T extends FundContributionLogFindFirstOrThrowArgs>(args?: Prisma.SelectSubset<T, FundContributionLogFindFirstOrThrowArgs<ExtArgs>>): Prisma.Prisma__FundContributionLogClient<runtime.Types.Result.GetResult<Prisma.$FundContributionLogPayload<ExtArgs>, T, "findFirstOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find zero or more FundContributionLogs that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {FundContributionLogFindManyArgs} args - Arguments to filter and select certain fields only.
   * @example
   * // Get all FundContributionLogs
   * const fundContributionLogs = await prisma.fundContributionLog.findMany()
   * 
   * // Get first 10 FundContributionLogs
   * const fundContributionLogs = await prisma.fundContributionLog.findMany({ take: 10 })
   * 
   * // Only select the `id`
   * const fundContributionLogWithIdOnly = await prisma.fundContributionLog.findMany({ select: { id: true } })
   * 
   */
  findMany<T extends FundContributionLogFindManyArgs>(args?: Prisma.SelectSubset<T, FundContributionLogFindManyArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$FundContributionLogPayload<ExtArgs>, T, "findMany", GlobalOmitOptions>>

  /**
   * Create a FundContributionLog.
   * @param {FundContributionLogCreateArgs} args - Arguments to create a FundContributionLog.
   * @example
   * // Create one FundContributionLog
   * const FundContributionLog = await prisma.fundContributionLog.create({
   *   data: {
   *     // ... data to create a FundContributionLog
   *   }
   * })
   * 
   */
  create<T extends FundContributionLogCreateArgs>(args: Prisma.SelectSubset<T, FundContributionLogCreateArgs<ExtArgs>>): Prisma.Prisma__FundContributionLogClient<runtime.Types.Result.GetResult<Prisma.$FundContributionLogPayload<ExtArgs>, T, "create", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Create many FundContributionLogs.
   * @param {FundContributionLogCreateManyArgs} args - Arguments to create many FundContributionLogs.
   * @example
   * // Create many FundContributionLogs
   * const fundContributionLog = await prisma.fundContributionLog.createMany({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   *     
   */
  createMany<T extends FundContributionLogCreateManyArgs>(args?: Prisma.SelectSubset<T, FundContributionLogCreateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Create many FundContributionLogs and returns the data saved in the database.
   * @param {FundContributionLogCreateManyAndReturnArgs} args - Arguments to create many FundContributionLogs.
   * @example
   * // Create many FundContributionLogs
   * const fundContributionLog = await prisma.fundContributionLog.createManyAndReturn({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Create many FundContributionLogs and only return the `id`
   * const fundContributionLogWithIdOnly = await prisma.fundContributionLog.createManyAndReturn({
   *   select: { id: true },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  createManyAndReturn<T extends FundContributionLogCreateManyAndReturnArgs>(args?: Prisma.SelectSubset<T, FundContributionLogCreateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$FundContributionLogPayload<ExtArgs>, T, "createManyAndReturn", GlobalOmitOptions>>

  /**
   * Delete a FundContributionLog.
   * @param {FundContributionLogDeleteArgs} args - Arguments to delete one FundContributionLog.
   * @example
   * // Delete one FundContributionLog
   * const FundContributionLog = await prisma.fundContributionLog.delete({
   *   where: {
   *     // ... filter to delete one FundContributionLog
   *   }
   * })
   * 
   */
  delete<T extends FundContributionLogDeleteArgs>(args: Prisma.SelectSubset<T, FundContributionLogDeleteArgs<ExtArgs>>): Prisma.Prisma__FundContributionLogClient<runtime.Types.Result.GetResult<Prisma.$FundContributionLogPayload<ExtArgs>, T, "delete", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Update one FundContributionLog.
   * @param {FundContributionLogUpdateArgs} args - Arguments to update one FundContributionLog.
   * @example
   * // Update one FundContributionLog
   * const fundContributionLog = await prisma.fundContributionLog.update({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  update<T extends FundContributionLogUpdateArgs>(args: Prisma.SelectSubset<T, FundContributionLogUpdateArgs<ExtArgs>>): Prisma.Prisma__FundContributionLogClient<runtime.Types.Result.GetResult<Prisma.$FundContributionLogPayload<ExtArgs>, T, "update", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Delete zero or more FundContributionLogs.
   * @param {FundContributionLogDeleteManyArgs} args - Arguments to filter FundContributionLogs to delete.
   * @example
   * // Delete a few FundContributionLogs
   * const { count } = await prisma.fundContributionLog.deleteMany({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   * 
   */
  deleteMany<T extends FundContributionLogDeleteManyArgs>(args?: Prisma.SelectSubset<T, FundContributionLogDeleteManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more FundContributionLogs.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {FundContributionLogUpdateManyArgs} args - Arguments to update one or more rows.
   * @example
   * // Update many FundContributionLogs
   * const fundContributionLog = await prisma.fundContributionLog.updateMany({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  updateMany<T extends FundContributionLogUpdateManyArgs>(args: Prisma.SelectSubset<T, FundContributionLogUpdateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more FundContributionLogs and returns the data updated in the database.
   * @param {FundContributionLogUpdateManyAndReturnArgs} args - Arguments to update many FundContributionLogs.
   * @example
   * // Update many FundContributionLogs
   * const fundContributionLog = await prisma.fundContributionLog.updateManyAndReturn({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Update zero or more FundContributionLogs and only return the `id`
   * const fundContributionLogWithIdOnly = await prisma.fundContributionLog.updateManyAndReturn({
   *   select: { id: true },
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  updateManyAndReturn<T extends FundContributionLogUpdateManyAndReturnArgs>(args: Prisma.SelectSubset<T, FundContributionLogUpdateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$FundContributionLogPayload<ExtArgs>, T, "updateManyAndReturn", GlobalOmitOptions>>

  /**
   * Create or update one FundContributionLog.
   * @param {FundContributionLogUpsertArgs} args - Arguments to update or create a FundContributionLog.
   * @example
   * // Update or create a FundContributionLog
   * const fundContributionLog = await prisma.fundContributionLog.upsert({
   *   create: {
   *     // ... data to create a FundContributionLog
   *   },
   *   update: {
   *     // ... in case it already exists, update
   *   },
   *   where: {
   *     // ... the filter for the FundContributionLog we want to update
   *   }
   * })
   */
  upsert<T extends FundContributionLogUpsertArgs>(args: Prisma.SelectSubset<T, FundContributionLogUpsertArgs<ExtArgs>>): Prisma.Prisma__FundContributionLogClient<runtime.Types.Result.GetResult<Prisma.$FundContributionLogPayload<ExtArgs>, T, "upsert", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>


  /**
   * Count the number of FundContributionLogs.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {FundContributionLogCountArgs} args - Arguments to filter FundContributionLogs to count.
   * @example
   * // Count the number of FundContributionLogs
   * const count = await prisma.fundContributionLog.count({
   *   where: {
   *     // ... the filter for the FundContributionLogs we want to count
   *   }
   * })
  **/
  count<T extends FundContributionLogCountArgs>(
    args?: Prisma.Subset<T, FundContributionLogCountArgs>,
  ): Prisma.PrismaPromise<
    T extends runtime.Types.Utils.Record<'select', any>
      ? T['select'] extends true
        ? number
        : Prisma.GetScalarType<T['select'], FundContributionLogCountAggregateOutputType>
      : number
  >

  /**
   * Allows you to perform aggregations operations on a FundContributionLog.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {FundContributionLogAggregateArgs} args - Select which aggregations you would like to apply and on what fields.
   * @example
   * // Ordered by age ascending
   * // Where email contains prisma.io
   * // Limited to the 10 users
   * const aggregations = await prisma.user.aggregate({
   *   _avg: {
   *     age: true,
   *   },
   *   where: {
   *     email: {
   *       contains: "prisma.io",
   *     },
   *   },
   *   orderBy: {
   *     age: "asc",
   *   },
   *   take: 10,
   * })
  **/
  aggregate<T extends FundContributionLogAggregateArgs>(args: Prisma.Subset<T, FundContributionLogAggregateArgs>): Prisma.PrismaPromise<GetFundContributionLogAggregateType<T>>

  /**
   * Group by FundContributionLog.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {FundContributionLogGroupByArgs} args - Group by arguments.
   * @example
   * // Group by city, order by createdAt, get count
   * const result = await prisma.user.groupBy({
   *   by: ['city', 'createdAt'],
   *   orderBy: {
   *     createdAt: true
   *   },
   *   _count: {
   *     _all: true
   *   },
   * })
   * 
  **/
  groupBy<
    T extends FundContributionLogGroupByArgs,
    HasSelectOrTake extends Prisma.Or<
      Prisma.Extends<'skip', Prisma.Keys<T>>,
      Prisma.Extends<'take', Prisma.Keys<T>>
    >,
    OrderByArg extends Prisma.True extends HasSelectOrTake
      ? { orderBy: FundContributionLogGroupByArgs['orderBy'] }
      : { orderBy?: FundContributionLogGroupByArgs['orderBy'] },
    OrderFields extends Prisma.ExcludeUnderscoreKeys<Prisma.Keys<Prisma.MaybeTupleToUnion<T['orderBy']>>>,
    ByFields extends Prisma.MaybeTupleToUnion<T['by']>,
    ByValid extends Prisma.Has<ByFields, OrderFields>,
    HavingFields extends Prisma.GetHavingFields<T['having']>,
    HavingValid extends Prisma.Has<ByFields, HavingFields>,
    ByEmpty extends T['by'] extends never[] ? Prisma.True : Prisma.False,
    InputErrors extends ByEmpty extends Prisma.True
    ? `Error: "by" must not be empty.`
    : HavingValid extends Prisma.False
    ? {
        [P in HavingFields]: P extends ByFields
          ? never
          : P extends string
          ? `Error: Field "${P}" used in "having" needs to be provided in "by".`
          : [
              Error,
              'Field ',
              P,
              ` in "having" needs to be provided in "by"`,
            ]
      }[HavingFields]
    : 'take' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "take", you also need to provide "orderBy"'
    : 'skip' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "skip", you also need to provide "orderBy"'
    : ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
          ? never
          : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
      }[OrderFields]
  >(args: Prisma.SubsetIntersection<T, FundContributionLogGroupByArgs, OrderByArg> & InputErrors): {} extends InputErrors ? GetFundContributionLogGroupByPayload<T> : Prisma.PrismaPromise<InputErrors>
/**
 * Fields of the FundContributionLog model
 */
readonly fields: FundContributionLogFieldRefs;
}

/**
 * The delegate class that acts as a "Promise-like" for FundContributionLog.
 * Why is this prefixed with `Prisma__`?
 * Because we want to prevent naming conflicts as mentioned in
 * https://github.com/prisma/prisma-client-js/issues/707
 */
export interface Prisma__FundContributionLogClient<T, Null = never, ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> extends Prisma.PrismaPromise<T> {
  readonly [Symbol.toStringTag]: "PrismaPromise"
  fund<T extends Prisma.FundDefaultArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.FundDefaultArgs<ExtArgs>>): Prisma.Prisma__FundClient<runtime.Types.Result.GetResult<Prisma.$FundPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions> | Null, Null, ExtArgs, GlobalOmitOptions>
  reporter<T extends Prisma.UserDefaultArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.UserDefaultArgs<ExtArgs>>): Prisma.Prisma__UserClient<runtime.Types.Result.GetResult<Prisma.$UserPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions> | Null, Null, ExtArgs, GlobalOmitOptions>
  contributor<T extends Prisma.UserDefaultArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.UserDefaultArgs<ExtArgs>>): Prisma.Prisma__UserClient<runtime.Types.Result.GetResult<Prisma.$UserPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions> | Null, Null, ExtArgs, GlobalOmitOptions>
  /**
   * Attaches callbacks for the resolution and/or rejection of the Promise.
   * @param onfulfilled The callback to execute when the Promise is resolved.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of which ever callback is executed.
   */
  then<TResult1 = T, TResult2 = never>(onfulfilled?: ((value: T) => TResult1 | PromiseLike<TResult1>) | undefined | null, onrejected?: ((reason: any) => TResult2 | PromiseLike<TResult2>) | undefined | null): runtime.Types.Utils.JsPromise<TResult1 | TResult2>
  /**
   * Attaches a callback for only the rejection of the Promise.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of the callback.
   */
  catch<TResult = never>(onrejected?: ((reason: any) => TResult | PromiseLike<TResult>) | undefined | null): runtime.Types.Utils.JsPromise<T | TResult>
  /**
   * Attaches a callback that is invoked when the Promise is settled (fulfilled or rejected). The
   * resolved value cannot be modified from the callback.
   * @param onfinally The callback to execute when the Promise is settled (fulfilled or rejected).
   * @returns A Promise for the completion of the callback.
   */
  finally(onfinally?: (() => void) | undefined | null): runtime.Types.Utils.JsPromise<T>
}




/**
 * Fields of the FundContributionLog model
 */
export interface FundContributionLogFieldRefs {
  readonly id: Prisma.FieldRef<"FundContributionLog", 'String'>
  readonly reporterId: Prisma.FieldRef<"FundContributionLog", 'String'>
  readonly contributorId: Prisma.FieldRef<"FundContributionLog", 'String'>
  readonly fundId: Prisma.FieldRef<"FundContributionLog", 'Int'>
  readonly currency: Prisma.FieldRef<"FundContributionLog", 'String'>
  readonly amount: Prisma.FieldRef<"FundContributionLog", 'Float'>
  readonly note: Prisma.FieldRef<"FundContributionLog", 'String'>
  readonly type: Prisma.FieldRef<"FundContributionLog", 'FundTransactionType'>
  readonly createdAt: Prisma.FieldRef<"FundContributionLog", 'DateTime'>
}
    

// Custom InputTypes
/**
 * FundContributionLog findUnique
 */
export type FundContributionLogFindUniqueArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the FundContributionLog
   */
  select?: Prisma.FundContributionLogSelect<ExtArgs> | null
  /**
   * Omit specific fields from the FundContributionLog
   */
  omit?: Prisma.FundContributionLogOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.FundContributionLogInclude<ExtArgs> | null
  /**
   * Filter, which FundContributionLog to fetch.
   */
  where: Prisma.FundContributionLogWhereUniqueInput
}

/**
 * FundContributionLog findUniqueOrThrow
 */
export type FundContributionLogFindUniqueOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the FundContributionLog
   */
  select?: Prisma.FundContributionLogSelect<ExtArgs> | null
  /**
   * Omit specific fields from the FundContributionLog
   */
  omit?: Prisma.FundContributionLogOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.FundContributionLogInclude<ExtArgs> | null
  /**
   * Filter, which FundContributionLog to fetch.
   */
  where: Prisma.FundContributionLogWhereUniqueInput
}

/**
 * FundContributionLog findFirst
 */
export type FundContributionLogFindFirstArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the FundContributionLog
   */
  select?: Prisma.FundContributionLogSelect<ExtArgs> | null
  /**
   * Omit specific fields from the FundContributionLog
   */
  omit?: Prisma.FundContributionLogOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.FundContributionLogInclude<ExtArgs> | null
  /**
   * Filter, which FundContributionLog to fetch.
   */
  where?: Prisma.FundContributionLogWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of FundContributionLogs to fetch.
   */
  orderBy?: Prisma.FundContributionLogOrderByWithRelationInput | Prisma.FundContributionLogOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for FundContributionLogs.
   */
  cursor?: Prisma.FundContributionLogWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` FundContributionLogs from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` FundContributionLogs.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of FundContributionLogs.
   */
  distinct?: Prisma.FundContributionLogScalarFieldEnum | Prisma.FundContributionLogScalarFieldEnum[]
}

/**
 * FundContributionLog findFirstOrThrow
 */
export type FundContributionLogFindFirstOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the FundContributionLog
   */
  select?: Prisma.FundContributionLogSelect<ExtArgs> | null
  /**
   * Omit specific fields from the FundContributionLog
   */
  omit?: Prisma.FundContributionLogOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.FundContributionLogInclude<ExtArgs> | null
  /**
   * Filter, which FundContributionLog to fetch.
   */
  where?: Prisma.FundContributionLogWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of FundContributionLogs to fetch.
   */
  orderBy?: Prisma.FundContributionLogOrderByWithRelationInput | Prisma.FundContributionLogOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for FundContributionLogs.
   */
  cursor?: Prisma.FundContributionLogWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` FundContributionLogs from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` FundContributionLogs.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of FundContributionLogs.
   */
  distinct?: Prisma.FundContributionLogScalarFieldEnum | Prisma.FundContributionLogScalarFieldEnum[]
}

/**
 * FundContributionLog findMany
 */
export type FundContributionLogFindManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the FundContributionLog
   */
  select?: Prisma.FundContributionLogSelect<ExtArgs> | null
  /**
   * Omit specific fields from the FundContributionLog
   */
  omit?: Prisma.FundContributionLogOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.FundContributionLogInclude<ExtArgs> | null
  /**
   * Filter, which FundContributionLogs to fetch.
   */
  where?: Prisma.FundContributionLogWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of FundContributionLogs to fetch.
   */
  orderBy?: Prisma.FundContributionLogOrderByWithRelationInput | Prisma.FundContributionLogOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for listing FundContributionLogs.
   */
  cursor?: Prisma.FundContributionLogWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` FundContributionLogs from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` FundContributionLogs.
   */
  skip?: number
  distinct?: Prisma.FundContributionLogScalarFieldEnum | Prisma.FundContributionLogScalarFieldEnum[]
}

/**
 * FundContributionLog create
 */
export type FundContributionLogCreateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the FundContributionLog
   */
  select?: Prisma.FundContributionLogSelect<ExtArgs> | null
  /**
   * Omit specific fields from the FundContributionLog
   */
  omit?: Prisma.FundContributionLogOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.FundContributionLogInclude<ExtArgs> | null
  /**
   * The data needed to create a FundContributionLog.
   */
  data: Prisma.XOR<Prisma.FundContributionLogCreateInput, Prisma.FundContributionLogUncheckedCreateInput>
}

/**
 * FundContributionLog createMany
 */
export type FundContributionLogCreateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to create many FundContributionLogs.
   */
  data: Prisma.FundContributionLogCreateManyInput | Prisma.FundContributionLogCreateManyInput[]
}

/**
 * FundContributionLog createManyAndReturn
 */
export type FundContributionLogCreateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the FundContributionLog
   */
  select?: Prisma.FundContributionLogSelectCreateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the FundContributionLog
   */
  omit?: Prisma.FundContributionLogOmit<ExtArgs> | null
  /**
   * The data used to create many FundContributionLogs.
   */
  data: Prisma.FundContributionLogCreateManyInput | Prisma.FundContributionLogCreateManyInput[]
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.FundContributionLogIncludeCreateManyAndReturn<ExtArgs> | null
}

/**
 * FundContributionLog update
 */
export type FundContributionLogUpdateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the FundContributionLog
   */
  select?: Prisma.FundContributionLogSelect<ExtArgs> | null
  /**
   * Omit specific fields from the FundContributionLog
   */
  omit?: Prisma.FundContributionLogOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.FundContributionLogInclude<ExtArgs> | null
  /**
   * The data needed to update a FundContributionLog.
   */
  data: Prisma.XOR<Prisma.FundContributionLogUpdateInput, Prisma.FundContributionLogUncheckedUpdateInput>
  /**
   * Choose, which FundContributionLog to update.
   */
  where: Prisma.FundContributionLogWhereUniqueInput
}

/**
 * FundContributionLog updateMany
 */
export type FundContributionLogUpdateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to update FundContributionLogs.
   */
  data: Prisma.XOR<Prisma.FundContributionLogUpdateManyMutationInput, Prisma.FundContributionLogUncheckedUpdateManyInput>
  /**
   * Filter which FundContributionLogs to update
   */
  where?: Prisma.FundContributionLogWhereInput
  /**
   * Limit how many FundContributionLogs to update.
   */
  limit?: number
}

/**
 * FundContributionLog updateManyAndReturn
 */
export type FundContributionLogUpdateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the FundContributionLog
   */
  select?: Prisma.FundContributionLogSelectUpdateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the FundContributionLog
   */
  omit?: Prisma.FundContributionLogOmit<ExtArgs> | null
  /**
   * The data used to update FundContributionLogs.
   */
  data: Prisma.XOR<Prisma.FundContributionLogUpdateManyMutationInput, Prisma.FundContributionLogUncheckedUpdateManyInput>
  /**
   * Filter which FundContributionLogs to update
   */
  where?: Prisma.FundContributionLogWhereInput
  /**
   * Limit how many FundContributionLogs to update.
   */
  limit?: number
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.FundContributionLogIncludeUpdateManyAndReturn<ExtArgs> | null
}

/**
 * FundContributionLog upsert
 */
export type FundContributionLogUpsertArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the FundContributionLog
   */
  select?: Prisma.FundContributionLogSelect<ExtArgs> | null
  /**
   * Omit specific fields from the FundContributionLog
   */
  omit?: Prisma.FundContributionLogOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.FundContributionLogInclude<ExtArgs> | null
  /**
   * The filter to search for the FundContributionLog to update in case it exists.
   */
  where: Prisma.FundContributionLogWhereUniqueInput
  /**
   * In case the FundContributionLog found by the `where` argument doesn't exist, create a new FundContributionLog with this data.
   */
  create: Prisma.XOR<Prisma.FundContributionLogCreateInput, Prisma.FundContributionLogUncheckedCreateInput>
  /**
   * In case the FundContributionLog was found with the provided `where` argument, update it with this data.
   */
  update: Prisma.XOR<Prisma.FundContributionLogUpdateInput, Prisma.FundContributionLogUncheckedUpdateInput>
}

/**
 * FundContributionLog delete
 */
export type FundContributionLogDeleteArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the FundContributionLog
   */
  select?: Prisma.FundContributionLogSelect<ExtArgs> | null
  /**
   * Omit specific fields from the FundContributionLog
   */
  omit?: Prisma.FundContributionLogOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.FundContributionLogInclude<ExtArgs> | null
  /**
   * Filter which FundContributionLog to delete.
   */
  where: Prisma.FundContributionLogWhereUniqueInput
}

/**
 * FundContributionLog deleteMany
 */
export type FundContributionLogDeleteManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which FundContributionLogs to delete
   */
  where?: Prisma.FundContributionLogWhereInput
  /**
   * Limit how many FundContributionLogs to delete.
   */
  limit?: number
}

/**
 * FundContributionLog without action
 */
export type FundContributionLogDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the FundContributionLog
   */
  select?: Prisma.FundContributionLogSelect<ExtArgs> | null
  /**
   * Omit specific fields from the FundContributionLog
   */
  omit?: Prisma.FundContributionLogOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.FundContributionLogInclude<ExtArgs> | null
}
