/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
 * This file exports the `GalleryPost` model and its related types.
 *
 * 🟢 You can import this file directly.
 */
import type * as runtime from "@prisma/client/runtime/client"
import type * as $Enums from "../enums.js"
import type * as Prisma from "../internal/prismaNamespace.js"

/**
 * Model GalleryPost
 * 
 */
export type GalleryPostModel = runtime.Types.Result.DefaultSelection<Prisma.$GalleryPostPayload>

export type AggregateGalleryPost = {
  _count: GalleryPostCountAggregateOutputType | null
  _min: GalleryPostMinAggregateOutputType | null
  _max: GalleryPostMaxAggregateOutputType | null
}

export type GalleryPostMinAggregateOutputType = {
  id: string | null
  userId: string | null
  mediaKey: string | null
  type: $Enums.MediaType | null
  createdAt: Date | null
}

export type GalleryPostMaxAggregateOutputType = {
  id: string | null
  userId: string | null
  mediaKey: string | null
  type: $Enums.MediaType | null
  createdAt: Date | null
}

export type GalleryPostCountAggregateOutputType = {
  id: number
  userId: number
  mediaKey: number
  type: number
  createdAt: number
  _all: number
}


export type GalleryPostMinAggregateInputType = {
  id?: true
  userId?: true
  mediaKey?: true
  type?: true
  createdAt?: true
}

export type GalleryPostMaxAggregateInputType = {
  id?: true
  userId?: true
  mediaKey?: true
  type?: true
  createdAt?: true
}

export type GalleryPostCountAggregateInputType = {
  id?: true
  userId?: true
  mediaKey?: true
  type?: true
  createdAt?: true
  _all?: true
}

export type GalleryPostAggregateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which GalleryPost to aggregate.
   */
  where?: Prisma.GalleryPostWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of GalleryPosts to fetch.
   */
  orderBy?: Prisma.GalleryPostOrderByWithRelationInput | Prisma.GalleryPostOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the start position
   */
  cursor?: Prisma.GalleryPostWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` GalleryPosts from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` GalleryPosts.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Count returned GalleryPosts
  **/
  _count?: true | GalleryPostCountAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the minimum value
  **/
  _min?: GalleryPostMinAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the maximum value
  **/
  _max?: GalleryPostMaxAggregateInputType
}

export type GetGalleryPostAggregateType<T extends GalleryPostAggregateArgs> = {
      [P in keyof T & keyof AggregateGalleryPost]: P extends '_count' | 'count'
    ? T[P] extends true
      ? number
      : Prisma.GetScalarType<T[P], AggregateGalleryPost[P]>
    : Prisma.GetScalarType<T[P], AggregateGalleryPost[P]>
}




export type GalleryPostGroupByArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.GalleryPostWhereInput
  orderBy?: Prisma.GalleryPostOrderByWithAggregationInput | Prisma.GalleryPostOrderByWithAggregationInput[]
  by: Prisma.GalleryPostScalarFieldEnum[] | Prisma.GalleryPostScalarFieldEnum
  having?: Prisma.GalleryPostScalarWhereWithAggregatesInput
  take?: number
  skip?: number
  _count?: GalleryPostCountAggregateInputType | true
  _min?: GalleryPostMinAggregateInputType
  _max?: GalleryPostMaxAggregateInputType
}

export type GalleryPostGroupByOutputType = {
  id: string
  userId: string
  mediaKey: string
  type: $Enums.MediaType
  createdAt: Date
  _count: GalleryPostCountAggregateOutputType | null
  _min: GalleryPostMinAggregateOutputType | null
  _max: GalleryPostMaxAggregateOutputType | null
}

type GetGalleryPostGroupByPayload<T extends GalleryPostGroupByArgs> = Prisma.PrismaPromise<
  Array<
    Prisma.PickEnumerable<GalleryPostGroupByOutputType, T['by']> &
      {
        [P in ((keyof T) & (keyof GalleryPostGroupByOutputType))]: P extends '_count'
          ? T[P] extends boolean
            ? number
            : Prisma.GetScalarType<T[P], GalleryPostGroupByOutputType[P]>
          : Prisma.GetScalarType<T[P], GalleryPostGroupByOutputType[P]>
      }
    >
  >



export type GalleryPostWhereInput = {
  AND?: Prisma.GalleryPostWhereInput | Prisma.GalleryPostWhereInput[]
  OR?: Prisma.GalleryPostWhereInput[]
  NOT?: Prisma.GalleryPostWhereInput | Prisma.GalleryPostWhereInput[]
  id?: Prisma.StringFilter<"GalleryPost"> | string
  userId?: Prisma.StringFilter<"GalleryPost"> | string
  mediaKey?: Prisma.StringFilter<"GalleryPost"> | string
  type?: Prisma.EnumMediaTypeFilter<"GalleryPost"> | $Enums.MediaType
  createdAt?: Prisma.DateTimeFilter<"GalleryPost"> | Date | string
  createdBy?: Prisma.XOR<Prisma.UserScalarRelationFilter, Prisma.UserWhereInput>
  reactions?: Prisma.GalleryPostReactionListRelationFilter
}

export type GalleryPostOrderByWithRelationInput = {
  id?: Prisma.SortOrder
  userId?: Prisma.SortOrder
  mediaKey?: Prisma.SortOrder
  type?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  createdBy?: Prisma.UserOrderByWithRelationInput
  reactions?: Prisma.GalleryPostReactionOrderByRelationAggregateInput
}

export type GalleryPostWhereUniqueInput = Prisma.AtLeast<{
  id?: string
  mediaKey?: string
  AND?: Prisma.GalleryPostWhereInput | Prisma.GalleryPostWhereInput[]
  OR?: Prisma.GalleryPostWhereInput[]
  NOT?: Prisma.GalleryPostWhereInput | Prisma.GalleryPostWhereInput[]
  userId?: Prisma.StringFilter<"GalleryPost"> | string
  type?: Prisma.EnumMediaTypeFilter<"GalleryPost"> | $Enums.MediaType
  createdAt?: Prisma.DateTimeFilter<"GalleryPost"> | Date | string
  createdBy?: Prisma.XOR<Prisma.UserScalarRelationFilter, Prisma.UserWhereInput>
  reactions?: Prisma.GalleryPostReactionListRelationFilter
}, "id" | "mediaKey">

export type GalleryPostOrderByWithAggregationInput = {
  id?: Prisma.SortOrder
  userId?: Prisma.SortOrder
  mediaKey?: Prisma.SortOrder
  type?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  _count?: Prisma.GalleryPostCountOrderByAggregateInput
  _max?: Prisma.GalleryPostMaxOrderByAggregateInput
  _min?: Prisma.GalleryPostMinOrderByAggregateInput
}

export type GalleryPostScalarWhereWithAggregatesInput = {
  AND?: Prisma.GalleryPostScalarWhereWithAggregatesInput | Prisma.GalleryPostScalarWhereWithAggregatesInput[]
  OR?: Prisma.GalleryPostScalarWhereWithAggregatesInput[]
  NOT?: Prisma.GalleryPostScalarWhereWithAggregatesInput | Prisma.GalleryPostScalarWhereWithAggregatesInput[]
  id?: Prisma.StringWithAggregatesFilter<"GalleryPost"> | string
  userId?: Prisma.StringWithAggregatesFilter<"GalleryPost"> | string
  mediaKey?: Prisma.StringWithAggregatesFilter<"GalleryPost"> | string
  type?: Prisma.EnumMediaTypeWithAggregatesFilter<"GalleryPost"> | $Enums.MediaType
  createdAt?: Prisma.DateTimeWithAggregatesFilter<"GalleryPost"> | Date | string
}

export type GalleryPostCreateInput = {
  id?: string
  mediaKey: string
  type: $Enums.MediaType
  createdAt?: Date | string
  createdBy: Prisma.UserCreateNestedOneWithoutGalleryPostsInput
  reactions?: Prisma.GalleryPostReactionCreateNestedManyWithoutPostInput
}

export type GalleryPostUncheckedCreateInput = {
  id?: string
  userId: string
  mediaKey: string
  type: $Enums.MediaType
  createdAt?: Date | string
  reactions?: Prisma.GalleryPostReactionUncheckedCreateNestedManyWithoutPostInput
}

export type GalleryPostUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  mediaKey?: Prisma.StringFieldUpdateOperationsInput | string
  type?: Prisma.EnumMediaTypeFieldUpdateOperationsInput | $Enums.MediaType
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  createdBy?: Prisma.UserUpdateOneRequiredWithoutGalleryPostsNestedInput
  reactions?: Prisma.GalleryPostReactionUpdateManyWithoutPostNestedInput
}

export type GalleryPostUncheckedUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  userId?: Prisma.StringFieldUpdateOperationsInput | string
  mediaKey?: Prisma.StringFieldUpdateOperationsInput | string
  type?: Prisma.EnumMediaTypeFieldUpdateOperationsInput | $Enums.MediaType
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  reactions?: Prisma.GalleryPostReactionUncheckedUpdateManyWithoutPostNestedInput
}

export type GalleryPostCreateManyInput = {
  id?: string
  userId: string
  mediaKey: string
  type: $Enums.MediaType
  createdAt?: Date | string
}

export type GalleryPostUpdateManyMutationInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  mediaKey?: Prisma.StringFieldUpdateOperationsInput | string
  type?: Prisma.EnumMediaTypeFieldUpdateOperationsInput | $Enums.MediaType
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type GalleryPostUncheckedUpdateManyInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  userId?: Prisma.StringFieldUpdateOperationsInput | string
  mediaKey?: Prisma.StringFieldUpdateOperationsInput | string
  type?: Prisma.EnumMediaTypeFieldUpdateOperationsInput | $Enums.MediaType
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type GalleryPostListRelationFilter = {
  every?: Prisma.GalleryPostWhereInput
  some?: Prisma.GalleryPostWhereInput
  none?: Prisma.GalleryPostWhereInput
}

export type GalleryPostOrderByRelationAggregateInput = {
  _count?: Prisma.SortOrder
}

export type GalleryPostCountOrderByAggregateInput = {
  id?: Prisma.SortOrder
  userId?: Prisma.SortOrder
  mediaKey?: Prisma.SortOrder
  type?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
}

export type GalleryPostMaxOrderByAggregateInput = {
  id?: Prisma.SortOrder
  userId?: Prisma.SortOrder
  mediaKey?: Prisma.SortOrder
  type?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
}

export type GalleryPostMinOrderByAggregateInput = {
  id?: Prisma.SortOrder
  userId?: Prisma.SortOrder
  mediaKey?: Prisma.SortOrder
  type?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
}

export type GalleryPostScalarRelationFilter = {
  is?: Prisma.GalleryPostWhereInput
  isNot?: Prisma.GalleryPostWhereInput
}

export type GalleryPostCreateNestedManyWithoutCreatedByInput = {
  create?: Prisma.XOR<Prisma.GalleryPostCreateWithoutCreatedByInput, Prisma.GalleryPostUncheckedCreateWithoutCreatedByInput> | Prisma.GalleryPostCreateWithoutCreatedByInput[] | Prisma.GalleryPostUncheckedCreateWithoutCreatedByInput[]
  connectOrCreate?: Prisma.GalleryPostCreateOrConnectWithoutCreatedByInput | Prisma.GalleryPostCreateOrConnectWithoutCreatedByInput[]
  createMany?: Prisma.GalleryPostCreateManyCreatedByInputEnvelope
  connect?: Prisma.GalleryPostWhereUniqueInput | Prisma.GalleryPostWhereUniqueInput[]
}

export type GalleryPostUncheckedCreateNestedManyWithoutCreatedByInput = {
  create?: Prisma.XOR<Prisma.GalleryPostCreateWithoutCreatedByInput, Prisma.GalleryPostUncheckedCreateWithoutCreatedByInput> | Prisma.GalleryPostCreateWithoutCreatedByInput[] | Prisma.GalleryPostUncheckedCreateWithoutCreatedByInput[]
  connectOrCreate?: Prisma.GalleryPostCreateOrConnectWithoutCreatedByInput | Prisma.GalleryPostCreateOrConnectWithoutCreatedByInput[]
  createMany?: Prisma.GalleryPostCreateManyCreatedByInputEnvelope
  connect?: Prisma.GalleryPostWhereUniqueInput | Prisma.GalleryPostWhereUniqueInput[]
}

export type GalleryPostUpdateManyWithoutCreatedByNestedInput = {
  create?: Prisma.XOR<Prisma.GalleryPostCreateWithoutCreatedByInput, Prisma.GalleryPostUncheckedCreateWithoutCreatedByInput> | Prisma.GalleryPostCreateWithoutCreatedByInput[] | Prisma.GalleryPostUncheckedCreateWithoutCreatedByInput[]
  connectOrCreate?: Prisma.GalleryPostCreateOrConnectWithoutCreatedByInput | Prisma.GalleryPostCreateOrConnectWithoutCreatedByInput[]
  upsert?: Prisma.GalleryPostUpsertWithWhereUniqueWithoutCreatedByInput | Prisma.GalleryPostUpsertWithWhereUniqueWithoutCreatedByInput[]
  createMany?: Prisma.GalleryPostCreateManyCreatedByInputEnvelope
  set?: Prisma.GalleryPostWhereUniqueInput | Prisma.GalleryPostWhereUniqueInput[]
  disconnect?: Prisma.GalleryPostWhereUniqueInput | Prisma.GalleryPostWhereUniqueInput[]
  delete?: Prisma.GalleryPostWhereUniqueInput | Prisma.GalleryPostWhereUniqueInput[]
  connect?: Prisma.GalleryPostWhereUniqueInput | Prisma.GalleryPostWhereUniqueInput[]
  update?: Prisma.GalleryPostUpdateWithWhereUniqueWithoutCreatedByInput | Prisma.GalleryPostUpdateWithWhereUniqueWithoutCreatedByInput[]
  updateMany?: Prisma.GalleryPostUpdateManyWithWhereWithoutCreatedByInput | Prisma.GalleryPostUpdateManyWithWhereWithoutCreatedByInput[]
  deleteMany?: Prisma.GalleryPostScalarWhereInput | Prisma.GalleryPostScalarWhereInput[]
}

export type GalleryPostUncheckedUpdateManyWithoutCreatedByNestedInput = {
  create?: Prisma.XOR<Prisma.GalleryPostCreateWithoutCreatedByInput, Prisma.GalleryPostUncheckedCreateWithoutCreatedByInput> | Prisma.GalleryPostCreateWithoutCreatedByInput[] | Prisma.GalleryPostUncheckedCreateWithoutCreatedByInput[]
  connectOrCreate?: Prisma.GalleryPostCreateOrConnectWithoutCreatedByInput | Prisma.GalleryPostCreateOrConnectWithoutCreatedByInput[]
  upsert?: Prisma.GalleryPostUpsertWithWhereUniqueWithoutCreatedByInput | Prisma.GalleryPostUpsertWithWhereUniqueWithoutCreatedByInput[]
  createMany?: Prisma.GalleryPostCreateManyCreatedByInputEnvelope
  set?: Prisma.GalleryPostWhereUniqueInput | Prisma.GalleryPostWhereUniqueInput[]
  disconnect?: Prisma.GalleryPostWhereUniqueInput | Prisma.GalleryPostWhereUniqueInput[]
  delete?: Prisma.GalleryPostWhereUniqueInput | Prisma.GalleryPostWhereUniqueInput[]
  connect?: Prisma.GalleryPostWhereUniqueInput | Prisma.GalleryPostWhereUniqueInput[]
  update?: Prisma.GalleryPostUpdateWithWhereUniqueWithoutCreatedByInput | Prisma.GalleryPostUpdateWithWhereUniqueWithoutCreatedByInput[]
  updateMany?: Prisma.GalleryPostUpdateManyWithWhereWithoutCreatedByInput | Prisma.GalleryPostUpdateManyWithWhereWithoutCreatedByInput[]
  deleteMany?: Prisma.GalleryPostScalarWhereInput | Prisma.GalleryPostScalarWhereInput[]
}

export type EnumMediaTypeFieldUpdateOperationsInput = {
  set?: $Enums.MediaType
}

export type GalleryPostCreateNestedOneWithoutReactionsInput = {
  create?: Prisma.XOR<Prisma.GalleryPostCreateWithoutReactionsInput, Prisma.GalleryPostUncheckedCreateWithoutReactionsInput>
  connectOrCreate?: Prisma.GalleryPostCreateOrConnectWithoutReactionsInput
  connect?: Prisma.GalleryPostWhereUniqueInput
}

export type GalleryPostUpdateOneRequiredWithoutReactionsNestedInput = {
  create?: Prisma.XOR<Prisma.GalleryPostCreateWithoutReactionsInput, Prisma.GalleryPostUncheckedCreateWithoutReactionsInput>
  connectOrCreate?: Prisma.GalleryPostCreateOrConnectWithoutReactionsInput
  upsert?: Prisma.GalleryPostUpsertWithoutReactionsInput
  connect?: Prisma.GalleryPostWhereUniqueInput
  update?: Prisma.XOR<Prisma.XOR<Prisma.GalleryPostUpdateToOneWithWhereWithoutReactionsInput, Prisma.GalleryPostUpdateWithoutReactionsInput>, Prisma.GalleryPostUncheckedUpdateWithoutReactionsInput>
}

export type GalleryPostCreateWithoutCreatedByInput = {
  id?: string
  mediaKey: string
  type: $Enums.MediaType
  createdAt?: Date | string
  reactions?: Prisma.GalleryPostReactionCreateNestedManyWithoutPostInput
}

export type GalleryPostUncheckedCreateWithoutCreatedByInput = {
  id?: string
  mediaKey: string
  type: $Enums.MediaType
  createdAt?: Date | string
  reactions?: Prisma.GalleryPostReactionUncheckedCreateNestedManyWithoutPostInput
}

export type GalleryPostCreateOrConnectWithoutCreatedByInput = {
  where: Prisma.GalleryPostWhereUniqueInput
  create: Prisma.XOR<Prisma.GalleryPostCreateWithoutCreatedByInput, Prisma.GalleryPostUncheckedCreateWithoutCreatedByInput>
}

export type GalleryPostCreateManyCreatedByInputEnvelope = {
  data: Prisma.GalleryPostCreateManyCreatedByInput | Prisma.GalleryPostCreateManyCreatedByInput[]
}

export type GalleryPostUpsertWithWhereUniqueWithoutCreatedByInput = {
  where: Prisma.GalleryPostWhereUniqueInput
  update: Prisma.XOR<Prisma.GalleryPostUpdateWithoutCreatedByInput, Prisma.GalleryPostUncheckedUpdateWithoutCreatedByInput>
  create: Prisma.XOR<Prisma.GalleryPostCreateWithoutCreatedByInput, Prisma.GalleryPostUncheckedCreateWithoutCreatedByInput>
}

export type GalleryPostUpdateWithWhereUniqueWithoutCreatedByInput = {
  where: Prisma.GalleryPostWhereUniqueInput
  data: Prisma.XOR<Prisma.GalleryPostUpdateWithoutCreatedByInput, Prisma.GalleryPostUncheckedUpdateWithoutCreatedByInput>
}

export type GalleryPostUpdateManyWithWhereWithoutCreatedByInput = {
  where: Prisma.GalleryPostScalarWhereInput
  data: Prisma.XOR<Prisma.GalleryPostUpdateManyMutationInput, Prisma.GalleryPostUncheckedUpdateManyWithoutCreatedByInput>
}

export type GalleryPostScalarWhereInput = {
  AND?: Prisma.GalleryPostScalarWhereInput | Prisma.GalleryPostScalarWhereInput[]
  OR?: Prisma.GalleryPostScalarWhereInput[]
  NOT?: Prisma.GalleryPostScalarWhereInput | Prisma.GalleryPostScalarWhereInput[]
  id?: Prisma.StringFilter<"GalleryPost"> | string
  userId?: Prisma.StringFilter<"GalleryPost"> | string
  mediaKey?: Prisma.StringFilter<"GalleryPost"> | string
  type?: Prisma.EnumMediaTypeFilter<"GalleryPost"> | $Enums.MediaType
  createdAt?: Prisma.DateTimeFilter<"GalleryPost"> | Date | string
}

export type GalleryPostCreateWithoutReactionsInput = {
  id?: string
  mediaKey: string
  type: $Enums.MediaType
  createdAt?: Date | string
  createdBy: Prisma.UserCreateNestedOneWithoutGalleryPostsInput
}

export type GalleryPostUncheckedCreateWithoutReactionsInput = {
  id?: string
  userId: string
  mediaKey: string
  type: $Enums.MediaType
  createdAt?: Date | string
}

export type GalleryPostCreateOrConnectWithoutReactionsInput = {
  where: Prisma.GalleryPostWhereUniqueInput
  create: Prisma.XOR<Prisma.GalleryPostCreateWithoutReactionsInput, Prisma.GalleryPostUncheckedCreateWithoutReactionsInput>
}

export type GalleryPostUpsertWithoutReactionsInput = {
  update: Prisma.XOR<Prisma.GalleryPostUpdateWithoutReactionsInput, Prisma.GalleryPostUncheckedUpdateWithoutReactionsInput>
  create: Prisma.XOR<Prisma.GalleryPostCreateWithoutReactionsInput, Prisma.GalleryPostUncheckedCreateWithoutReactionsInput>
  where?: Prisma.GalleryPostWhereInput
}

export type GalleryPostUpdateToOneWithWhereWithoutReactionsInput = {
  where?: Prisma.GalleryPostWhereInput
  data: Prisma.XOR<Prisma.GalleryPostUpdateWithoutReactionsInput, Prisma.GalleryPostUncheckedUpdateWithoutReactionsInput>
}

export type GalleryPostUpdateWithoutReactionsInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  mediaKey?: Prisma.StringFieldUpdateOperationsInput | string
  type?: Prisma.EnumMediaTypeFieldUpdateOperationsInput | $Enums.MediaType
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  createdBy?: Prisma.UserUpdateOneRequiredWithoutGalleryPostsNestedInput
}

export type GalleryPostUncheckedUpdateWithoutReactionsInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  userId?: Prisma.StringFieldUpdateOperationsInput | string
  mediaKey?: Prisma.StringFieldUpdateOperationsInput | string
  type?: Prisma.EnumMediaTypeFieldUpdateOperationsInput | $Enums.MediaType
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type GalleryPostCreateManyCreatedByInput = {
  id?: string
  mediaKey: string
  type: $Enums.MediaType
  createdAt?: Date | string
}

export type GalleryPostUpdateWithoutCreatedByInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  mediaKey?: Prisma.StringFieldUpdateOperationsInput | string
  type?: Prisma.EnumMediaTypeFieldUpdateOperationsInput | $Enums.MediaType
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  reactions?: Prisma.GalleryPostReactionUpdateManyWithoutPostNestedInput
}

export type GalleryPostUncheckedUpdateWithoutCreatedByInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  mediaKey?: Prisma.StringFieldUpdateOperationsInput | string
  type?: Prisma.EnumMediaTypeFieldUpdateOperationsInput | $Enums.MediaType
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  reactions?: Prisma.GalleryPostReactionUncheckedUpdateManyWithoutPostNestedInput
}

export type GalleryPostUncheckedUpdateManyWithoutCreatedByInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  mediaKey?: Prisma.StringFieldUpdateOperationsInput | string
  type?: Prisma.EnumMediaTypeFieldUpdateOperationsInput | $Enums.MediaType
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}


/**
 * Count Type GalleryPostCountOutputType
 */

export type GalleryPostCountOutputType = {
  reactions: number
}

export type GalleryPostCountOutputTypeSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  reactions?: boolean | GalleryPostCountOutputTypeCountReactionsArgs
}

/**
 * GalleryPostCountOutputType without action
 */
export type GalleryPostCountOutputTypeDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the GalleryPostCountOutputType
   */
  select?: Prisma.GalleryPostCountOutputTypeSelect<ExtArgs> | null
}

/**
 * GalleryPostCountOutputType without action
 */
export type GalleryPostCountOutputTypeCountReactionsArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.GalleryPostReactionWhereInput
}


export type GalleryPostSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  userId?: boolean
  mediaKey?: boolean
  type?: boolean
  createdAt?: boolean
  createdBy?: boolean | Prisma.UserDefaultArgs<ExtArgs>
  reactions?: boolean | Prisma.GalleryPost$reactionsArgs<ExtArgs>
  _count?: boolean | Prisma.GalleryPostCountOutputTypeDefaultArgs<ExtArgs>
}, ExtArgs["result"]["galleryPost"]>

export type GalleryPostSelectCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  userId?: boolean
  mediaKey?: boolean
  type?: boolean
  createdAt?: boolean
  createdBy?: boolean | Prisma.UserDefaultArgs<ExtArgs>
}, ExtArgs["result"]["galleryPost"]>

export type GalleryPostSelectUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  userId?: boolean
  mediaKey?: boolean
  type?: boolean
  createdAt?: boolean
  createdBy?: boolean | Prisma.UserDefaultArgs<ExtArgs>
}, ExtArgs["result"]["galleryPost"]>

export type GalleryPostSelectScalar = {
  id?: boolean
  userId?: boolean
  mediaKey?: boolean
  type?: boolean
  createdAt?: boolean
}

export type GalleryPostOmit<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetOmit<"id" | "userId" | "mediaKey" | "type" | "createdAt", ExtArgs["result"]["galleryPost"]>
export type GalleryPostInclude<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  createdBy?: boolean | Prisma.UserDefaultArgs<ExtArgs>
  reactions?: boolean | Prisma.GalleryPost$reactionsArgs<ExtArgs>
  _count?: boolean | Prisma.GalleryPostCountOutputTypeDefaultArgs<ExtArgs>
}
export type GalleryPostIncludeCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  createdBy?: boolean | Prisma.UserDefaultArgs<ExtArgs>
}
export type GalleryPostIncludeUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  createdBy?: boolean | Prisma.UserDefaultArgs<ExtArgs>
}

export type $GalleryPostPayload<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  name: "GalleryPost"
  objects: {
    createdBy: Prisma.$UserPayload<ExtArgs>
    reactions: Prisma.$GalleryPostReactionPayload<ExtArgs>[]
  }
  scalars: runtime.Types.Extensions.GetPayloadResult<{
    id: string
    userId: string
    mediaKey: string
    type: $Enums.MediaType
    createdAt: Date
  }, ExtArgs["result"]["galleryPost"]>
  composites: {}
}

export type GalleryPostGetPayload<S extends boolean | null | undefined | GalleryPostDefaultArgs> = runtime.Types.Result.GetResult<Prisma.$GalleryPostPayload, S>

export type GalleryPostCountArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> =
  Omit<GalleryPostFindManyArgs, 'select' | 'include' | 'distinct' | 'omit'> & {
    select?: GalleryPostCountAggregateInputType | true
  }

export interface GalleryPostDelegate<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> {
  [K: symbol]: { types: Prisma.TypeMap<ExtArgs>['model']['GalleryPost'], meta: { name: 'GalleryPost' } }
  /**
   * Find zero or one GalleryPost that matches the filter.
   * @param {GalleryPostFindUniqueArgs} args - Arguments to find a GalleryPost
   * @example
   * // Get one GalleryPost
   * const galleryPost = await prisma.galleryPost.findUnique({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUnique<T extends GalleryPostFindUniqueArgs>(args: Prisma.SelectSubset<T, GalleryPostFindUniqueArgs<ExtArgs>>): Prisma.Prisma__GalleryPostClient<runtime.Types.Result.GetResult<Prisma.$GalleryPostPayload<ExtArgs>, T, "findUnique", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find one GalleryPost that matches the filter or throw an error with `error.code='P2025'`
   * if no matches were found.
   * @param {GalleryPostFindUniqueOrThrowArgs} args - Arguments to find a GalleryPost
   * @example
   * // Get one GalleryPost
   * const galleryPost = await prisma.galleryPost.findUniqueOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUniqueOrThrow<T extends GalleryPostFindUniqueOrThrowArgs>(args: Prisma.SelectSubset<T, GalleryPostFindUniqueOrThrowArgs<ExtArgs>>): Prisma.Prisma__GalleryPostClient<runtime.Types.Result.GetResult<Prisma.$GalleryPostPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first GalleryPost that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {GalleryPostFindFirstArgs} args - Arguments to find a GalleryPost
   * @example
   * // Get one GalleryPost
   * const galleryPost = await prisma.galleryPost.findFirst({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirst<T extends GalleryPostFindFirstArgs>(args?: Prisma.SelectSubset<T, GalleryPostFindFirstArgs<ExtArgs>>): Prisma.Prisma__GalleryPostClient<runtime.Types.Result.GetResult<Prisma.$GalleryPostPayload<ExtArgs>, T, "findFirst", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first GalleryPost that matches the filter or
   * throw `PrismaKnownClientError` with `P2025` code if no matches were found.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {GalleryPostFindFirstOrThrowArgs} args - Arguments to find a GalleryPost
   * @example
   * // Get one GalleryPost
   * const galleryPost = await prisma.galleryPost.findFirstOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirstOrThrow<T extends GalleryPostFindFirstOrThrowArgs>(args?: Prisma.SelectSubset<T, GalleryPostFindFirstOrThrowArgs<ExtArgs>>): Prisma.Prisma__GalleryPostClient<runtime.Types.Result.GetResult<Prisma.$GalleryPostPayload<ExtArgs>, T, "findFirstOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find zero or more GalleryPosts that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {GalleryPostFindManyArgs} args - Arguments to filter and select certain fields only.
   * @example
   * // Get all GalleryPosts
   * const galleryPosts = await prisma.galleryPost.findMany()
   * 
   * // Get first 10 GalleryPosts
   * const galleryPosts = await prisma.galleryPost.findMany({ take: 10 })
   * 
   * // Only select the `id`
   * const galleryPostWithIdOnly = await prisma.galleryPost.findMany({ select: { id: true } })
   * 
   */
  findMany<T extends GalleryPostFindManyArgs>(args?: Prisma.SelectSubset<T, GalleryPostFindManyArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$GalleryPostPayload<ExtArgs>, T, "findMany", GlobalOmitOptions>>

  /**
   * Create a GalleryPost.
   * @param {GalleryPostCreateArgs} args - Arguments to create a GalleryPost.
   * @example
   * // Create one GalleryPost
   * const GalleryPost = await prisma.galleryPost.create({
   *   data: {
   *     // ... data to create a GalleryPost
   *   }
   * })
   * 
   */
  create<T extends GalleryPostCreateArgs>(args: Prisma.SelectSubset<T, GalleryPostCreateArgs<ExtArgs>>): Prisma.Prisma__GalleryPostClient<runtime.Types.Result.GetResult<Prisma.$GalleryPostPayload<ExtArgs>, T, "create", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Create many GalleryPosts.
   * @param {GalleryPostCreateManyArgs} args - Arguments to create many GalleryPosts.
   * @example
   * // Create many GalleryPosts
   * const galleryPost = await prisma.galleryPost.createMany({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   *     
   */
  createMany<T extends GalleryPostCreateManyArgs>(args?: Prisma.SelectSubset<T, GalleryPostCreateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Create many GalleryPosts and returns the data saved in the database.
   * @param {GalleryPostCreateManyAndReturnArgs} args - Arguments to create many GalleryPosts.
   * @example
   * // Create many GalleryPosts
   * const galleryPost = await prisma.galleryPost.createManyAndReturn({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Create many GalleryPosts and only return the `id`
   * const galleryPostWithIdOnly = await prisma.galleryPost.createManyAndReturn({
   *   select: { id: true },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  createManyAndReturn<T extends GalleryPostCreateManyAndReturnArgs>(args?: Prisma.SelectSubset<T, GalleryPostCreateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$GalleryPostPayload<ExtArgs>, T, "createManyAndReturn", GlobalOmitOptions>>

  /**
   * Delete a GalleryPost.
   * @param {GalleryPostDeleteArgs} args - Arguments to delete one GalleryPost.
   * @example
   * // Delete one GalleryPost
   * const GalleryPost = await prisma.galleryPost.delete({
   *   where: {
   *     // ... filter to delete one GalleryPost
   *   }
   * })
   * 
   */
  delete<T extends GalleryPostDeleteArgs>(args: Prisma.SelectSubset<T, GalleryPostDeleteArgs<ExtArgs>>): Prisma.Prisma__GalleryPostClient<runtime.Types.Result.GetResult<Prisma.$GalleryPostPayload<ExtArgs>, T, "delete", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Update one GalleryPost.
   * @param {GalleryPostUpdateArgs} args - Arguments to update one GalleryPost.
   * @example
   * // Update one GalleryPost
   * const galleryPost = await prisma.galleryPost.update({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  update<T extends GalleryPostUpdateArgs>(args: Prisma.SelectSubset<T, GalleryPostUpdateArgs<ExtArgs>>): Prisma.Prisma__GalleryPostClient<runtime.Types.Result.GetResult<Prisma.$GalleryPostPayload<ExtArgs>, T, "update", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Delete zero or more GalleryPosts.
   * @param {GalleryPostDeleteManyArgs} args - Arguments to filter GalleryPosts to delete.
   * @example
   * // Delete a few GalleryPosts
   * const { count } = await prisma.galleryPost.deleteMany({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   * 
   */
  deleteMany<T extends GalleryPostDeleteManyArgs>(args?: Prisma.SelectSubset<T, GalleryPostDeleteManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more GalleryPosts.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {GalleryPostUpdateManyArgs} args - Arguments to update one or more rows.
   * @example
   * // Update many GalleryPosts
   * const galleryPost = await prisma.galleryPost.updateMany({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  updateMany<T extends GalleryPostUpdateManyArgs>(args: Prisma.SelectSubset<T, GalleryPostUpdateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more GalleryPosts and returns the data updated in the database.
   * @param {GalleryPostUpdateManyAndReturnArgs} args - Arguments to update many GalleryPosts.
   * @example
   * // Update many GalleryPosts
   * const galleryPost = await prisma.galleryPost.updateManyAndReturn({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Update zero or more GalleryPosts and only return the `id`
   * const galleryPostWithIdOnly = await prisma.galleryPost.updateManyAndReturn({
   *   select: { id: true },
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  updateManyAndReturn<T extends GalleryPostUpdateManyAndReturnArgs>(args: Prisma.SelectSubset<T, GalleryPostUpdateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$GalleryPostPayload<ExtArgs>, T, "updateManyAndReturn", GlobalOmitOptions>>

  /**
   * Create or update one GalleryPost.
   * @param {GalleryPostUpsertArgs} args - Arguments to update or create a GalleryPost.
   * @example
   * // Update or create a GalleryPost
   * const galleryPost = await prisma.galleryPost.upsert({
   *   create: {
   *     // ... data to create a GalleryPost
   *   },
   *   update: {
   *     // ... in case it already exists, update
   *   },
   *   where: {
   *     // ... the filter for the GalleryPost we want to update
   *   }
   * })
   */
  upsert<T extends GalleryPostUpsertArgs>(args: Prisma.SelectSubset<T, GalleryPostUpsertArgs<ExtArgs>>): Prisma.Prisma__GalleryPostClient<runtime.Types.Result.GetResult<Prisma.$GalleryPostPayload<ExtArgs>, T, "upsert", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>


  /**
   * Count the number of GalleryPosts.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {GalleryPostCountArgs} args - Arguments to filter GalleryPosts to count.
   * @example
   * // Count the number of GalleryPosts
   * const count = await prisma.galleryPost.count({
   *   where: {
   *     // ... the filter for the GalleryPosts we want to count
   *   }
   * })
  **/
  count<T extends GalleryPostCountArgs>(
    args?: Prisma.Subset<T, GalleryPostCountArgs>,
  ): Prisma.PrismaPromise<
    T extends runtime.Types.Utils.Record<'select', any>
      ? T['select'] extends true
        ? number
        : Prisma.GetScalarType<T['select'], GalleryPostCountAggregateOutputType>
      : number
  >

  /**
   * Allows you to perform aggregations operations on a GalleryPost.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {GalleryPostAggregateArgs} args - Select which aggregations you would like to apply and on what fields.
   * @example
   * // Ordered by age ascending
   * // Where email contains prisma.io
   * // Limited to the 10 users
   * const aggregations = await prisma.user.aggregate({
   *   _avg: {
   *     age: true,
   *   },
   *   where: {
   *     email: {
   *       contains: "prisma.io",
   *     },
   *   },
   *   orderBy: {
   *     age: "asc",
   *   },
   *   take: 10,
   * })
  **/
  aggregate<T extends GalleryPostAggregateArgs>(args: Prisma.Subset<T, GalleryPostAggregateArgs>): Prisma.PrismaPromise<GetGalleryPostAggregateType<T>>

  /**
   * Group by GalleryPost.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {GalleryPostGroupByArgs} args - Group by arguments.
   * @example
   * // Group by city, order by createdAt, get count
   * const result = await prisma.user.groupBy({
   *   by: ['city', 'createdAt'],
   *   orderBy: {
   *     createdAt: true
   *   },
   *   _count: {
   *     _all: true
   *   },
   * })
   * 
  **/
  groupBy<
    T extends GalleryPostGroupByArgs,
    HasSelectOrTake extends Prisma.Or<
      Prisma.Extends<'skip', Prisma.Keys<T>>,
      Prisma.Extends<'take', Prisma.Keys<T>>
    >,
    OrderByArg extends Prisma.True extends HasSelectOrTake
      ? { orderBy: GalleryPostGroupByArgs['orderBy'] }
      : { orderBy?: GalleryPostGroupByArgs['orderBy'] },
    OrderFields extends Prisma.ExcludeUnderscoreKeys<Prisma.Keys<Prisma.MaybeTupleToUnion<T['orderBy']>>>,
    ByFields extends Prisma.MaybeTupleToUnion<T['by']>,
    ByValid extends Prisma.Has<ByFields, OrderFields>,
    HavingFields extends Prisma.GetHavingFields<T['having']>,
    HavingValid extends Prisma.Has<ByFields, HavingFields>,
    ByEmpty extends T['by'] extends never[] ? Prisma.True : Prisma.False,
    InputErrors extends ByEmpty extends Prisma.True
    ? `Error: "by" must not be empty.`
    : HavingValid extends Prisma.False
    ? {
        [P in HavingFields]: P extends ByFields
          ? never
          : P extends string
          ? `Error: Field "${P}" used in "having" needs to be provided in "by".`
          : [
              Error,
              'Field ',
              P,
              ` in "having" needs to be provided in "by"`,
            ]
      }[HavingFields]
    : 'take' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "take", you also need to provide "orderBy"'
    : 'skip' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "skip", you also need to provide "orderBy"'
    : ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
          ? never
          : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
      }[OrderFields]
  >(args: Prisma.SubsetIntersection<T, GalleryPostGroupByArgs, OrderByArg> & InputErrors): {} extends InputErrors ? GetGalleryPostGroupByPayload<T> : Prisma.PrismaPromise<InputErrors>
/**
 * Fields of the GalleryPost model
 */
readonly fields: GalleryPostFieldRefs;
}

/**
 * The delegate class that acts as a "Promise-like" for GalleryPost.
 * Why is this prefixed with `Prisma__`?
 * Because we want to prevent naming conflicts as mentioned in
 * https://github.com/prisma/prisma-client-js/issues/707
 */
export interface Prisma__GalleryPostClient<T, Null = never, ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> extends Prisma.PrismaPromise<T> {
  readonly [Symbol.toStringTag]: "PrismaPromise"
  createdBy<T extends Prisma.UserDefaultArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.UserDefaultArgs<ExtArgs>>): Prisma.Prisma__UserClient<runtime.Types.Result.GetResult<Prisma.$UserPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions> | Null, Null, ExtArgs, GlobalOmitOptions>
  reactions<T extends Prisma.GalleryPost$reactionsArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.GalleryPost$reactionsArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$GalleryPostReactionPayload<ExtArgs>, T, "findMany", GlobalOmitOptions> | Null>
  /**
   * Attaches callbacks for the resolution and/or rejection of the Promise.
   * @param onfulfilled The callback to execute when the Promise is resolved.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of which ever callback is executed.
   */
  then<TResult1 = T, TResult2 = never>(onfulfilled?: ((value: T) => TResult1 | PromiseLike<TResult1>) | undefined | null, onrejected?: ((reason: any) => TResult2 | PromiseLike<TResult2>) | undefined | null): runtime.Types.Utils.JsPromise<TResult1 | TResult2>
  /**
   * Attaches a callback for only the rejection of the Promise.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of the callback.
   */
  catch<TResult = never>(onrejected?: ((reason: any) => TResult | PromiseLike<TResult>) | undefined | null): runtime.Types.Utils.JsPromise<T | TResult>
  /**
   * Attaches a callback that is invoked when the Promise is settled (fulfilled or rejected). The
   * resolved value cannot be modified from the callback.
   * @param onfinally The callback to execute when the Promise is settled (fulfilled or rejected).
   * @returns A Promise for the completion of the callback.
   */
  finally(onfinally?: (() => void) | undefined | null): runtime.Types.Utils.JsPromise<T>
}




/**
 * Fields of the GalleryPost model
 */
export interface GalleryPostFieldRefs {
  readonly id: Prisma.FieldRef<"GalleryPost", 'String'>
  readonly userId: Prisma.FieldRef<"GalleryPost", 'String'>
  readonly mediaKey: Prisma.FieldRef<"GalleryPost", 'String'>
  readonly type: Prisma.FieldRef<"GalleryPost", 'MediaType'>
  readonly createdAt: Prisma.FieldRef<"GalleryPost", 'DateTime'>
}
    

// Custom InputTypes
/**
 * GalleryPost findUnique
 */
export type GalleryPostFindUniqueArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the GalleryPost
   */
  select?: Prisma.GalleryPostSelect<ExtArgs> | null
  /**
   * Omit specific fields from the GalleryPost
   */
  omit?: Prisma.GalleryPostOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.GalleryPostInclude<ExtArgs> | null
  /**
   * Filter, which GalleryPost to fetch.
   */
  where: Prisma.GalleryPostWhereUniqueInput
}

/**
 * GalleryPost findUniqueOrThrow
 */
export type GalleryPostFindUniqueOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the GalleryPost
   */
  select?: Prisma.GalleryPostSelect<ExtArgs> | null
  /**
   * Omit specific fields from the GalleryPost
   */
  omit?: Prisma.GalleryPostOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.GalleryPostInclude<ExtArgs> | null
  /**
   * Filter, which GalleryPost to fetch.
   */
  where: Prisma.GalleryPostWhereUniqueInput
}

/**
 * GalleryPost findFirst
 */
export type GalleryPostFindFirstArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the GalleryPost
   */
  select?: Prisma.GalleryPostSelect<ExtArgs> | null
  /**
   * Omit specific fields from the GalleryPost
   */
  omit?: Prisma.GalleryPostOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.GalleryPostInclude<ExtArgs> | null
  /**
   * Filter, which GalleryPost to fetch.
   */
  where?: Prisma.GalleryPostWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of GalleryPosts to fetch.
   */
  orderBy?: Prisma.GalleryPostOrderByWithRelationInput | Prisma.GalleryPostOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for GalleryPosts.
   */
  cursor?: Prisma.GalleryPostWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` GalleryPosts from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` GalleryPosts.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of GalleryPosts.
   */
  distinct?: Prisma.GalleryPostScalarFieldEnum | Prisma.GalleryPostScalarFieldEnum[]
}

/**
 * GalleryPost findFirstOrThrow
 */
export type GalleryPostFindFirstOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the GalleryPost
   */
  select?: Prisma.GalleryPostSelect<ExtArgs> | null
  /**
   * Omit specific fields from the GalleryPost
   */
  omit?: Prisma.GalleryPostOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.GalleryPostInclude<ExtArgs> | null
  /**
   * Filter, which GalleryPost to fetch.
   */
  where?: Prisma.GalleryPostWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of GalleryPosts to fetch.
   */
  orderBy?: Prisma.GalleryPostOrderByWithRelationInput | Prisma.GalleryPostOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for GalleryPosts.
   */
  cursor?: Prisma.GalleryPostWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` GalleryPosts from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` GalleryPosts.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of GalleryPosts.
   */
  distinct?: Prisma.GalleryPostScalarFieldEnum | Prisma.GalleryPostScalarFieldEnum[]
}

/**
 * GalleryPost findMany
 */
export type GalleryPostFindManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the GalleryPost
   */
  select?: Prisma.GalleryPostSelect<ExtArgs> | null
  /**
   * Omit specific fields from the GalleryPost
   */
  omit?: Prisma.GalleryPostOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.GalleryPostInclude<ExtArgs> | null
  /**
   * Filter, which GalleryPosts to fetch.
   */
  where?: Prisma.GalleryPostWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of GalleryPosts to fetch.
   */
  orderBy?: Prisma.GalleryPostOrderByWithRelationInput | Prisma.GalleryPostOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for listing GalleryPosts.
   */
  cursor?: Prisma.GalleryPostWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` GalleryPosts from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` GalleryPosts.
   */
  skip?: number
  distinct?: Prisma.GalleryPostScalarFieldEnum | Prisma.GalleryPostScalarFieldEnum[]
}

/**
 * GalleryPost create
 */
export type GalleryPostCreateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the GalleryPost
   */
  select?: Prisma.GalleryPostSelect<ExtArgs> | null
  /**
   * Omit specific fields from the GalleryPost
   */
  omit?: Prisma.GalleryPostOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.GalleryPostInclude<ExtArgs> | null
  /**
   * The data needed to create a GalleryPost.
   */
  data: Prisma.XOR<Prisma.GalleryPostCreateInput, Prisma.GalleryPostUncheckedCreateInput>
}

/**
 * GalleryPost createMany
 */
export type GalleryPostCreateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to create many GalleryPosts.
   */
  data: Prisma.GalleryPostCreateManyInput | Prisma.GalleryPostCreateManyInput[]
}

/**
 * GalleryPost createManyAndReturn
 */
export type GalleryPostCreateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the GalleryPost
   */
  select?: Prisma.GalleryPostSelectCreateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the GalleryPost
   */
  omit?: Prisma.GalleryPostOmit<ExtArgs> | null
  /**
   * The data used to create many GalleryPosts.
   */
  data: Prisma.GalleryPostCreateManyInput | Prisma.GalleryPostCreateManyInput[]
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.GalleryPostIncludeCreateManyAndReturn<ExtArgs> | null
}

/**
 * GalleryPost update
 */
export type GalleryPostUpdateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the GalleryPost
   */
  select?: Prisma.GalleryPostSelect<ExtArgs> | null
  /**
   * Omit specific fields from the GalleryPost
   */
  omit?: Prisma.GalleryPostOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.GalleryPostInclude<ExtArgs> | null
  /**
   * The data needed to update a GalleryPost.
   */
  data: Prisma.XOR<Prisma.GalleryPostUpdateInput, Prisma.GalleryPostUncheckedUpdateInput>
  /**
   * Choose, which GalleryPost to update.
   */
  where: Prisma.GalleryPostWhereUniqueInput
}

/**
 * GalleryPost updateMany
 */
export type GalleryPostUpdateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to update GalleryPosts.
   */
  data: Prisma.XOR<Prisma.GalleryPostUpdateManyMutationInput, Prisma.GalleryPostUncheckedUpdateManyInput>
  /**
   * Filter which GalleryPosts to update
   */
  where?: Prisma.GalleryPostWhereInput
  /**
   * Limit how many GalleryPosts to update.
   */
  limit?: number
}

/**
 * GalleryPost updateManyAndReturn
 */
export type GalleryPostUpdateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the GalleryPost
   */
  select?: Prisma.GalleryPostSelectUpdateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the GalleryPost
   */
  omit?: Prisma.GalleryPostOmit<ExtArgs> | null
  /**
   * The data used to update GalleryPosts.
   */
  data: Prisma.XOR<Prisma.GalleryPostUpdateManyMutationInput, Prisma.GalleryPostUncheckedUpdateManyInput>
  /**
   * Filter which GalleryPosts to update
   */
  where?: Prisma.GalleryPostWhereInput
  /**
   * Limit how many GalleryPosts to update.
   */
  limit?: number
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.GalleryPostIncludeUpdateManyAndReturn<ExtArgs> | null
}

/**
 * GalleryPost upsert
 */
export type GalleryPostUpsertArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the GalleryPost
   */
  select?: Prisma.GalleryPostSelect<ExtArgs> | null
  /**
   * Omit specific fields from the GalleryPost
   */
  omit?: Prisma.GalleryPostOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.GalleryPostInclude<ExtArgs> | null
  /**
   * The filter to search for the GalleryPost to update in case it exists.
   */
  where: Prisma.GalleryPostWhereUniqueInput
  /**
   * In case the GalleryPost found by the `where` argument doesn't exist, create a new GalleryPost with this data.
   */
  create: Prisma.XOR<Prisma.GalleryPostCreateInput, Prisma.GalleryPostUncheckedCreateInput>
  /**
   * In case the GalleryPost was found with the provided `where` argument, update it with this data.
   */
  update: Prisma.XOR<Prisma.GalleryPostUpdateInput, Prisma.GalleryPostUncheckedUpdateInput>
}

/**
 * GalleryPost delete
 */
export type GalleryPostDeleteArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the GalleryPost
   */
  select?: Prisma.GalleryPostSelect<ExtArgs> | null
  /**
   * Omit specific fields from the GalleryPost
   */
  omit?: Prisma.GalleryPostOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.GalleryPostInclude<ExtArgs> | null
  /**
   * Filter which GalleryPost to delete.
   */
  where: Prisma.GalleryPostWhereUniqueInput
}

/**
 * GalleryPost deleteMany
 */
export type GalleryPostDeleteManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which GalleryPosts to delete
   */
  where?: Prisma.GalleryPostWhereInput
  /**
   * Limit how many GalleryPosts to delete.
   */
  limit?: number
}

/**
 * GalleryPost.reactions
 */
export type GalleryPost$reactionsArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the GalleryPostReaction
   */
  select?: Prisma.GalleryPostReactionSelect<ExtArgs> | null
  /**
   * Omit specific fields from the GalleryPostReaction
   */
  omit?: Prisma.GalleryPostReactionOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.GalleryPostReactionInclude<ExtArgs> | null
  where?: Prisma.GalleryPostReactionWhereInput
  orderBy?: Prisma.GalleryPostReactionOrderByWithRelationInput | Prisma.GalleryPostReactionOrderByWithRelationInput[]
  cursor?: Prisma.GalleryPostReactionWhereUniqueInput
  take?: number
  skip?: number
  distinct?: Prisma.GalleryPostReactionScalarFieldEnum | Prisma.GalleryPostReactionScalarFieldEnum[]
}

/**
 * GalleryPost without action
 */
export type GalleryPostDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the GalleryPost
   */
  select?: Prisma.GalleryPostSelect<ExtArgs> | null
  /**
   * Omit specific fields from the GalleryPost
   */
  omit?: Prisma.GalleryPostOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.GalleryPostInclude<ExtArgs> | null
}
