
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
 * This file exports the `UserNameChangeRequest` model and its related types.
 *
 * 🟢 You can import this file directly.
 */
import type * as runtime from "@prisma/client/runtime/client"
import type * as $Enums from "../enums.js"
import type * as Prisma from "../internal/prismaNamespace.js"

/**
 * Model UserNameChangeRequest
 * 
 */
export type UserNameChangeRequestModel = runtime.Types.Result.DefaultSelection<Prisma.$UserNameChangeRequestPayload>

export type AggregateUserNameChangeRequest = {
  _count: UserNameChangeRequestCountAggregateOutputType | null
  _min: UserNameChangeRequestMinAggregateOutputType | null
  _max: UserNameChangeRequestMaxAggregateOutputType | null
}

export type UserNameChangeRequestMinAggregateOutputType = {
  id: string | null
  userId: string | null
  requestedName: string | null
  status: string | null
  source: string | null
  requestedAt: Date | null
  reviewedAt: Date | null
  reviewedById: string | null
  rejectionReason: string | null
  adminsNotified: boolean | null
  notifiedAt: Date | null
}

export type UserNameChangeRequestMaxAggregateOutputType = {
  id: string | null
  userId: string | null
  requestedName: string | null
  status: string | null
  source: string | null
  requestedAt: Date | null
  reviewedAt: Date | null
  reviewedById: string | null
  rejectionReason: string | null
  adminsNotified: boolean | null
  notifiedAt: Date | null
}

export type UserNameChangeRequestCountAggregateOutputType = {
  id: number
  userId: number
  requestedName: number
  status: number
  source: number
  requestedAt: number
  reviewedAt: number
  reviewedById: number
  rejectionReason: number
  adminsNotified: number
  notifiedAt: number
  _all: number
}


export type UserNameChangeRequestMinAggregateInputType = {
  id?: true
  userId?: true
  requestedName?: true
  status?: true
  source?: true
  requestedAt?: true
  reviewedAt?: true
  reviewedById?: true
  rejectionReason?: true
  adminsNotified?: true
  notifiedAt?: true
}

export type UserNameChangeRequestMaxAggregateInputType = {
  id?: true
  userId?: true
  requestedName?: true
  status?: true
  source?: true
  requestedAt?: true
  reviewedAt?: true
  reviewedById?: true
  rejectionReason?: true
  adminsNotified?: true
  notifiedAt?: true
}

export type UserNameChangeRequestCountAggregateInputType = {
  id?: true
  userId?: true
  requestedName?: true
  status?: true
  source?: true
  requestedAt?: true
  reviewedAt?: true
  reviewedById?: true
  rejectionReason?: true
  adminsNotified?: true
  notifiedAt?: true
  _all?: true
}

export type UserNameChangeRequestAggregateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which UserNameChangeRequest to aggregate.
   */
  where?: Prisma.UserNameChangeRequestWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of UserNameChangeRequests to fetch.
   */
  orderBy?: Prisma.UserNameChangeRequestOrderByWithRelationInput | Prisma.UserNameChangeRequestOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the start position
   */
  cursor?: Prisma.UserNameChangeRequestWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` UserNameChangeRequests from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` UserNameChangeRequests.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Count returned UserNameChangeRequests
  **/
  _count?: true | UserNameChangeRequestCountAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the minimum value
  **/
  _min?: UserNameChangeRequestMinAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the maximum value
  **/
  _max?: UserNameChangeRequestMaxAggregateInputType
}

export type GetUserNameChangeRequestAggregateType<T extends UserNameChangeRequestAggregateArgs> = {
      [P in keyof T & keyof AggregateUserNameChangeRequest]: P extends '_count' | 'count'
    ? T[P] extends true
      ? number
      : Prisma.GetScalarType<T[P], AggregateUserNameChangeRequest[P]>
    : Prisma.GetScalarType<T[P], AggregateUserNameChangeRequest[P]>
}




export type UserNameChangeRequestGroupByArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.UserNameChangeRequestWhereInput
  orderBy?: Prisma.UserNameChangeRequestOrderByWithAggregationInput | Prisma.UserNameChangeRequestOrderByWithAggregationInput[]
  by: Prisma.UserNameChangeRequestScalarFieldEnum[] | Prisma.UserNameChangeRequestScalarFieldEnum
  having?: Prisma.UserNameChangeRequestScalarWhereWithAggregatesInput
  take?: number
  skip?: number
  _count?: UserNameChangeRequestCountAggregateInputType | true
  _min?: UserNameChangeRequestMinAggregateInputType
  _max?: UserNameChangeRequestMaxAggregateInputType
}

export type UserNameChangeRequestGroupByOutputType = {
  id: string
  userId: string
  requestedName: string
  status: string
  source: string
  requestedAt: Date
  reviewedAt: Date | null
  reviewedById: string | null
  rejectionReason: string | null
  adminsNotified: boolean
  notifiedAt: Date | null
  _count: UserNameChangeRequestCountAggregateOutputType | null
  _min: UserNameChangeRequestMinAggregateOutputType | null
  _max: UserNameChangeRequestMaxAggregateOutputType | null
}

export type GetUserNameChangeRequestGroupByPayload<T extends UserNameChangeRequestGroupByArgs> = Prisma.PrismaPromise<
  Array<
    Prisma.PickEnumerable<UserNameChangeRequestGroupByOutputType, T['by']> &
      {
        [P in ((keyof T) & (keyof UserNameChangeRequestGroupByOutputType))]: P extends '_count'
          ? T[P] extends boolean
            ? number
            : Prisma.GetScalarType<T[P], UserNameChangeRequestGroupByOutputType[P]>
          : Prisma.GetScalarType<T[P], UserNameChangeRequestGroupByOutputType[P]>
      }
    >
  >



export type UserNameChangeRequestWhereInput = {
  AND?: Prisma.UserNameChangeRequestWhereInput | Prisma.UserNameChangeRequestWhereInput[]
  OR?: Prisma.UserNameChangeRequestWhereInput[]
  NOT?: Prisma.UserNameChangeRequestWhereInput | Prisma.UserNameChangeRequestWhereInput[]
  id?: Prisma.StringFilter<"UserNameChangeRequest"> | string
  userId?: Prisma.StringFilter<"UserNameChangeRequest"> | string
  requestedName?: Prisma.StringFilter<"UserNameChangeRequest"> | string
  status?: Prisma.StringFilter<"UserNameChangeRequest"> | string
  source?: Prisma.StringFilter<"UserNameChangeRequest"> | string
  requestedAt?: Prisma.DateTimeFilter<"UserNameChangeRequest"> | Date | string
  reviewedAt?: Prisma.DateTimeNullableFilter<"UserNameChangeRequest"> | Date | string | null
  reviewedById?: Prisma.StringNullableFilter<"UserNameChangeRequest"> | string | null
  rejectionReason?: Prisma.StringNullableFilter<"UserNameChangeRequest"> | string | null
  adminsNotified?: Prisma.BoolFilter<"UserNameChangeRequest"> | boolean
  notifiedAt?: Prisma.DateTimeNullableFilter<"UserNameChangeRequest"> | Date | string | null
  user?: Prisma.XOR<Prisma.UserScalarRelationFilter, Prisma.UserWhereInput>
  reviewedBy?: Prisma.XOR<Prisma.UserNullableScalarRelationFilter, Prisma.UserWhereInput> | null
}

export type UserNameChangeRequestOrderByWithRelationInput = {
  id?: Prisma.SortOrder
  userId?: Prisma.SortOrder
  requestedName?: Prisma.SortOrder
  status?: Prisma.SortOrder
  source?: Prisma.SortOrder
  requestedAt?: Prisma.SortOrder
  reviewedAt?: Prisma.SortOrderInput | Prisma.SortOrder
  reviewedById?: Prisma.SortOrderInput | Prisma.SortOrder
  rejectionReason?: Prisma.SortOrderInput | Prisma.SortOrder
  adminsNotified?: Prisma.SortOrder
  notifiedAt?: Prisma.SortOrderInput | Prisma.SortOrder
  user?: Prisma.UserOrderByWithRelationInput
  reviewedBy?: Prisma.UserOrderByWithRelationInput
}

export type UserNameChangeRequestWhereUniqueInput = Prisma.AtLeast<{
  id?: string
  AND?: Prisma.UserNameChangeRequestWhereInput | Prisma.UserNameChangeRequestWhereInput[]
  OR?: Prisma.UserNameChangeRequestWhereInput[]
  NOT?: Prisma.UserNameChangeRequestWhereInput | Prisma.UserNameChangeRequestWhereInput[]
  userId?: Prisma.StringFilter<"UserNameChangeRequest"> | string
  requestedName?: Prisma.StringFilter<"UserNameChangeRequest"> | string
  status?: Prisma.StringFilter<"UserNameChangeRequest"> | string
  source?: Prisma.StringFilter<"UserNameChangeRequest"> | string
  requestedAt?: Prisma.DateTimeFilter<"UserNameChangeRequest"> | Date | string
  reviewedAt?: Prisma.DateTimeNullableFilter<"UserNameChangeRequest"> | Date | string | null
  reviewedById?: Prisma.StringNullableFilter<"UserNameChangeRequest"> | string | null
  rejectionReason?: Prisma.StringNullableFilter<"UserNameChangeRequest"> | string | null
  adminsNotified?: Prisma.BoolFilter<"UserNameChangeRequest"> | boolean
  notifiedAt?: Prisma.DateTimeNullableFilter<"UserNameChangeRequest"> | Date | string | null
  user?: Prisma.XOR<Prisma.UserScalarRelationFilter, Prisma.UserWhereInput>
  reviewedBy?: Prisma.XOR<Prisma.UserNullableScalarRelationFilter, Prisma.UserWhereInput> | null
}, "id">

export type UserNameChangeRequestOrderByWithAggregationInput = {
  id?: Prisma.SortOrder
  userId?: Prisma.SortOrder
  requestedName?: Prisma.SortOrder
  status?: Prisma.SortOrder
  source?: Prisma.SortOrder
  requestedAt?: Prisma.SortOrder
  reviewedAt?: Prisma.SortOrderInput | Prisma.SortOrder
  reviewedById?: Prisma.SortOrderInput | Prisma.SortOrder
  rejectionReason?: Prisma.SortOrderInput | Prisma.SortOrder
  adminsNotified?: Prisma.SortOrder
  notifiedAt?: Prisma.SortOrderInput | Prisma.SortOrder
  _count?: Prisma.UserNameChangeRequestCountOrderByAggregateInput
  _max?: Prisma.UserNameChangeRequestMaxOrderByAggregateInput
  _min?: Prisma.UserNameChangeRequestMinOrderByAggregateInput
}

export type UserNameChangeRequestScalarWhereWithAggregatesInput = {
  AND?: Prisma.UserNameChangeRequestScalarWhereWithAggregatesInput | Prisma.UserNameChangeRequestScalarWhereWithAggregatesInput[]
  OR?: Prisma.UserNameChangeRequestScalarWhereWithAggregatesInput[]
  NOT?: Prisma.UserNameChangeRequestScalarWhereWithAggregatesInput | Prisma.UserNameChangeRequestScalarWhereWithAggregatesInput[]
  id?: Prisma.StringWithAggregatesFilter<"UserNameChangeRequest"> | string
  userId?: Prisma.StringWithAggregatesFilter<"UserNameChangeRequest"> | string
  requestedName?: Prisma.StringWithAggregatesFilter<"UserNameChangeRequest"> | string
  status?: Prisma.StringWithAggregatesFilter<"UserNameChangeRequest"> | string
  source?: Prisma.StringWithAggregatesFilter<"UserNameChangeRequest"> | string
  requestedAt?: Prisma.DateTimeWithAggregatesFilter<"UserNameChangeRequest"> | Date | string
  reviewedAt?: Prisma.DateTimeNullableWithAggregatesFilter<"UserNameChangeRequest"> | Date | string | null
  reviewedById?: Prisma.StringNullableWithAggregatesFilter<"UserNameChangeRequest"> | string | null
  rejectionReason?: Prisma.StringNullableWithAggregatesFilter<"UserNameChangeRequest"> | string | null
  adminsNotified?: Prisma.BoolWithAggregatesFilter<"UserNameChangeRequest"> | boolean
  notifiedAt?: Prisma.DateTimeNullableWithAggregatesFilter<"UserNameChangeRequest"> | Date | string | null
}

export type UserNameChangeRequestCreateInput = {
  id?: string
  requestedName: string
  status?: string
  source: string
  requestedAt?: Date | string
  reviewedAt?: Date | string | null
  rejectionReason?: string | null
  adminsNotified?: boolean
  notifiedAt?: Date | string | null
  user: Prisma.UserCreateNestedOneWithoutNameChangeRequestsInput
  reviewedBy?: Prisma.UserCreateNestedOneWithoutReviewedNameChangeRequestsInput
}

export type UserNameChangeRequestUncheckedCreateInput = {
  id?: string
  userId: string
  requestedName: string
  status?: string
  source: string
  requestedAt?: Date | string
  reviewedAt?: Date | string | null
  reviewedById?: string | null
  rejectionReason?: string | null
  adminsNotified?: boolean
  notifiedAt?: Date | string | null
}

export type UserNameChangeRequestUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  requestedName?: Prisma.StringFieldUpdateOperationsInput | string
  status?: Prisma.StringFieldUpdateOperationsInput | string
  source?: Prisma.StringFieldUpdateOperationsInput | string
  requestedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  reviewedAt?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  rejectionReason?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  adminsNotified?: Prisma.BoolFieldUpdateOperationsInput | boolean
  notifiedAt?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  user?: Prisma.UserUpdateOneRequiredWithoutNameChangeRequestsNestedInput
  reviewedBy?: Prisma.UserUpdateOneWithoutReviewedNameChangeRequestsNestedInput
}

export type UserNameChangeRequestUncheckedUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  userId?: Prisma.StringFieldUpdateOperationsInput | string
  requestedName?: Prisma.StringFieldUpdateOperationsInput | string
  status?: Prisma.StringFieldUpdateOperationsInput | string
  source?: Prisma.StringFieldUpdateOperationsInput | string
  requestedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  reviewedAt?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  reviewedById?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  rejectionReason?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  adminsNotified?: Prisma.BoolFieldUpdateOperationsInput | boolean
  notifiedAt?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
}

export type UserNameChangeRequestCreateManyInput = {
  id?: string
  userId: string
  requestedName: string
  status?: string
  source: string
  requestedAt?: Date | string
  reviewedAt?: Date | string | null
  reviewedById?: string | null
  rejectionReason?: string | null
  adminsNotified?: boolean
  notifiedAt?: Date | string | null
}

export type UserNameChangeRequestUpdateManyMutationInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  requestedName?: Prisma.StringFieldUpdateOperationsInput | string
  status?: Prisma.StringFieldUpdateOperationsInput | string
  source?: Prisma.StringFieldUpdateOperationsInput | string
  requestedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  reviewedAt?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  rejectionReason?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  adminsNotified?: Prisma.BoolFieldUpdateOperationsInput | boolean
  notifiedAt?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
}

export type UserNameChangeRequestUncheckedUpdateManyInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  userId?: Prisma.StringFieldUpdateOperationsInput | string
  requestedName?: Prisma.StringFieldUpdateOperationsInput | string
  status?: Prisma.StringFieldUpdateOperationsInput | string
  source?: Prisma.StringFieldUpdateOperationsInput | string
  requestedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  reviewedAt?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  reviewedById?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  rejectionReason?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  adminsNotified?: Prisma.BoolFieldUpdateOperationsInput | boolean
  notifiedAt?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
}

export type UserNameChangeRequestListRelationFilter = {
  every?: Prisma.UserNameChangeRequestWhereInput
  some?: Prisma.UserNameChangeRequestWhereInput
  none?: Prisma.UserNameChangeRequestWhereInput
}

export type UserNameChangeRequestOrderByRelationAggregateInput = {
  _count?: Prisma.SortOrder
}

export type UserNameChangeRequestCountOrderByAggregateInput = {
  id?: Prisma.SortOrder
  userId?: Prisma.SortOrder
  requestedName?: Prisma.SortOrder
  status?: Prisma.SortOrder
  source?: Prisma.SortOrder
  requestedAt?: Prisma.SortOrder
  reviewedAt?: Prisma.SortOrder
  reviewedById?: Prisma.SortOrder
  rejectionReason?: Prisma.SortOrder
  adminsNotified?: Prisma.SortOrder
  notifiedAt?: Prisma.SortOrder
}

export type UserNameChangeRequestMaxOrderByAggregateInput = {
  id?: Prisma.SortOrder
  userId?: Prisma.SortOrder
  requestedName?: Prisma.SortOrder
  status?: Prisma.SortOrder
  source?: Prisma.SortOrder
  requestedAt?: Prisma.SortOrder
  reviewedAt?: Prisma.SortOrder
  reviewedById?: Prisma.SortOrder
  rejectionReason?: Prisma.SortOrder
  adminsNotified?: Prisma.SortOrder
  notifiedAt?: Prisma.SortOrder
}

export type UserNameChangeRequestMinOrderByAggregateInput = {
  id?: Prisma.SortOrder
  userId?: Prisma.SortOrder
  requestedName?: Prisma.SortOrder
  status?: Prisma.SortOrder
  source?: Prisma.SortOrder
  requestedAt?: Prisma.SortOrder
  reviewedAt?: Prisma.SortOrder
  reviewedById?: Prisma.SortOrder
  rejectionReason?: Prisma.SortOrder
  adminsNotified?: Prisma.SortOrder
  notifiedAt?: Prisma.SortOrder
}

export type UserNameChangeRequestCreateNestedManyWithoutUserInput = {
  create?: Prisma.XOR<Prisma.UserNameChangeRequestCreateWithoutUserInput, Prisma.UserNameChangeRequestUncheckedCreateWithoutUserInput> | Prisma.UserNameChangeRequestCreateWithoutUserInput[] | Prisma.UserNameChangeRequestUncheckedCreateWithoutUserInput[]
  connectOrCreate?: Prisma.UserNameChangeRequestCreateOrConnectWithoutUserInput | Prisma.UserNameChangeRequestCreateOrConnectWithoutUserInput[]
  createMany?: Prisma.UserNameChangeRequestCreateManyUserInputEnvelope
  connect?: Prisma.UserNameChangeRequestWhereUniqueInput | Prisma.UserNameChangeRequestWhereUniqueInput[]
}

export type UserNameChangeRequestCreateNestedManyWithoutReviewedByInput = {
  create?: Prisma.XOR<Prisma.UserNameChangeRequestCreateWithoutReviewedByInput, Prisma.UserNameChangeRequestUncheckedCreateWithoutReviewedByInput> | Prisma.UserNameChangeRequestCreateWithoutReviewedByInput[] | Prisma.UserNameChangeRequestUncheckedCreateWithoutReviewedByInput[]
  connectOrCreate?: Prisma.UserNameChangeRequestCreateOrConnectWithoutReviewedByInput | Prisma.UserNameChangeRequestCreateOrConnectWithoutReviewedByInput[]
  createMany?: Prisma.UserNameChangeRequestCreateManyReviewedByInputEnvelope
  connect?: Prisma.UserNameChangeRequestWhereUniqueInput | Prisma.UserNameChangeRequestWhereUniqueInput[]
}

export type UserNameChangeRequestUncheckedCreateNestedManyWithoutUserInput = {
  create?: Prisma.XOR<Prisma.UserNameChangeRequestCreateWithoutUserInput, Prisma.UserNameChangeRequestUncheckedCreateWithoutUserInput> | Prisma.UserNameChangeRequestCreateWithoutUserInput[] | Prisma.UserNameChangeRequestUncheckedCreateWithoutUserInput[]
  connectOrCreate?: Prisma.UserNameChangeRequestCreateOrConnectWithoutUserInput | Prisma.UserNameChangeRequestCreateOrConnectWithoutUserInput[]
  createMany?: Prisma.UserNameChangeRequestCreateManyUserInputEnvelope
  connect?: Prisma.UserNameChangeRequestWhereUniqueInput | Prisma.UserNameChangeRequestWhereUniqueInput[]
}

export type UserNameChangeRequestUncheckedCreateNestedManyWithoutReviewedByInput = {
  create?: Prisma.XOR<Prisma.UserNameChangeRequestCreateWithoutReviewedByInput, Prisma.UserNameChangeRequestUncheckedCreateWithoutReviewedByInput> | Prisma.UserNameChangeRequestCreateWithoutReviewedByInput[] | Prisma.UserNameChangeRequestUncheckedCreateWithoutReviewedByInput[]
  connectOrCreate?: Prisma.UserNameChangeRequestCreateOrConnectWithoutReviewedByInput | Prisma.UserNameChangeRequestCreateOrConnectWithoutReviewedByInput[]
  createMany?: Prisma.UserNameChangeRequestCreateManyReviewedByInputEnvelope
  connect?: Prisma.UserNameChangeRequestWhereUniqueInput | Prisma.UserNameChangeRequestWhereUniqueInput[]
}

export type UserNameChangeRequestUpdateManyWithoutUserNestedInput = {
  create?: Prisma.XOR<Prisma.UserNameChangeRequestCreateWithoutUserInput, Prisma.UserNameChangeRequestUncheckedCreateWithoutUserInput> | Prisma.UserNameChangeRequestCreateWithoutUserInput[] | Prisma.UserNameChangeRequestUncheckedCreateWithoutUserInput[]
  connectOrCreate?: Prisma.UserNameChangeRequestCreateOrConnectWithoutUserInput | Prisma.UserNameChangeRequestCreateOrConnectWithoutUserInput[]
  upsert?: Prisma.UserNameChangeRequestUpsertWithWhereUniqueWithoutUserInput | Prisma.UserNameChangeRequestUpsertWithWhereUniqueWithoutUserInput[]
  createMany?: Prisma.UserNameChangeRequestCreateManyUserInputEnvelope
  set?: Prisma.UserNameChangeRequestWhereUniqueInput | Prisma.UserNameChangeRequestWhereUniqueInput[]
  disconnect?: Prisma.UserNameChangeRequestWhereUniqueInput | Prisma.UserNameChangeRequestWhereUniqueInput[]
  delete?: Prisma.UserNameChangeRequestWhereUniqueInput | Prisma.UserNameChangeRequestWhereUniqueInput[]
  connect?: Prisma.UserNameChangeRequestWhereUniqueInput | Prisma.UserNameChangeRequestWhereUniqueInput[]
  update?: Prisma.UserNameChangeRequestUpdateWithWhereUniqueWithoutUserInput | Prisma.UserNameChangeRequestUpdateWithWhereUniqueWithoutUserInput[]
  updateMany?: Prisma.UserNameChangeRequestUpdateManyWithWhereWithoutUserInput | Prisma.UserNameChangeRequestUpdateManyWithWhereWithoutUserInput[]
  deleteMany?: Prisma.UserNameChangeRequestScalarWhereInput | Prisma.UserNameChangeRequestScalarWhereInput[]
}

export type UserNameChangeRequestUpdateManyWithoutReviewedByNestedInput = {
  create?: Prisma.XOR<Prisma.UserNameChangeRequestCreateWithoutReviewedByInput, Prisma.UserNameChangeRequestUncheckedCreateWithoutReviewedByInput> | Prisma.UserNameChangeRequestCreateWithoutReviewedByInput[] | Prisma.UserNameChangeRequestUncheckedCreateWithoutReviewedByInput[]
  connectOrCreate?: Prisma.UserNameChangeRequestCreateOrConnectWithoutReviewedByInput | Prisma.UserNameChangeRequestCreateOrConnectWithoutReviewedByInput[]
  upsert?: Prisma.UserNameChangeRequestUpsertWithWhereUniqueWithoutReviewedByInput | Prisma.UserNameChangeRequestUpsertWithWhereUniqueWithoutReviewedByInput[]
  createMany?: Prisma.UserNameChangeRequestCreateManyReviewedByInputEnvelope
  set?: Prisma.UserNameChangeRequestWhereUniqueInput | Prisma.UserNameChangeRequestWhereUniqueInput[]
  disconnect?: Prisma.UserNameChangeRequestWhereUniqueInput | Prisma.UserNameChangeRequestWhereUniqueInput[]
  delete?: Prisma.UserNameChangeRequestWhereUniqueInput | Prisma.UserNameChangeRequestWhereUniqueInput[]
  connect?: Prisma.UserNameChangeRequestWhereUniqueInput | Prisma.UserNameChangeRequestWhereUniqueInput[]
  update?: Prisma.UserNameChangeRequestUpdateWithWhereUniqueWithoutReviewedByInput | Prisma.UserNameChangeRequestUpdateWithWhereUniqueWithoutReviewedByInput[]
  updateMany?: Prisma.UserNameChangeRequestUpdateManyWithWhereWithoutReviewedByInput | Prisma.UserNameChangeRequestUpdateManyWithWhereWithoutReviewedByInput[]
  deleteMany?: Prisma.UserNameChangeRequestScalarWhereInput | Prisma.UserNameChangeRequestScalarWhereInput[]
}

export type UserNameChangeRequestUncheckedUpdateManyWithoutUserNestedInput = {
  create?: Prisma.XOR<Prisma.UserNameChangeRequestCreateWithoutUserInput, Prisma.UserNameChangeRequestUncheckedCreateWithoutUserInput> | Prisma.UserNameChangeRequestCreateWithoutUserInput[] | Prisma.UserNameChangeRequestUncheckedCreateWithoutUserInput[]
  connectOrCreate?: Prisma.UserNameChangeRequestCreateOrConnectWithoutUserInput | Prisma.UserNameChangeRequestCreateOrConnectWithoutUserInput[]
  upsert?: Prisma.UserNameChangeRequestUpsertWithWhereUniqueWithoutUserInput | Prisma.UserNameChangeRequestUpsertWithWhereUniqueWithoutUserInput[]
  createMany?: Prisma.UserNameChangeRequestCreateManyUserInputEnvelope
  set?: Prisma.UserNameChangeRequestWhereUniqueInput | Prisma.UserNameChangeRequestWhereUniqueInput[]
  disconnect?: Prisma.UserNameChangeRequestWhereUniqueInput | Prisma.UserNameChangeRequestWhereUniqueInput[]
  delete?: Prisma.UserNameChangeRequestWhereUniqueInput | Prisma.UserNameChangeRequestWhereUniqueInput[]
  connect?: Prisma.UserNameChangeRequestWhereUniqueInput | Prisma.UserNameChangeRequestWhereUniqueInput[]
  update?: Prisma.UserNameChangeRequestUpdateWithWhereUniqueWithoutUserInput | Prisma.UserNameChangeRequestUpdateWithWhereUniqueWithoutUserInput[]
  updateMany?: Prisma.UserNameChangeRequestUpdateManyWithWhereWithoutUserInput | Prisma.UserNameChangeRequestUpdateManyWithWhereWithoutUserInput[]
  deleteMany?: Prisma.UserNameChangeRequestScalarWhereInput | Prisma.UserNameChangeRequestScalarWhereInput[]
}

export type UserNameChangeRequestUncheckedUpdateManyWithoutReviewedByNestedInput = {
  create?: Prisma.XOR<Prisma.UserNameChangeRequestCreateWithoutReviewedByInput, Prisma.UserNameChangeRequestUncheckedCreateWithoutReviewedByInput> | Prisma.UserNameChangeRequestCreateWithoutReviewedByInput[] | Prisma.UserNameChangeRequestUncheckedCreateWithoutReviewedByInput[]
  connectOrCreate?: Prisma.UserNameChangeRequestCreateOrConnectWithoutReviewedByInput | Prisma.UserNameChangeRequestCreateOrConnectWithoutReviewedByInput[]
  upsert?: Prisma.UserNameChangeRequestUpsertWithWhereUniqueWithoutReviewedByInput | Prisma.UserNameChangeRequestUpsertWithWhereUniqueWithoutReviewedByInput[]
  createMany?: Prisma.UserNameChangeRequestCreateManyReviewedByInputEnvelope
  set?: Prisma.UserNameChangeRequestWhereUniqueInput | Prisma.UserNameChangeRequestWhereUniqueInput[]
  disconnect?: Prisma.UserNameChangeRequestWhereUniqueInput | Prisma.UserNameChangeRequestWhereUniqueInput[]
  delete?: Prisma.UserNameChangeRequestWhereUniqueInput | Prisma.UserNameChangeRequestWhereUniqueInput[]
  connect?: Prisma.UserNameChangeRequestWhereUniqueInput | Prisma.UserNameChangeRequestWhereUniqueInput[]
  update?: Prisma.UserNameChangeRequestUpdateWithWhereUniqueWithoutReviewedByInput | Prisma.UserNameChangeRequestUpdateWithWhereUniqueWithoutReviewedByInput[]
  updateMany?: Prisma.UserNameChangeRequestUpdateManyWithWhereWithoutReviewedByInput | Prisma.UserNameChangeRequestUpdateManyWithWhereWithoutReviewedByInput[]
  deleteMany?: Prisma.UserNameChangeRequestScalarWhereInput | Prisma.UserNameChangeRequestScalarWhereInput[]
}

export type UserNameChangeRequestCreateWithoutUserInput = {
  id?: string
  requestedName: string
  status?: string
  source: string
  requestedAt?: Date | string
  reviewedAt?: Date | string | null
  rejectionReason?: string | null
  adminsNotified?: boolean
  notifiedAt?: Date | string | null
  reviewedBy?: Prisma.UserCreateNestedOneWithoutReviewedNameChangeRequestsInput
}

export type UserNameChangeRequestUncheckedCreateWithoutUserInput = {
  id?: string
  requestedName: string
  status?: string
  source: string
  requestedAt?: Date | string
  reviewedAt?: Date | string | null
  reviewedById?: string | null
  rejectionReason?: string | null
  adminsNotified?: boolean
  notifiedAt?: Date | string | null
}

export type UserNameChangeRequestCreateOrConnectWithoutUserInput = {
  where: Prisma.UserNameChangeRequestWhereUniqueInput
  create: Prisma.XOR<Prisma.UserNameChangeRequestCreateWithoutUserInput, Prisma.UserNameChangeRequestUncheckedCreateWithoutUserInput>
}

export type UserNameChangeRequestCreateManyUserInputEnvelope = {
  data: Prisma.UserNameChangeRequestCreateManyUserInput | Prisma.UserNameChangeRequestCreateManyUserInput[]
}

export type UserNameChangeRequestCreateWithoutReviewedByInput = {
  id?: string
  requestedName: string
  status?: string
  source: string
  requestedAt?: Date | string
  reviewedAt?: Date | string | null
  rejectionReason?: string | null
  adminsNotified?: boolean
  notifiedAt?: Date | string | null
  user: Prisma.UserCreateNestedOneWithoutNameChangeRequestsInput
}

export type UserNameChangeRequestUncheckedCreateWithoutReviewedByInput = {
  id?: string
  userId: string
  requestedName: string
  status?: string
  source: string
  requestedAt?: Date | string
  reviewedAt?: Date | string | null
  rejectionReason?: string | null
  adminsNotified?: boolean
  notifiedAt?: Date | string | null
}

export type UserNameChangeRequestCreateOrConnectWithoutReviewedByInput = {
  where: Prisma.UserNameChangeRequestWhereUniqueInput
  create: Prisma.XOR<Prisma.UserNameChangeRequestCreateWithoutReviewedByInput, Prisma.UserNameChangeRequestUncheckedCreateWithoutReviewedByInput>
}

export type UserNameChangeRequestCreateManyReviewedByInputEnvelope = {
  data: Prisma.UserNameChangeRequestCreateManyReviewedByInput | Prisma.UserNameChangeRequestCreateManyReviewedByInput[]
}

export type UserNameChangeRequestUpsertWithWhereUniqueWithoutUserInput = {
  where: Prisma.UserNameChangeRequestWhereUniqueInput
  update: Prisma.XOR<Prisma.UserNameChangeRequestUpdateWithoutUserInput, Prisma.UserNameChangeRequestUncheckedUpdateWithoutUserInput>
  create: Prisma.XOR<Prisma.UserNameChangeRequestCreateWithoutUserInput, Prisma.UserNameChangeRequestUncheckedCreateWithoutUserInput>
}

export type UserNameChangeRequestUpdateWithWhereUniqueWithoutUserInput = {
  where: Prisma.UserNameChangeRequestWhereUniqueInput
  data: Prisma.XOR<Prisma.UserNameChangeRequestUpdateWithoutUserInput, Prisma.UserNameChangeRequestUncheckedUpdateWithoutUserInput>
}

export type UserNameChangeRequestUpdateManyWithWhereWithoutUserInput = {
  where: Prisma.UserNameChangeRequestScalarWhereInput
  data: Prisma.XOR<Prisma.UserNameChangeRequestUpdateManyMutationInput, Prisma.UserNameChangeRequestUncheckedUpdateManyWithoutUserInput>
}

export type UserNameChangeRequestScalarWhereInput = {
  AND?: Prisma.UserNameChangeRequestScalarWhereInput | Prisma.UserNameChangeRequestScalarWhereInput[]
  OR?: Prisma.UserNameChangeRequestScalarWhereInput[]
  NOT?: Prisma.UserNameChangeRequestScalarWhereInput | Prisma.UserNameChangeRequestScalarWhereInput[]
  id?: Prisma.StringFilter<"UserNameChangeRequest"> | string
  userId?: Prisma.StringFilter<"UserNameChangeRequest"> | string
  requestedName?: Prisma.StringFilter<"UserNameChangeRequest"> | string
  status?: Prisma.StringFilter<"UserNameChangeRequest"> | string
  source?: Prisma.StringFilter<"UserNameChangeRequest"> | string
  requestedAt?: Prisma.DateTimeFilter<"UserNameChangeRequest"> | Date | string
  reviewedAt?: Prisma.DateTimeNullableFilter<"UserNameChangeRequest"> | Date | string | null
  reviewedById?: Prisma.StringNullableFilter<"UserNameChangeRequest"> | string | null
  rejectionReason?: Prisma.StringNullableFilter<"UserNameChangeRequest"> | string | null
  adminsNotified?: Prisma.BoolFilter<"UserNameChangeRequest"> | boolean
  notifiedAt?: Prisma.DateTimeNullableFilter<"UserNameChangeRequest"> | Date | string | null
}

export type UserNameChangeRequestUpsertWithWhereUniqueWithoutReviewedByInput = {
  where: Prisma.UserNameChangeRequestWhereUniqueInput
  update: Prisma.XOR<Prisma.UserNameChangeRequestUpdateWithoutReviewedByInput, Prisma.UserNameChangeRequestUncheckedUpdateWithoutReviewedByInput>
  create: Prisma.XOR<Prisma.UserNameChangeRequestCreateWithoutReviewedByInput, Prisma.UserNameChangeRequestUncheckedCreateWithoutReviewedByInput>
}

export type UserNameChangeRequestUpdateWithWhereUniqueWithoutReviewedByInput = {
  where: Prisma.UserNameChangeRequestWhereUniqueInput
  data: Prisma.XOR<Prisma.UserNameChangeRequestUpdateWithoutReviewedByInput, Prisma.UserNameChangeRequestUncheckedUpdateWithoutReviewedByInput>
}

export type UserNameChangeRequestUpdateManyWithWhereWithoutReviewedByInput = {
  where: Prisma.UserNameChangeRequestScalarWhereInput
  data: Prisma.XOR<Prisma.UserNameChangeRequestUpdateManyMutationInput, Prisma.UserNameChangeRequestUncheckedUpdateManyWithoutReviewedByInput>
}

export type UserNameChangeRequestCreateManyUserInput = {
  id?: string
  requestedName: string
  status?: string
  source: string
  requestedAt?: Date | string
  reviewedAt?: Date | string | null
  reviewedById?: string | null
  rejectionReason?: string | null
  adminsNotified?: boolean
  notifiedAt?: Date | string | null
}

export type UserNameChangeRequestCreateManyReviewedByInput = {
  id?: string
  userId: string
  requestedName: string
  status?: string
  source: string
  requestedAt?: Date | string
  reviewedAt?: Date | string | null
  rejectionReason?: string | null
  adminsNotified?: boolean
  notifiedAt?: Date | string | null
}

export type UserNameChangeRequestUpdateWithoutUserInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  requestedName?: Prisma.StringFieldUpdateOperationsInput | string
  status?: Prisma.StringFieldUpdateOperationsInput | string
  source?: Prisma.StringFieldUpdateOperationsInput | string
  requestedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  reviewedAt?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  rejectionReason?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  adminsNotified?: Prisma.BoolFieldUpdateOperationsInput | boolean
  notifiedAt?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  reviewedBy?: Prisma.UserUpdateOneWithoutReviewedNameChangeRequestsNestedInput
}

export type UserNameChangeRequestUncheckedUpdateWithoutUserInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  requestedName?: Prisma.StringFieldUpdateOperationsInput | string
  status?: Prisma.StringFieldUpdateOperationsInput | string
  source?: Prisma.StringFieldUpdateOperationsInput | string
  requestedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  reviewedAt?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  reviewedById?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  rejectionReason?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  adminsNotified?: Prisma.BoolFieldUpdateOperationsInput | boolean
  notifiedAt?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
}

export type UserNameChangeRequestUncheckedUpdateManyWithoutUserInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  requestedName?: Prisma.StringFieldUpdateOperationsInput | string
  status?: Prisma.StringFieldUpdateOperationsInput | string
  source?: Prisma.StringFieldUpdateOperationsInput | string
  requestedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  reviewedAt?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  reviewedById?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  rejectionReason?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  adminsNotified?: Prisma.BoolFieldUpdateOperationsInput | boolean
  notifiedAt?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
}

export type UserNameChangeRequestUpdateWithoutReviewedByInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  requestedName?: Prisma.StringFieldUpdateOperationsInput | string
  status?: Prisma.StringFieldUpdateOperationsInput | string
  source?: Prisma.StringFieldUpdateOperationsInput | string
  requestedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  reviewedAt?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  rejectionReason?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  adminsNotified?: Prisma.BoolFieldUpdateOperationsInput | boolean
  notifiedAt?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  user?: Prisma.UserUpdateOneRequiredWithoutNameChangeRequestsNestedInput
}

export type UserNameChangeRequestUncheckedUpdateWithoutReviewedByInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  userId?: Prisma.StringFieldUpdateOperationsInput | string
  requestedName?: Prisma.StringFieldUpdateOperationsInput | string
  status?: Prisma.StringFieldUpdateOperationsInput | string
  source?: Prisma.StringFieldUpdateOperationsInput | string
  requestedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  reviewedAt?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  rejectionReason?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  adminsNotified?: Prisma.BoolFieldUpdateOperationsInput | boolean
  notifiedAt?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
}

export type UserNameChangeRequestUncheckedUpdateManyWithoutReviewedByInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  userId?: Prisma.StringFieldUpdateOperationsInput | string
  requestedName?: Prisma.StringFieldUpdateOperationsInput | string
  status?: Prisma.StringFieldUpdateOperationsInput | string
  source?: Prisma.StringFieldUpdateOperationsInput | string
  requestedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  reviewedAt?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  rejectionReason?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  adminsNotified?: Prisma.BoolFieldUpdateOperationsInput | boolean
  notifiedAt?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
}



export type UserNameChangeRequestSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  userId?: boolean
  requestedName?: boolean
  status?: boolean
  source?: boolean
  requestedAt?: boolean
  reviewedAt?: boolean
  reviewedById?: boolean
  rejectionReason?: boolean
  adminsNotified?: boolean
  notifiedAt?: boolean
  user?: boolean | Prisma.UserDefaultArgs<ExtArgs>
  reviewedBy?: boolean | Prisma.UserNameChangeRequest$reviewedByArgs<ExtArgs>
}, ExtArgs["result"]["userNameChangeRequest"]>

export type UserNameChangeRequestSelectCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  userId?: boolean
  requestedName?: boolean
  status?: boolean
  source?: boolean
  requestedAt?: boolean
  reviewedAt?: boolean
  reviewedById?: boolean
  rejectionReason?: boolean
  adminsNotified?: boolean
  notifiedAt?: boolean
  user?: boolean | Prisma.UserDefaultArgs<ExtArgs>
  reviewedBy?: boolean | Prisma.UserNameChangeRequest$reviewedByArgs<ExtArgs>
}, ExtArgs["result"]["userNameChangeRequest"]>

export type UserNameChangeRequestSelectUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  userId?: boolean
  requestedName?: boolean
  status?: boolean
  source?: boolean
  requestedAt?: boolean
  reviewedAt?: boolean
  reviewedById?: boolean
  rejectionReason?: boolean
  adminsNotified?: boolean
  notifiedAt?: boolean
  user?: boolean | Prisma.UserDefaultArgs<ExtArgs>
  reviewedBy?: boolean | Prisma.UserNameChangeRequest$reviewedByArgs<ExtArgs>
}, ExtArgs["result"]["userNameChangeRequest"]>

export type UserNameChangeRequestSelectScalar = {
  id?: boolean
  userId?: boolean
  requestedName?: boolean
  status?: boolean
  source?: boolean
  requestedAt?: boolean
  reviewedAt?: boolean
  reviewedById?: boolean
  rejectionReason?: boolean
  adminsNotified?: boolean
  notifiedAt?: boolean
}

export type UserNameChangeRequestOmit<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetOmit<"id" | "userId" | "requestedName" | "status" | "source" | "requestedAt" | "reviewedAt" | "reviewedById" | "rejectionReason" | "adminsNotified" | "notifiedAt", ExtArgs["result"]["userNameChangeRequest"]>
export type UserNameChangeRequestInclude<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  user?: boolean | Prisma.UserDefaultArgs<ExtArgs>
  reviewedBy?: boolean | Prisma.UserNameChangeRequest$reviewedByArgs<ExtArgs>
}
export type UserNameChangeRequestIncludeCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  user?: boolean | Prisma.UserDefaultArgs<ExtArgs>
  reviewedBy?: boolean | Prisma.UserNameChangeRequest$reviewedByArgs<ExtArgs>
}
export type UserNameChangeRequestIncludeUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  user?: boolean | Prisma.UserDefaultArgs<ExtArgs>
  reviewedBy?: boolean | Prisma.UserNameChangeRequest$reviewedByArgs<ExtArgs>
}

export type $UserNameChangeRequestPayload<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  name: "UserNameChangeRequest"
  objects: {
    user: Prisma.$UserPayload<ExtArgs>
    reviewedBy: Prisma.$UserPayload<ExtArgs> | null
  }
  scalars: runtime.Types.Extensions.GetPayloadResult<{
    id: string
    userId: string
    requestedName: string
    status: string
    source: string
    requestedAt: Date
    reviewedAt: Date | null
    reviewedById: string | null
    rejectionReason: string | null
    adminsNotified: boolean
    notifiedAt: Date | null
  }, ExtArgs["result"]["userNameChangeRequest"]>
  composites: {}
}

export type UserNameChangeRequestGetPayload<S extends boolean | null | undefined | UserNameChangeRequestDefaultArgs> = runtime.Types.Result.GetResult<Prisma.$UserNameChangeRequestPayload, S>

export type UserNameChangeRequestCountArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> =
  Omit<UserNameChangeRequestFindManyArgs, 'select' | 'include' | 'distinct' | 'omit'> & {
    select?: UserNameChangeRequestCountAggregateInputType | true
  }

export interface UserNameChangeRequestDelegate<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> {
  [K: symbol]: { types: Prisma.TypeMap<ExtArgs>['model']['UserNameChangeRequest'], meta: { name: 'UserNameChangeRequest' } }
  /**
   * Find zero or one UserNameChangeRequest that matches the filter.
   * @param {UserNameChangeRequestFindUniqueArgs} args - Arguments to find a UserNameChangeRequest
   * @example
   * // Get one UserNameChangeRequest
   * const userNameChangeRequest = await prisma.userNameChangeRequest.findUnique({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUnique<T extends UserNameChangeRequestFindUniqueArgs>(args: Prisma.SelectSubset<T, UserNameChangeRequestFindUniqueArgs<ExtArgs>>): Prisma.Prisma__UserNameChangeRequestClient<runtime.Types.Result.GetResult<Prisma.$UserNameChangeRequestPayload<ExtArgs>, T, "findUnique", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find one UserNameChangeRequest that matches the filter or throw an error with `error.code='P2025'`
   * if no matches were found.
   * @param {UserNameChangeRequestFindUniqueOrThrowArgs} args - Arguments to find a UserNameChangeRequest
   * @example
   * // Get one UserNameChangeRequest
   * const userNameChangeRequest = await prisma.userNameChangeRequest.findUniqueOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUniqueOrThrow<T extends UserNameChangeRequestFindUniqueOrThrowArgs>(args: Prisma.SelectSubset<T, UserNameChangeRequestFindUniqueOrThrowArgs<ExtArgs>>): Prisma.Prisma__UserNameChangeRequestClient<runtime.Types.Result.GetResult<Prisma.$UserNameChangeRequestPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first UserNameChangeRequest that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {UserNameChangeRequestFindFirstArgs} args - Arguments to find a UserNameChangeRequest
   * @example
   * // Get one UserNameChangeRequest
   * const userNameChangeRequest = await prisma.userNameChangeRequest.findFirst({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirst<T extends UserNameChangeRequestFindFirstArgs>(args?: Prisma.SelectSubset<T, UserNameChangeRequestFindFirstArgs<ExtArgs>>): Prisma.Prisma__UserNameChangeRequestClient<runtime.Types.Result.GetResult<Prisma.$UserNameChangeRequestPayload<ExtArgs>, T, "findFirst", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first UserNameChangeRequest that matches the filter or
   * throw `PrismaKnownClientError` with `P2025` code if no matches were found.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {UserNameChangeRequestFindFirstOrThrowArgs} args - Arguments to find a UserNameChangeRequest
   * @example
   * // Get one UserNameChangeRequest
   * const userNameChangeRequest = await prisma.userNameChangeRequest.findFirstOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirstOrThrow<T extends UserNameChangeRequestFindFirstOrThrowArgs>(args?: Prisma.SelectSubset<T, UserNameChangeRequestFindFirstOrThrowArgs<ExtArgs>>): Prisma.Prisma__UserNameChangeRequestClient<runtime.Types.Result.GetResult<Prisma.$UserNameChangeRequestPayload<ExtArgs>, T, "findFirstOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find zero or more UserNameChangeRequests that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {UserNameChangeRequestFindManyArgs} args - Arguments to filter and select certain fields only.
   * @example
   * // Get all UserNameChangeRequests
   * const userNameChangeRequests = await prisma.userNameChangeRequest.findMany()
   * 
   * // Get first 10 UserNameChangeRequests
   * const userNameChangeRequests = await prisma.userNameChangeRequest.findMany({ take: 10 })
   * 
   * // Only select the `id`
   * const userNameChangeRequestWithIdOnly = await prisma.userNameChangeRequest.findMany({ select: { id: true } })
   * 
   */
  findMany<T extends UserNameChangeRequestFindManyArgs>(args?: Prisma.SelectSubset<T, UserNameChangeRequestFindManyArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$UserNameChangeRequestPayload<ExtArgs>, T, "findMany", GlobalOmitOptions>>

  /**
   * Create a UserNameChangeRequest.
   * @param {UserNameChangeRequestCreateArgs} args - Arguments to create a UserNameChangeRequest.
   * @example
   * // Create one UserNameChangeRequest
   * const UserNameChangeRequest = await prisma.userNameChangeRequest.create({
   *   data: {
   *     // ... data to create a UserNameChangeRequest
   *   }
   * })
   * 
   */
  create<T extends UserNameChangeRequestCreateArgs>(args: Prisma.SelectSubset<T, UserNameChangeRequestCreateArgs<ExtArgs>>): Prisma.Prisma__UserNameChangeRequestClient<runtime.Types.Result.GetResult<Prisma.$UserNameChangeRequestPayload<ExtArgs>, T, "create", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Create many UserNameChangeRequests.
   * @param {UserNameChangeRequestCreateManyArgs} args - Arguments to create many UserNameChangeRequests.
   * @example
   * // Create many UserNameChangeRequests
   * const userNameChangeRequest = await prisma.userNameChangeRequest.createMany({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   *     
   */
  createMany<T extends UserNameChangeRequestCreateManyArgs>(args?: Prisma.SelectSubset<T, UserNameChangeRequestCreateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Create many UserNameChangeRequests and returns the data saved in the database.
   * @param {UserNameChangeRequestCreateManyAndReturnArgs} args - Arguments to create many UserNameChangeRequests.
   * @example
   * // Create many UserNameChangeRequests
   * const userNameChangeRequest = await prisma.userNameChangeRequest.createManyAndReturn({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Create many UserNameChangeRequests and only return the `id`
   * const userNameChangeRequestWithIdOnly = await prisma.userNameChangeRequest.createManyAndReturn({
   *   select: { id: true },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  createManyAndReturn<T extends UserNameChangeRequestCreateManyAndReturnArgs>(args?: Prisma.SelectSubset<T, UserNameChangeRequestCreateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$UserNameChangeRequestPayload<ExtArgs>, T, "createManyAndReturn", GlobalOmitOptions>>

  /**
   * Delete a UserNameChangeRequest.
   * @param {UserNameChangeRequestDeleteArgs} args - Arguments to delete one UserNameChangeRequest.
   * @example
   * // Delete one UserNameChangeRequest
   * const UserNameChangeRequest = await prisma.userNameChangeRequest.delete({
   *   where: {
   *     // ... filter to delete one UserNameChangeRequest
   *   }
   * })
   * 
   */
  delete<T extends UserNameChangeRequestDeleteArgs>(args: Prisma.SelectSubset<T, UserNameChangeRequestDeleteArgs<ExtArgs>>): Prisma.Prisma__UserNameChangeRequestClient<runtime.Types.Result.GetResult<Prisma.$UserNameChangeRequestPayload<ExtArgs>, T, "delete", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Update one UserNameChangeRequest.
   * @param {UserNameChangeRequestUpdateArgs} args - Arguments to update one UserNameChangeRequest.
   * @example
   * // Update one UserNameChangeRequest
   * const userNameChangeRequest = await prisma.userNameChangeRequest.update({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  update<T extends UserNameChangeRequestUpdateArgs>(args: Prisma.SelectSubset<T, UserNameChangeRequestUpdateArgs<ExtArgs>>): Prisma.Prisma__UserNameChangeRequestClient<runtime.Types.Result.GetResult<Prisma.$UserNameChangeRequestPayload<ExtArgs>, T, "update", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Delete zero or more UserNameChangeRequests.
   * @param {UserNameChangeRequestDeleteManyArgs} args - Arguments to filter UserNameChangeRequests to delete.
   * @example
   * // Delete a few UserNameChangeRequests
   * const { count } = await prisma.userNameChangeRequest.deleteMany({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   * 
   */
  deleteMany<T extends UserNameChangeRequestDeleteManyArgs>(args?: Prisma.SelectSubset<T, UserNameChangeRequestDeleteManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more UserNameChangeRequests.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {UserNameChangeRequestUpdateManyArgs} args - Arguments to update one or more rows.
   * @example
   * // Update many UserNameChangeRequests
   * const userNameChangeRequest = await prisma.userNameChangeRequest.updateMany({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  updateMany<T extends UserNameChangeRequestUpdateManyArgs>(args: Prisma.SelectSubset<T, UserNameChangeRequestUpdateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more UserNameChangeRequests and returns the data updated in the database.
   * @param {UserNameChangeRequestUpdateManyAndReturnArgs} args - Arguments to update many UserNameChangeRequests.
   * @example
   * // Update many UserNameChangeRequests
   * const userNameChangeRequest = await prisma.userNameChangeRequest.updateManyAndReturn({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Update zero or more UserNameChangeRequests and only return the `id`
   * const userNameChangeRequestWithIdOnly = await prisma.userNameChangeRequest.updateManyAndReturn({
   *   select: { id: true },
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  updateManyAndReturn<T extends UserNameChangeRequestUpdateManyAndReturnArgs>(args: Prisma.SelectSubset<T, UserNameChangeRequestUpdateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$UserNameChangeRequestPayload<ExtArgs>, T, "updateManyAndReturn", GlobalOmitOptions>>

  /**
   * Create or update one UserNameChangeRequest.
   * @param {UserNameChangeRequestUpsertArgs} args - Arguments to update or create a UserNameChangeRequest.
   * @example
   * // Update or create a UserNameChangeRequest
   * const userNameChangeRequest = await prisma.userNameChangeRequest.upsert({
   *   create: {
   *     // ... data to create a UserNameChangeRequest
   *   },
   *   update: {
   *     // ... in case it already exists, update
   *   },
   *   where: {
   *     // ... the filter for the UserNameChangeRequest we want to update
   *   }
   * })
   */
  upsert<T extends UserNameChangeRequestUpsertArgs>(args: Prisma.SelectSubset<T, UserNameChangeRequestUpsertArgs<ExtArgs>>): Prisma.Prisma__UserNameChangeRequestClient<runtime.Types.Result.GetResult<Prisma.$UserNameChangeRequestPayload<ExtArgs>, T, "upsert", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>


  /**
   * Count the number of UserNameChangeRequests.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {UserNameChangeRequestCountArgs} args - Arguments to filter UserNameChangeRequests to count.
   * @example
   * // Count the number of UserNameChangeRequests
   * const count = await prisma.userNameChangeRequest.count({
   *   where: {
   *     // ... the filter for the UserNameChangeRequests we want to count
   *   }
   * })
  **/
  count<T extends UserNameChangeRequestCountArgs>(
    args?: Prisma.Subset<T, UserNameChangeRequestCountArgs>,
  ): Prisma.PrismaPromise<
    T extends runtime.Types.Utils.Record<'select', any>
      ? T['select'] extends true
        ? number
        : Prisma.GetScalarType<T['select'], UserNameChangeRequestCountAggregateOutputType>
      : number
  >

  /**
   * Allows you to perform aggregations operations on a UserNameChangeRequest.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {UserNameChangeRequestAggregateArgs} args - Select which aggregations you would like to apply and on what fields.
   * @example
   * // Ordered by age ascending
   * // Where email contains prisma.io
   * // Limited to the 10 users
   * const aggregations = await prisma.user.aggregate({
   *   _avg: {
   *     age: true,
   *   },
   *   where: {
   *     email: {
   *       contains: "prisma.io",
   *     },
   *   },
   *   orderBy: {
   *     age: "asc",
   *   },
   *   take: 10,
   * })
  **/
  aggregate<T extends UserNameChangeRequestAggregateArgs>(args: Prisma.Subset<T, UserNameChangeRequestAggregateArgs>): Prisma.PrismaPromise<GetUserNameChangeRequestAggregateType<T>>

  /**
   * Group by UserNameChangeRequest.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {UserNameChangeRequestGroupByArgs} args - Group by arguments.
   * @example
   * // Group by city, order by createdAt, get count
   * const result = await prisma.user.groupBy({
   *   by: ['city', 'createdAt'],
   *   orderBy: {
   *     createdAt: true
   *   },
   *   _count: {
   *     _all: true
   *   },
   * })
   * 
  **/
  groupBy<
    T extends UserNameChangeRequestGroupByArgs,
    HasSelectOrTake extends Prisma.Or<
      Prisma.Extends<'skip', Prisma.Keys<T>>,
      Prisma.Extends<'take', Prisma.Keys<T>>
    >,
    OrderByArg extends Prisma.True extends HasSelectOrTake
      ? { orderBy: UserNameChangeRequestGroupByArgs['orderBy'] }
      : { orderBy?: UserNameChangeRequestGroupByArgs['orderBy'] },
    OrderFields extends Prisma.ExcludeUnderscoreKeys<Prisma.Keys<Prisma.MaybeTupleToUnion<T['orderBy']>>>,
    ByFields extends Prisma.MaybeTupleToUnion<T['by']>,
    ByValid extends Prisma.Has<ByFields, OrderFields>,
    HavingFields extends Prisma.GetHavingFields<T['having']>,
    HavingValid extends Prisma.Has<ByFields, HavingFields>,
    ByEmpty extends T['by'] extends never[] ? Prisma.True : Prisma.False,
    InputErrors extends ByEmpty extends Prisma.True
    ? `Error: "by" must not be empty.`
    : HavingValid extends Prisma.False
    ? {
        [P in HavingFields]: P extends ByFields
          ? never
          : P extends string
          ? `Error: Field "${P}" used in "having" needs to be provided in "by".`
          : [
              Error,
              'Field ',
              P,
              ` in "having" needs to be provided in "by"`,
            ]
      }[HavingFields]
    : 'take' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "take", you also need to provide "orderBy"'
    : 'skip' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "skip", you also need to provide "orderBy"'
    : ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
          ? never
          : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
      }[OrderFields]
  >(args: Prisma.SubsetIntersection<T, UserNameChangeRequestGroupByArgs, OrderByArg> & InputErrors): {} extends InputErrors ? GetUserNameChangeRequestGroupByPayload<T> : Prisma.PrismaPromise<InputErrors>
/**
 * Fields of the UserNameChangeRequest model
 */
readonly fields: UserNameChangeRequestFieldRefs;
}

/**
 * The delegate class that acts as a "Promise-like" for UserNameChangeRequest.
 * Why is this prefixed with `Prisma__`?
 * Because we want to prevent naming conflicts as mentioned in
 * https://github.com/prisma/prisma-client-js/issues/707
 */
export interface Prisma__UserNameChangeRequestClient<T, Null = never, ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> extends Prisma.PrismaPromise<T> {
  readonly [Symbol.toStringTag]: "PrismaPromise"
  user<T extends Prisma.UserDefaultArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.UserDefaultArgs<ExtArgs>>): Prisma.Prisma__UserClient<runtime.Types.Result.GetResult<Prisma.$UserPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions> | Null, Null, ExtArgs, GlobalOmitOptions>
  reviewedBy<T extends Prisma.UserNameChangeRequest$reviewedByArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.UserNameChangeRequest$reviewedByArgs<ExtArgs>>): Prisma.Prisma__UserClient<runtime.Types.Result.GetResult<Prisma.$UserPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>
  /**
   * Attaches callbacks for the resolution and/or rejection of the Promise.
   * @param onfulfilled The callback to execute when the Promise is resolved.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of which ever callback is executed.
   */
  then<TResult1 = T, TResult2 = never>(onfulfilled?: ((value: T) => TResult1 | PromiseLike<TResult1>) | undefined | null, onrejected?: ((reason: any) => TResult2 | PromiseLike<TResult2>) | undefined | null): runtime.Types.Utils.JsPromise<TResult1 | TResult2>
  /**
   * Attaches a callback for only the rejection of the Promise.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of the callback.
   */
  catch<TResult = never>(onrejected?: ((reason: any) => TResult | PromiseLike<TResult>) | undefined | null): runtime.Types.Utils.JsPromise<T | TResult>
  /**
   * Attaches a callback that is invoked when the Promise is settled (fulfilled or rejected). The
   * resolved value cannot be modified from the callback.
   * @param onfinally The callback to execute when the Promise is settled (fulfilled or rejected).
   * @returns A Promise for the completion of the callback.
   */
  finally(onfinally?: (() => void) | undefined | null): runtime.Types.Utils.JsPromise<T>
}




/**
 * Fields of the UserNameChangeRequest model
 */
export interface UserNameChangeRequestFieldRefs {
  readonly id: Prisma.FieldRef<"UserNameChangeRequest", 'String'>
  readonly userId: Prisma.FieldRef<"UserNameChangeRequest", 'String'>
  readonly requestedName: Prisma.FieldRef<"UserNameChangeRequest", 'String'>
  readonly status: Prisma.FieldRef<"UserNameChangeRequest", 'String'>
  readonly source: Prisma.FieldRef<"UserNameChangeRequest", 'String'>
  readonly requestedAt: Prisma.FieldRef<"UserNameChangeRequest", 'DateTime'>
  readonly reviewedAt: Prisma.FieldRef<"UserNameChangeRequest", 'DateTime'>
  readonly reviewedById: Prisma.FieldRef<"UserNameChangeRequest", 'String'>
  readonly rejectionReason: Prisma.FieldRef<"UserNameChangeRequest", 'String'>
  readonly adminsNotified: Prisma.FieldRef<"UserNameChangeRequest", 'Boolean'>
  readonly notifiedAt: Prisma.FieldRef<"UserNameChangeRequest", 'DateTime'>
}
    

// Custom InputTypes
/**
 * UserNameChangeRequest findUnique
 */
export type UserNameChangeRequestFindUniqueArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the UserNameChangeRequest
   */
  select?: Prisma.UserNameChangeRequestSelect<ExtArgs> | null
  /**
   * Omit specific fields from the UserNameChangeRequest
   */
  omit?: Prisma.UserNameChangeRequestOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.UserNameChangeRequestInclude<ExtArgs> | null
  /**
   * Filter, which UserNameChangeRequest to fetch.
   */
  where: Prisma.UserNameChangeRequestWhereUniqueInput
}

/**
 * UserNameChangeRequest findUniqueOrThrow
 */
export type UserNameChangeRequestFindUniqueOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the UserNameChangeRequest
   */
  select?: Prisma.UserNameChangeRequestSelect<ExtArgs> | null
  /**
   * Omit specific fields from the UserNameChangeRequest
   */
  omit?: Prisma.UserNameChangeRequestOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.UserNameChangeRequestInclude<ExtArgs> | null
  /**
   * Filter, which UserNameChangeRequest to fetch.
   */
  where: Prisma.UserNameChangeRequestWhereUniqueInput
}

/**
 * UserNameChangeRequest findFirst
 */
export type UserNameChangeRequestFindFirstArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the UserNameChangeRequest
   */
  select?: Prisma.UserNameChangeRequestSelect<ExtArgs> | null
  /**
   * Omit specific fields from the UserNameChangeRequest
   */
  omit?: Prisma.UserNameChangeRequestOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.UserNameChangeRequestInclude<ExtArgs> | null
  /**
   * Filter, which UserNameChangeRequest to fetch.
   */
  where?: Prisma.UserNameChangeRequestWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of UserNameChangeRequests to fetch.
   */
  orderBy?: Prisma.UserNameChangeRequestOrderByWithRelationInput | Prisma.UserNameChangeRequestOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for UserNameChangeRequests.
   */
  cursor?: Prisma.UserNameChangeRequestWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` UserNameChangeRequests from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` UserNameChangeRequests.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of UserNameChangeRequests.
   */
  distinct?: Prisma.UserNameChangeRequestScalarFieldEnum | Prisma.UserNameChangeRequestScalarFieldEnum[]
}

/**
 * UserNameChangeRequest findFirstOrThrow
 */
export type UserNameChangeRequestFindFirstOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the UserNameChangeRequest
   */
  select?: Prisma.UserNameChangeRequestSelect<ExtArgs> | null
  /**
   * Omit specific fields from the UserNameChangeRequest
   */
  omit?: Prisma.UserNameChangeRequestOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.UserNameChangeRequestInclude<ExtArgs> | null
  /**
   * Filter, which UserNameChangeRequest to fetch.
   */
  where?: Prisma.UserNameChangeRequestWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of UserNameChangeRequests to fetch.
   */
  orderBy?: Prisma.UserNameChangeRequestOrderByWithRelationInput | Prisma.UserNameChangeRequestOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for UserNameChangeRequests.
   */
  cursor?: Prisma.UserNameChangeRequestWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` UserNameChangeRequests from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` UserNameChangeRequests.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of UserNameChangeRequests.
   */
  distinct?: Prisma.UserNameChangeRequestScalarFieldEnum | Prisma.UserNameChangeRequestScalarFieldEnum[]
}

/**
 * UserNameChangeRequest findMany
 */
export type UserNameChangeRequestFindManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the UserNameChangeRequest
   */
  select?: Prisma.UserNameChangeRequestSelect<ExtArgs> | null
  /**
   * Omit specific fields from the UserNameChangeRequest
   */
  omit?: Prisma.UserNameChangeRequestOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.UserNameChangeRequestInclude<ExtArgs> | null
  /**
   * Filter, which UserNameChangeRequests to fetch.
   */
  where?: Prisma.UserNameChangeRequestWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of UserNameChangeRequests to fetch.
   */
  orderBy?: Prisma.UserNameChangeRequestOrderByWithRelationInput | Prisma.UserNameChangeRequestOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for listing UserNameChangeRequests.
   */
  cursor?: Prisma.UserNameChangeRequestWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` UserNameChangeRequests from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` UserNameChangeRequests.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of UserNameChangeRequests.
   */
  distinct?: Prisma.UserNameChangeRequestScalarFieldEnum | Prisma.UserNameChangeRequestScalarFieldEnum[]
}

/**
 * UserNameChangeRequest create
 */
export type UserNameChangeRequestCreateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the UserNameChangeRequest
   */
  select?: Prisma.UserNameChangeRequestSelect<ExtArgs> | null
  /**
   * Omit specific fields from the UserNameChangeRequest
   */
  omit?: Prisma.UserNameChangeRequestOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.UserNameChangeRequestInclude<ExtArgs> | null
  /**
   * The data needed to create a UserNameChangeRequest.
   */
  data: Prisma.XOR<Prisma.UserNameChangeRequestCreateInput, Prisma.UserNameChangeRequestUncheckedCreateInput>
}

/**
 * UserNameChangeRequest createMany
 */
export type UserNameChangeRequestCreateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to create many UserNameChangeRequests.
   */
  data: Prisma.UserNameChangeRequestCreateManyInput | Prisma.UserNameChangeRequestCreateManyInput[]
}

/**
 * UserNameChangeRequest createManyAndReturn
 */
export type UserNameChangeRequestCreateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the UserNameChangeRequest
   */
  select?: Prisma.UserNameChangeRequestSelectCreateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the UserNameChangeRequest
   */
  omit?: Prisma.UserNameChangeRequestOmit<ExtArgs> | null
  /**
   * The data used to create many UserNameChangeRequests.
   */
  data: Prisma.UserNameChangeRequestCreateManyInput | Prisma.UserNameChangeRequestCreateManyInput[]
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.UserNameChangeRequestIncludeCreateManyAndReturn<ExtArgs> | null
}

/**
 * UserNameChangeRequest update
 */
export type UserNameChangeRequestUpdateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the UserNameChangeRequest
   */
  select?: Prisma.UserNameChangeRequestSelect<ExtArgs> | null
  /**
   * Omit specific fields from the UserNameChangeRequest
   */
  omit?: Prisma.UserNameChangeRequestOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.UserNameChangeRequestInclude<ExtArgs> | null
  /**
   * The data needed to update a UserNameChangeRequest.
   */
  data: Prisma.XOR<Prisma.UserNameChangeRequestUpdateInput, Prisma.UserNameChangeRequestUncheckedUpdateInput>
  /**
   * Choose, which UserNameChangeRequest to update.
   */
  where: Prisma.UserNameChangeRequestWhereUniqueInput
}

/**
 * UserNameChangeRequest updateMany
 */
export type UserNameChangeRequestUpdateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to update UserNameChangeRequests.
   */
  data: Prisma.XOR<Prisma.UserNameChangeRequestUpdateManyMutationInput, Prisma.UserNameChangeRequestUncheckedUpdateManyInput>
  /**
   * Filter which UserNameChangeRequests to update
   */
  where?: Prisma.UserNameChangeRequestWhereInput
  /**
   * Limit how many UserNameChangeRequests to update.
   */
  limit?: number
}

/**
 * UserNameChangeRequest updateManyAndReturn
 */
export type UserNameChangeRequestUpdateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the UserNameChangeRequest
   */
  select?: Prisma.UserNameChangeRequestSelectUpdateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the UserNameChangeRequest
   */
  omit?: Prisma.UserNameChangeRequestOmit<ExtArgs> | null
  /**
   * The data used to update UserNameChangeRequests.
   */
  data: Prisma.XOR<Prisma.UserNameChangeRequestUpdateManyMutationInput, Prisma.UserNameChangeRequestUncheckedUpdateManyInput>
  /**
   * Filter which UserNameChangeRequests to update
   */
  where?: Prisma.UserNameChangeRequestWhereInput
  /**
   * Limit how many UserNameChangeRequests to update.
   */
  limit?: number
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.UserNameChangeRequestIncludeUpdateManyAndReturn<ExtArgs> | null
}

/**
 * UserNameChangeRequest upsert
 */
export type UserNameChangeRequestUpsertArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the UserNameChangeRequest
   */
  select?: Prisma.UserNameChangeRequestSelect<ExtArgs> | null
  /**
   * Omit specific fields from the UserNameChangeRequest
   */
  omit?: Prisma.UserNameChangeRequestOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.UserNameChangeRequestInclude<ExtArgs> | null
  /**
   * The filter to search for the UserNameChangeRequest to update in case it exists.
   */
  where: Prisma.UserNameChangeRequestWhereUniqueInput
  /**
   * In case the UserNameChangeRequest found by the `where` argument doesn't exist, create a new UserNameChangeRequest with this data.
   */
  create: Prisma.XOR<Prisma.UserNameChangeRequestCreateInput, Prisma.UserNameChangeRequestUncheckedCreateInput>
  /**
   * In case the UserNameChangeRequest was found with the provided `where` argument, update it with this data.
   */
  update: Prisma.XOR<Prisma.UserNameChangeRequestUpdateInput, Prisma.UserNameChangeRequestUncheckedUpdateInput>
}

/**
 * UserNameChangeRequest delete
 */
export type UserNameChangeRequestDeleteArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the UserNameChangeRequest
   */
  select?: Prisma.UserNameChangeRequestSelect<ExtArgs> | null
  /**
   * Omit specific fields from the UserNameChangeRequest
   */
  omit?: Prisma.UserNameChangeRequestOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.UserNameChangeRequestInclude<ExtArgs> | null
  /**
   * Filter which UserNameChangeRequest to delete.
   */
  where: Prisma.UserNameChangeRequestWhereUniqueInput
}

/**
 * UserNameChangeRequest deleteMany
 */
export type UserNameChangeRequestDeleteManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which UserNameChangeRequests to delete
   */
  where?: Prisma.UserNameChangeRequestWhereInput
  /**
   * Limit how many UserNameChangeRequests to delete.
   */
  limit?: number
}

/**
 * UserNameChangeRequest.reviewedBy
 */
export type UserNameChangeRequest$reviewedByArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the User
   */
  select?: Prisma.UserSelect<ExtArgs> | null
  /**
   * Omit specific fields from the User
   */
  omit?: Prisma.UserOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.UserInclude<ExtArgs> | null
  where?: Prisma.UserWhereInput
}

/**
 * UserNameChangeRequest without action
 */
export type UserNameChangeRequestDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the UserNameChangeRequest
   */
  select?: Prisma.UserNameChangeRequestSelect<ExtArgs> | null
  /**
   * Omit specific fields from the UserNameChangeRequest
   */
  omit?: Prisma.UserNameChangeRequestOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.UserNameChangeRequestInclude<ExtArgs> | null
}
