
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
 * WARNING: This is an internal file that is subject to change!
 *
 * 🛑 Under no circumstances should you import this file directly! 🛑
 *
 * All exports from this file are wrapped under a `Prisma` namespace object in the browser.ts file.
 * While this enables partial backward compatibility, it is not part of the stable public API.
 *
 * If you are looking for your Models, Enums, and Input Types, please import them from the respective
 * model files in the `model` directory!
 */

import * as runtime from "@prisma/client/runtime/index-browser"

export type * from '../models.js'
export type * from './prismaNamespace.js'

export const Decimal = runtime.Decimal


export const NullTypes = {
  DbNull: runtime.NullTypes.DbNull as (new (secret: never) => typeof runtime.DbNull),
  JsonNull: runtime.NullTypes.JsonNull as (new (secret: never) => typeof runtime.JsonNull),
  AnyNull: runtime.NullTypes.AnyNull as (new (secret: never) => typeof runtime.AnyNull),
}
/**
 * Helper for filtering JSON entries that have `null` on the database (empty on the db)
 *
 * @see https://www.prisma.io/docs/concepts/components/prisma-client/working-with-fields/working-with-json-fields#filtering-on-a-json-field
 */
export const DbNull = runtime.DbNull

/**
 * Helper for filtering JSON entries that have JSON `null` values (not empty on the db)
 *
 * @see https://www.prisma.io/docs/concepts/components/prisma-client/working-with-fields/working-with-json-fields#filtering-on-a-json-field
 */
export const JsonNull = runtime.JsonNull

/**
 * Helper for filtering JSON entries that are `Prisma.DbNull` or `Prisma.JsonNull`
 *
 * @see https://www.prisma.io/docs/concepts/components/prisma-client/working-with-fields/working-with-json-fields#filtering-on-a-json-field
 */
export const AnyNull = runtime.AnyNull


export const ModelName = {
  Organization: 'Organization',
  User: 'User',
  Session: 'Session',
  Account: 'Account',
  Verification: 'Verification',
  Subject: 'Subject',
  SubjectSchedule: 'SubjectSchedule',
  Assignment: 'Assignment',
  AssignmentStatus: 'AssignmentStatus',
  Fund: 'Fund',
  FundContributionLog: 'FundContributionLog',
  GalleryPost: 'GalleryPost',
  GalleryPostReaction: 'GalleryPostReaction',
  DutyType: 'DutyType',
  DutySchedule: 'DutySchedule',
  Settings: 'Settings'
} as const

export type ModelName = (typeof ModelName)[keyof typeof ModelName]

/*
 * Enums
 */

export const TransactionIsolationLevel = runtime.makeStrictEnum({
  Serializable: 'Serializable'
} as const)

export type TransactionIsolationLevel = (typeof TransactionIsolationLevel)[keyof typeof TransactionIsolationLevel]


export const OrganizationScalarFieldEnum = {
  id: 'id',
  name: 'name',
  description: 'description',
  image: 'image',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
} as const

export type OrganizationScalarFieldEnum = (typeof OrganizationScalarFieldEnum)[keyof typeof OrganizationScalarFieldEnum]


export const UserScalarFieldEnum = {
  id: 'id',
  name: 'name',
  email: 'email',
  emailVerified: 'emailVerified',
  image: 'image',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt',
  phoneNumber: 'phoneNumber',
  phoneNumberVerified: 'phoneNumberVerified',
  role: 'role',
  isProfileComplete: 'isProfileComplete',
  banned: 'banned',
  banReason: 'banReason',
  banExpires: 'banExpires',
  birthday: 'birthday'
} as const

export type UserScalarFieldEnum = (typeof UserScalarFieldEnum)[keyof typeof UserScalarFieldEnum]


export const SessionScalarFieldEnum = {
  id: 'id',
  expiresAt: 'expiresAt',
  token: 'token',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt',
  ipAddress: 'ipAddress',
  userAgent: 'userAgent',
  userId: 'userId',
  impersonatedBy: 'impersonatedBy'
} as const

export type SessionScalarFieldEnum = (typeof SessionScalarFieldEnum)[keyof typeof SessionScalarFieldEnum]


export const AccountScalarFieldEnum = {
  id: 'id',
  accountId: 'accountId',
  providerId: 'providerId',
  userId: 'userId',
  accessToken: 'accessToken',
  refreshToken: 'refreshToken',
  idToken: 'idToken',
  accessTokenExpiresAt: 'accessTokenExpiresAt',
  refreshTokenExpiresAt: 'refreshTokenExpiresAt',
  scope: 'scope',
  password: 'password',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
} as const

export type AccountScalarFieldEnum = (typeof AccountScalarFieldEnum)[keyof typeof AccountScalarFieldEnum]


export const VerificationScalarFieldEnum = {
  id: 'id',
  identifier: 'identifier',
  value: 'value',
  expiresAt: 'expiresAt',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
} as const

export type VerificationScalarFieldEnum = (typeof VerificationScalarFieldEnum)[keyof typeof VerificationScalarFieldEnum]


export const SubjectScalarFieldEnum = {
  id: 'id',
  name: 'name',
  createdAt: 'createdAt'
} as const

export type SubjectScalarFieldEnum = (typeof SubjectScalarFieldEnum)[keyof typeof SubjectScalarFieldEnum]


export const SubjectScheduleScalarFieldEnum = {
  id: 'id',
  subjectId: 'subjectId',
  dayOfWeek: 'dayOfWeek',
  startTime: 'startTime',
  endTime: 'endTime',
  room: 'room',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
} as const

export type SubjectScheduleScalarFieldEnum = (typeof SubjectScheduleScalarFieldEnum)[keyof typeof SubjectScheduleScalarFieldEnum]


export const AssignmentScalarFieldEnum = {
  id: 'id',
  subjectId: 'subjectId',
  createdBy: 'createdBy',
  title: 'title',
  description: 'description',
  dueDate: 'dueDate',
  createdAt: 'createdAt'
} as const

export type AssignmentScalarFieldEnum = (typeof AssignmentScalarFieldEnum)[keyof typeof AssignmentScalarFieldEnum]


export const AssignmentStatusScalarFieldEnum = {
  id: 'id',
  userId: 'userId',
  assignmentId: 'assignmentId',
  done: 'done',
  createdAt: 'createdAt'
} as const

export type AssignmentStatusScalarFieldEnum = (typeof AssignmentStatusScalarFieldEnum)[keyof typeof AssignmentStatusScalarFieldEnum]


export const FundScalarFieldEnum = {
  id: 'id',
  totalAmount: 'totalAmount',
  currency: 'currency'
} as const

export type FundScalarFieldEnum = (typeof FundScalarFieldEnum)[keyof typeof FundScalarFieldEnum]


export const FundContributionLogScalarFieldEnum = {
  id: 'id',
  reporterId: 'reporterId',
  contributorId: 'contributorId',
  fundId: 'fundId',
  currency: 'currency',
  amount: 'amount',
  note: 'note',
  type: 'type',
  createdAt: 'createdAt'
} as const

export type FundContributionLogScalarFieldEnum = (typeof FundContributionLogScalarFieldEnum)[keyof typeof FundContributionLogScalarFieldEnum]


export const GalleryPostScalarFieldEnum = {
  id: 'id',
  userId: 'userId',
  mediaKey: 'mediaKey',
  type: 'type',
  createdAt: 'createdAt'
} as const

export type GalleryPostScalarFieldEnum = (typeof GalleryPostScalarFieldEnum)[keyof typeof GalleryPostScalarFieldEnum]


export const GalleryPostReactionScalarFieldEnum = {
  id: 'id',
  postId: 'postId',
  userId: 'userId',
  emoji: 'emoji',
  createdAt: 'createdAt'
} as const

export type GalleryPostReactionScalarFieldEnum = (typeof GalleryPostReactionScalarFieldEnum)[keyof typeof GalleryPostReactionScalarFieldEnum]


export const DutyTypeScalarFieldEnum = {
  id: 'id',
  name: 'name',
  category: 'category',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
} as const

export type DutyTypeScalarFieldEnum = (typeof DutyTypeScalarFieldEnum)[keyof typeof DutyTypeScalarFieldEnum]


export const DutyScheduleScalarFieldEnum = {
  id: 'id',
  dutyTypeId: 'dutyTypeId',
  userId: 'userId',
  dayOfWeek: 'dayOfWeek',
  status: 'status',
  completedAt: 'completedAt',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
} as const

export type DutyScheduleScalarFieldEnum = (typeof DutyScheduleScalarFieldEnum)[keyof typeof DutyScheduleScalarFieldEnum]


export const SettingsScalarFieldEnum = {
  id: 'id',
  ENABLE_WHATSAPP_BOT_FUND_REPORT: 'ENABLE_WHATSAPP_BOT_FUND_REPORT',
  ENABLE_WHATSAPP_BOT_DUTY_REPORT: 'ENABLE_WHATSAPP_BOT_DUTY_REPORT',
  ENABLE_WHATSAPP_BOT_SUBJECT_SCHEDULE_REMINDER: 'ENABLE_WHATSAPP_BOT_SUBJECT_SCHEDULE_REMINDER',
  ENABLE_WHATSAPP_BOT_BIRTHDAY_REMINDER: 'ENABLE_WHATSAPP_BOT_BIRTHDAY_REMINDER',
  ENABLE_WHATSAPP_BOT_ASSIGNMENT_REMINDER: 'ENABLE_WHATSAPP_BOT_ASSIGNMENT_REMINDER',
  announcementGroupJid: 'announcementGroupJid',
  dutyReminderTime: 'dutyReminderTime',
  scheduleReminderTime: 'scheduleReminderTime',
  assignmentReminderTime: 'assignmentReminderTime',
  birthdayReminderTime: 'birthdayReminderTime',
  fundReportDay: 'fundReportDay',
  fundReportTime: 'fundReportTime',
  dutyPersonalizedMessage: 'dutyPersonalizedMessage',
  birthdayMessageTemplate: 'birthdayMessageTemplate',
  timezone: 'timezone',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
} as const

export type SettingsScalarFieldEnum = (typeof SettingsScalarFieldEnum)[keyof typeof SettingsScalarFieldEnum]


export const SortOrder = {
  asc: 'asc',
  desc: 'desc'
} as const

export type SortOrder = (typeof SortOrder)[keyof typeof SortOrder]


export const NullsOrder = {
  first: 'first',
  last: 'last'
} as const

export type NullsOrder = (typeof NullsOrder)[keyof typeof NullsOrder]

