import { DarkTheme, DefaultTheme, type Theme } from '@react-navigation/native';

/** Stitch design system: primary #13ec5b, background-light #f6f8f6, background-dark #102216 */
export const THEME = {
  light: {
    background: '#f6f8f6',
    foreground: '#111827',
    card: '#ffffff',
    cardForeground: '#111827',
    popover: '#ffffff',
    popoverForeground: '#111827',
    primary: '#13ec5b',
    primaryForeground: '#0a2e16',
    primaryDark: '#0ea340',
    secondary: '#e5e7eb',
    secondaryForeground: '#111827',
    muted: '#f3f4f6',
    mutedForeground: '#6b7280',
    accent: '#f3f4f6',
    accentForeground: '#111827',
    destructive: '#ef4444',
    border: '#e5e7eb',
    input: '#e5e7eb',
    ring: '#13ec5b',
    radius: '0.5rem',
    surfaceDark: '#193322',
    chart1: '#13ec5b',
    chart2: '#92c9a4',
    chart3: '#0ea340',
    chart4: '#0fae43',
    chart5: '#102216',
  },
  dark: {
    background: '#102216',
    foreground: '#f9fafb',
    card: '#193322',
    cardForeground: '#f9fafb',
    popover: '#1a3524',
    popoverForeground: '#f9fafb',
    primary: '#13ec5b',
    primaryForeground: '#0a2e16',
    primaryDark: '#0fae43',
    secondary: '#162f21',
    secondaryForeground: '#f9fafb',
    muted: '#162f21',
    mutedForeground: '#9ca3af',
    accent: '#1a3524',
    accentForeground: '#f9fafb',
    destructive: '#ef4444',
    border: 'rgba(255,255,255,0.1)',
    input: 'rgba(255,255,255,0.15)',
    ring: '#13ec5b',
    radius: '0.5rem',
    surfaceDark: '#1a3524',
    chart1: '#13ec5b',
    chart2: '#92c9a4',
    chart3: '#0ea340',
    chart4: '#0fae43',
    chart5: '#102216',
  },
};

export const NAV_THEME: Record<'light' | 'dark', Theme> = {
  light: {
    ...DefaultTheme,
    colors: {
      background: THEME.light.background,
      border: THEME.light.border,
      card: THEME.light.card,
      notification: THEME.light.destructive,
      primary: THEME.light.primary,
      text: THEME.light.foreground,
    },
  },
  dark: {
    ...DarkTheme,
    colors: {
      background: THEME.dark.background,
      border: THEME.dark.border,
      card: THEME.dark.card,
      notification: THEME.dark.destructive,
      primary: THEME.dark.primary,
      text: THEME.dark.foreground,
    },
  },
};
