/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
 * This file should be your main import to use Prisma-related types and utilities in a browser. 
 * Use it to get access to models, enums, and input types.
 * 
 * This file does not contain a `PrismaClient` class, nor several other helpers that are intended as server-side only.
 * See `client.ts` for the standard, server-side entry point.
 *
 * 🟢 You can import this file directly.
 */

import * as Prisma from './internal/prismaNamespaceBrowser.js'
export { Prisma }
export * as $Enums from './enums.js'
export * from './enums.js';
/**
 * Model Organization
 * 
 */
export type Organization = Prisma.OrganizationModel
/**
 * Model User
 * 
 */
export type User = Prisma.UserModel
/**
 * Model Session
 * 
 */
export type Session = Prisma.SessionModel
/**
 * Model Account
 * 
 */
export type Account = Prisma.AccountModel
/**
 * Model Verification
 * 
 */
export type Verification = Prisma.VerificationModel
/**
 * Model Subject
 * 
 */
export type Subject = Prisma.SubjectModel
/**
 * Model SubjectSchedule
 * 
 */
export type SubjectSchedule = Prisma.SubjectScheduleModel
/**
 * Model Assignment
 * 
 */
export type Assignment = Prisma.AssignmentModel
/**
 * Model AssignmentStatus
 * 
 */
export type AssignmentStatus = Prisma.AssignmentStatusModel
/**
 * Model Fund
 * 
 */
export type Fund = Prisma.FundModel
/**
 * Model FundContributionLog
 * 
 */
export type FundContributionLog = Prisma.FundContributionLogModel
/**
 * Model GalleryPost
 * 
 */
export type GalleryPost = Prisma.GalleryPostModel
/**
 * Model GalleryPostReaction
 * 
 */
export type GalleryPostReaction = Prisma.GalleryPostReactionModel
/**
 * Model Duty
 * 
 */
export type Duty = Prisma.DutyModel
/**
 * Model DutySchedule
 * 
 */
export type DutySchedule = Prisma.DutyScheduleModel
/**
 * Model Settings
 * 
 */
export type Settings = Prisma.SettingsModel
